### ISSUE TITLE
Failed to load deferred package helm-mode

### ISSUE THREAD

**Issue by atmichalak** [hlissner/doom-emacs#1059]
On startup, I get this error and cannot use helm to search for files. M-x obviously still works as does C-x but if I use any commands related to helm, I get this error;

Failed to load deferred package helm-mode: (error Key sequence M-SPC h M starts with non-prefix key M-SPC)

### System information

<details>
<summary>Click to expand</summary>

```- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 9f2dff02fa8ed3c2162a38195e69aff1085933ea)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux nordvind 4.19.12-2-MANJARO #1 SMP PREEMPT Sun Dec 23 19:08:00 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :lang data emacs-lisp markdown (org +attach +babel +capture +export +present) (sh +fish) :config default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/local/sbin /usr/bin /opt/android-sdk/tools /opt/android-sdk/tools/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```
</details>

**Comment by y-usuzumi** [comment]
Hi. Got biten by the same issue. A quick investigation and googling shows it happens due to the introduction of general.el.

I'm not a Elisp pro nor did I take time to read in-depth about general.el. A quick and dirty workaround is to edit your ~/.doom.d/init.el and remove the `+bindings` part from the default module, as in:
```
(default +bindings +smartparens)
```

Another workaround is to go to ~/.emacs.d/core/core-keybinds.el and alter `doom-leader-alt-key` and `doom-localleader-alt-key` to something that do not use M-SPC, e.g. M-s-SPC.

Anyway,
Let's patiently wait for a fix from @hlissner

**Comment by laermannjan** [comment]
I can replicate this with a fresh install from `develop`.
If `ivy` is an option for you, replacing `helm` with it seems to avoid the problem altogether for now.


Simply, change the relevant part in your `~/.doom.d/init.el` accordingly:
```
;;; init.el

(doom!
       ... 

       :completion
       ;;helm
       ivy

       ...)
```

**Comment by X1aomu** [comment]
I found that this problem occurs starting from commit 5ad0b749. Hope this information can help.

**Comment by flyingns** [comment]
I have the same problem and have not solved it. It is really annoying.

**Comment by hlissner** [comment]
Sorry about this! As of d337e25, this issue should be resolved. Please update and let me know!

And Merry Christmas!

**Comment by SteamedFish** [comment]
I'm still having the issue with 94b4cd3ddbbc, but everything works fine with c0c84eb99b3b5360

thanks for your hard work and Merry Christmas!

**Comment by hlissner** [comment]
Happy to help! I was just about to say: I discovered the real issue behind those M-SPC errors and fixed them in c0c84eb. Glad to know it worked!

**Comment by chengyi** [comment]
@hlissner Merry Christmas!

**Comment by flyingns** [comment]
The problem was solved after the update, thanks for your hard work.
and Merry Christmas! @hlissner
