### ISSUE TITLE
package tls is obsolete on running =irc

### ISSUE THREAD

**Issue by shanavas786** [hlissner/doom-emacs#1121]
### Steps to reproduce

1. start emacs
2. M-x =irc

### System information

<details>
<summary>Click to expand</summary>

```
`DEBUG=1 make doctor`

Doom Doctor
Emacs v27.0.50
Doom v2.0.9 (aaee04e2)
shell: /bin/bash
Compiled with:
  XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2
  FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS GMP
uname -a:
  Linux sinergia 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
  x86_64 x86_64 x86_64 GNU/Linux

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking your enabled modules...
Loading /home/sinergia/.emacs.d/core/autoload/cache.el (source)...
Loading /home/sinergia/.emacs.d/modules/completion/helm/packages.el (source)...
  > (:lang cc) Couldn’t find the rtag client and/or server programs
    (rdm rc). Disabling rtags support
  > (:lang cc) Irony server isn’t installed. Run M-x
    irony-install-server
  > (:lang cc) Couldn’t find glslangValidator. GLSL code completion
    is disabled
  > (:lang rust) Couldn’t find Rust’s source code at RUST_SRC_PATH
    or ‘racer-rust-src-path’.


There are 4 warnings!

```
</details>

**Comment by hlissner** [comment]
Sorry for the late response! As of fb8a378 this should be resolved. Please update and let me know if that isn't the case and I'll reopen this issue.

Thanks for letting me know!

**Comment by shanavas786** [comment]
Issue still persist in [9f96e3ea](https://github.com/hlissner/doom-emacs/commit/9f96e3eae82fc8a841b0037834e928bef98e421c)

**Comment by hlissner** [comment]
Does `=irc` fail to open circe? It isn't trivial to prevent the `Package tls is obsolete` message, but as long as the command works, it should be fine.

**Comment by shanavas786** [comment]
![irc](https://user-images.githubusercontent.com/5337197/52773836-e268f100-3061-11e9-8693-f36ea79e9ebb.gif)

it fails to open

**Comment by hlissner** [comment]
5b48c21 is another hopeful attempt to fix this. Please update and let me know if that is the case.

**Comment by shanavas786** [comment]
running `circe` directly gave some insights.
error `Network option :port not specified` was being thrown but not shown when running `M-x =irc`

Additionally it was using `openssl` for certificate verification which stalls for some reason. installing `gnutls-cli` fixed that.

**Comment by shanavas786** [comment]
Closing it as of #1184
