### ISSUE TITLE
error load magit

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1174]
```
Buffer has been modified; could not load undo-tree history
evil-magit-change-popup-key: Symbol’s function definition is void: transient-suffix-put
evil-line-move: End of buffer
Failed to load ’magit’ package incrementally, because: (error magit-dispatch is not a transient command)
magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.
transient--layout-member: magit-dispatch is not a transient command

```

**Comment by gsnewmark** [comment]
I have the similar issue, but slightly different message for the incremental load error:
```
Failed to load ’magit’ package incrementally, because: (void-function transient-suffix-put)
```
I've upgraded Doom to the latest develop version, enabled `+forge`, and the run `doom re`. I don't remember exactly, but I think the error was like in the initial report after that. 

Then I disabled the `forge`, and tried disabling magit in `init.el`->`doom re`->enabling magit, wiping magit packages from `.local` as well as wiping everything from `.local` (`forge` remained disabled all the time), but in every case I got the `(void-function transient-suffix-put)`. I haven't tried deleting Doom completely and starting it from scratch yet.

**Comment by hlissner** [comment]
ffcfde7 should resolve this issue (by replacing magithub entirely with forge). Please update and let me know if that isn't the case.

**Comment by stefkin** [comment]
Unfortunately, I still get the `magit-disptach is not a transient command` on develop d0533fe99cf30c54ea0cd9006c1ee6f46d55e5f3

**Comment by stefkin** [comment]
Apologies, package update resolved my issue
