### ISSUE TITLE
RET on a selection does not toggle evil-multiedit

### ISSUE THREAD

**Issue by siddharthshekar** [hlissner/doom-emacs#1218]
### Observed behavior

The documentation for evil-multiedit suggests that pressing `RET` on a selection should toggle it, but this doesn't seem to be happening on the current (March 5) develop branch.

### Expected behavior

Pressing `RET` on a selection made using evil-multiedit should toggle it.

### Steps to reproduce

1. In a document, press `Option+D` on a word to mark it using evil-multiedit.
2. Press `RET`.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.1 (Feb 23, 2019)
- Doom: 2.0.9 (develop d587d11653609127f676e4d4a44c879408ce4e1b)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  elisp
  elc count: 0
  uname -a:  Darwin Siddharths-Work-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company helm :ui deft doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu term vc :tools flycheck lsp magit :lang data emacs-lisp latex markdown (org +attach +babel +capture +present) python (sh +fish) :config literate (default +bindings +snippets +evil-commands) sid :ui modeline)
  packages:  (evil-nerd-commenter gruvbox-theme matlab-mode ox-hugo ox-twbs uuidgen (webkit-katex-render :recipe (webkit-katex-render :fetcher github :repo fuxialexander/emacs-webkit-katex-render :files (*))))
  exec-path: (~/bin/ ~/Library/Python/3.7/bin/ /usr/local/opt/python/libexec/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin18.2.0/)
```
</details>

**Comment by filalex77** [comment]
I've just tested it, works for me. Could you please press `<f1> k RET` after `Option+D` and tell us what function is bound to `RET`? For me it's `evil-multiedit-toggle-or-restrict-region`.

**Comment by siddharthshekar** [comment]
In an org file, for example, this is what I see when I press `<f1> k RET`:

```
<return> runs the command +org/dwim-at-point, which is an interactive autoloaded
Lisp closure in ‘../modules/lang/org/autoload/org.el’.

It is bound to <return>, <normal-state> <return>.

(+org/dwim-at-point)

Do-what-I-mean at point.
```

**Comment by hlissner** [comment]
This should be resolved in 9d30b41. Please update and let me know if that isn't the case.

**Comment by siddharthshekar** [comment]
This works fine for `org-mode` now. I'm still seeing this issue in .m files but that's likely because `matlab-mode` defines a keybinding using `<return>`.

**Comment by hlissner** [comment]
Since I can no longer reproduce this (in `matlab-mode` either), I'll consider this resolved. Let me know if that isn't the case and I'll reopen this.
