### ISSUE TITLE
Treemacs does not work update recent upgrading

### ISSUE THREAD

**Issue by laishulu** [hlissner/doom-emacs#1257]
### Observed behavior
I am using Emacs in terminal.
After run `make upgrade && make update`
can't `<TAB>` to expand directory and `<RET>` to open file.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop 60c965ded8f1f46eb5c7a82cdbc84fc0d1a49fb0)
- Graphic display: nil (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin mao 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui deft doom doom-quit evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired eshell imenu term vc :tools flycheck lsp magit make :lang data emacs-lisp (haskell +intero) markdown (org +attach +babel +capture +export +present) python rust (sh +fish) :config default)
  packages:  ((s :modules ((:private))) (evil-textobj-column :modules ((:private))) (evil-textobj-line :modules ((:private))) (evil-textobj-syntax :modules ((:private))) (evil-textobj-entire :modules ((:private))) (aggressive-indent :modules ((:private))) (tmux-pane :modules ((:private))) (hl-fill-column :modules ((:private))) (fcitx :modules ((:private))))
  exec-path: (~/bin ~/.local/bin ~/.cargo/bin /usr/local/opt/python/libexec/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/bin /usr/local/sbin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /usr/local/MacGPG2/bin /opt/X11/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
  ```
</details>

**Comment by hlissner** [comment]
I cannot recreate this. 

1. Are there any errors/warnings in \*Messages\*? e.g. press `SPC h e` or `M-x view-echo-area-messages`

2. Does the error occur in vanilla Doom (without your private config)? e.g. press `SPC h E`, then press `C-c C-p` to launch an instance of Doom without your private config, open treemacs and try to recreate the issue.

3. What terminal are you using to run Emacs in? iterm2? Terminal?

**Comment by laishulu** [comment]
1. 
![图片](https://user-images.githubusercontent.com/1224321/54401063-d58efa00-4700-11e9-9a5a-13bc8458baa3.png)

2. still the same in vanilla Doom following your instructions.

3. failed in all of those: iterm2/iterm2+tmux/ternimal

**Comment by hlissner** [comment]
I just pushed 90f36bce, which may resolve your issue. Please update and let me know.

**Comment by laishulu** [comment]
Still does not work.

But Emacs.app works all the time. before or after this patch.

**Comment by hlissner** [comment]
Does this resolve your issue?

```elisp
(after! treemacs-evil
  (define-key evil-treemacs-state-map [return] #'treemacs-RET-action)
  (define-key evil-treemacs-state-map [tab] #'treemacs-TAB-action)
  (define-key evil-treemacs-state-map (kbd "TAB") #'treemacs-TAB-action))
```

**Comment by laishulu** [comment]
works now. Thanks!

Would you put the codes in later commit,
so user need not to config by himself?

**Comment by hlissner** [comment]
Done in a37e192, so I'll consider this resolved. However, this should probably be reported [upstream](https://github.com/Alexander-Miller/treemacs) as this isn't really a Doom issue.
