### ISSUE TITLE
[BUG] Making resize-mini-windows buffer-local while locally let-bound!

### ISSUE THREAD

**Issue by alinbxSorcerer** [hlissner/doom-emacs#1627]
Striking (save-some-buffers) or (save-buffers-kill-terminal) invoke error of "Making resize-mini-windows buffer-local while locally let-bound!"

The problem lies in `doom|setq-resize-mini-windows-for-minibuffer-setup()`

```
Debugger entered--Lisp error: "Making resize-mini-windows buffer-local while locally let-bound!"
  make-local-variable(resize-mini-windows)
  (set (make-local-variable 'resize-mini-windows) 'grow-only)
  doom|setq-resize-mini-windows-for-minibuffer-setup()
  read-from-minibuffer("File to save in: " nil (keymap keymap (36 . ivy-magic-read-file-env) (3 keymap (5 . +ivy/woccur) (19 . ivy-rotate-sort) (1 . ivy-toggle-ignore) (15 . ivy-occur)) (67108903 . ivy-avy) (33554464 . ivy-restrict-to-matches) (15 . ivy-dispatching-done-hydra) (22 . ivy-scroll-up-command) (prior . ivy-scroll-down-command) (next . ivy-scroll-up-command) (7 . keyboard-escape-quit) (right . ivy-forward-char) (32 . self-insert-command) (18 . ivy-reverse-i-search) (19 . counsel-minibuffer-history) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-whole-line . ivy-kill-whole-line) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-alt-done) (10 . ivy-alt-done) (27 keymap (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . hydra-ivy/body) (25 . ivy-insert-current-full) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (mouse-3 . ivy-mouse-dispatching-done) (mouse-1 . ivy-mouse-done) (down-mouse-1 . ignore) (13 . ivy-done)) nil file-name-history)
  ivy-read("File to save in: " read-file-name-internal :predicate file-exists-p :require-match nil :initial-input "~/Documents/OrgMode/ORG/src/" :preselect "~/Documents/OrgMode/ORG/src/ *Minibuf-1*" :def "~/Documents/OrgMode/ORG/src/ *Minibuf-1*" :history file-name-history :keymap nil :sort t :dynamic-collection nil :caller read-file-name-internal)
  ivy-completing-read("File to save in: " read-file-name-internal file-exists-p nil "~/Documents/OrgMode/ORG/src/" file-name-history "~/Documents/OrgMode/ORG/src/ *Minibuf-1*" nil)
  completing-read("File to save in: " read-file-name-internal file-exists-p nil "~/Documents/OrgMode/ORG/src/" file-name-history "~/Documents/OrgMode/ORG/src/ *Minibuf-1*")
  read-file-name-default("File to save in: " nil "/home/me/Documents/OrgMode/ORG/src/ *Minibuf-1*" nil nil nil)
  read-file-name("File to save in: " nil "/home/me/Documents/OrgMode/ORG/src/ *Minibuf-1*")
  basic-save-buffer(nil)
  save-buffer()
  save-some-buffers(nil)
  funcall-interactively(save-some-buffers nil)
  call-interactively(save-some-buffers nil nil)
  command-execute(save-some-buffers)
```

**Comment by hlissner** [comment]
I believe this has been resolved on the straight branch. Since it will be merged this Sunday, I will consider this resolved for now. I will close the thread once it has been merged.

**Comment by alinbxSorcerer** [comment]
the problem remains after I changed to straight branch. @hlissner
