### ISSUE TITLE
[BUG] Symbol’s function definition is void: battery-update

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#2135]
**Describe the issue**
- What actually happened?
Doom won't boot completely after recent upgrade. Getting the `battery-update` error, seem to happen pretty early because my settings (i.e. font settings) are not applied. SPC-based keybindings don't work either.
I've tried removing elpa/straight packages, which didn't help. Then I've completely remove ~/.emacs.d and cloned the project. That didn't help either.

<details><pre>
Debugger entered--Lisp error: (void-function battery-update)
  battery-update()
  doom-modeline-override-battery-modeline()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()

</pre></details>

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "авг 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 90c0dd6b3 2019-12-01 22:46:45 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64")
  (path "~/.node_modules/bin" "~/.bin" "~/.bin.local" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.deliver/bin" "~/.local/bin" "~/.gem/bin" "~/.emacs.d/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard fill-column hydra modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :term eshell vterm :tools eval (lookup +docsets) lsp magit :lang data emacs-lisp markdown org plantuml (ruby +lsp) sh :config literate (default +bindings +smartparens))
  (packages evil-lion org-mru-clock vimrc-mode org-cliplink org-journal haml-mode dockerfile-mode try rjsx-mode feature-mode jinja2-mode terraform-mode graphviz-dot-mode highlight-indent-guides "(rubocop :disable t)")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
See https://github.com/seagle0128/doom-modeline/issues/274 for cause and workaround.

**Comment by ineu** [comment]
Thank you, that works

**Comment by richerve** [comment]
Apparently there's already a commit that maybe tried to fix it (https://github.com/seagle0128/doom-modeline/commit/211c0d0c28c27a9f700b5c10ba2e4b0e3f9bdcd9), but is still failing. Confirmed that hlissner work around works.

**Comment by hlissner** [comment]
As of https://github.com/seagle0128/doom-modeline/commit/2fcb6e8c0f78f6d5755a09872e253e96e2b2e233 this has been resolved upstream. Run `doom udpate` to update your packages. Thanks for bringing it to my attention!

**Comment by verajosemanuel** [comment]
updated doom packages to no avail. usual keybindings still not working.
