### ISSUE TITLE
[BUG] doom doctor "x org is not installed"

### ISSUE THREAD

**Issue by atmichalak** [hlissner/doom-emacs#2284]
**What did you expect to happen?**
...
Ran `doom doctor` after a `doom upgrade`, expecting to see zero issues.

**What actually happened?**
...
`doom doctor` says `x org is not installed`

**Additional details:**
<details>
Private config is standard, except for using `doom-vibrant` as a theme and `Fira Code` as my font.
I also have this added, which may or may not lead to my previous issues with Ocaml LSP;

`(require 'opam-user-setup "~/.emacs.d/opam-user-setup.el")`

Since I'm on Fedora 31, I'm using Emacs 26.3 provided by `dnf copr enable jaroslav/emacs`

Might be related but the error in buffer is;
 "Cannot determine Magit's version (error "/home/atm/.emacs.d/.local/straight/repos/magit/lisp/magit.el" repo t static elpa dirname)"

</details>

**Steps to reproduce:**
`sudo dnf enable copr jaroslav/emacs`
`sudo dnf install emacs`
`git clone -b develop https://github.com/hlissner/doom-emacs ~/.emacs.d`
Added configuration to `init.el`
`doom refresh`
`doom doctor`

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Nov 20, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4a53f0818 2020-01-01 03:02:05 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64
        path       (~/.opam/default/bin ~/.nimble/bin ~/.rbenv/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.opam/default/ ~/.nvm/versions/node/v13.1.0/bin ~/.rbenv/shims ~/opt/idea/bin ~/bin ~/.nimble/bin ~/anaconda3/bin ~/.rbenv/bin ~/.emacs.d/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.nimble/bin ~/.rbenv/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.nimble/bin ~/.rbenv/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin ~/bin /usr/local/sbin /usr/sbin ~/bin /usr/lib/jvm/java-11-openjdk-11.0.5.10-0.fc31.x86_64/bin ~/Documents/Projects/go/bin ~/.fzf/bin)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) helm :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric (ibuffer +icons) vc :tools (eval +overlay) flycheck (lookup +docsets) lsp magit :lang assembly (cc +lsp) crystal data emacs-lisp (go +lsp) (javascript +lsp) markdown nim (ocaml +lsp) (org +dragndrop +present) (php +lsp) purescript (ruby +lsp +rbenv) (rust +lsp) scheme (sh +lsp) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
This is a regression caused [by this change](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el#L28). I am working on a rewrite of the doctor which will address this issue, but it will take me a couple days. I'll keep you posted.

**Comment by wawosz** [comment]
I confirm having the same problem on Emacs 26.1 running on Debian GNU/Linux 10 (buster) on Chrome OS aarch64 , kernel 4.19.79-07511-ge32b3719f26b. I am looking forward to the future fix.

**Comment by janhye** [comment]
I had the same problem on Emacs 26.3 running on macOS 10.15.2

**Comment by yanite** [comment]
^^/.doom-emacs.d >>> ./bin/doom doctor                                                     (base) (*develop+11693) 20:11:50
The doctor will see you now...

> Checking your Emacs version...
! Emacs 27.0.60 detected. Emacs HEAD is unstable and may cause errors.
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Package cl is deprecated
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 55 modules
  ✓ Detected 229 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :lang cc
      ! Couldn't find glslangValidator. GLSL code completion is disabled
      ! Irony server isn't installed. Run M-x irony-install-server
      ! Couldn't find the rtag client and/or server programs (rdm rc). Disabling rtags support
  x org is not installed
    > :lang rust
      ! Couldn't find the racer binary at `racer-cmd'
    > :lang web
      ! Couldn't find stylelint. Linting for CSS modes will not work.
      ! Couldn't find js-beautify. Code formatting in JS/CSS/HTML modes will not work.


There are 7 warnings!
mac os 10.14.6

**Comment by atmichalak** [comment]
Other than the `org` error, all of those can be fixed by installing the required binaries. Specifically for `:lang cc`, install irony and rtags or enable the `lsp` module for `doom` and add the `+lsp` modifier to cc in the `init.el`.

**Comment by arunkhattri** [comment]
still getting the same error "x org is not installed"
Emacs 26.3
experimenting wtith doom emacs for the last 5 days....

**Comment by JAQRZN** [comment]
This issue can be worked around by uninstalling and reinstalling.

**Comment by hlissner** [comment]
As of 68b5f68 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ncihnegn** [comment]
As of https://github.com/hlissner/doom-emacs/commit/2884dd9ea70b0bfedf1740baa3f70561a7277afe it is not fixed yet.
The message is now
```
  > Checking your enabled modules...
      x Missing emacs package: org
```

**Comment by hlissner** [comment]
My bad. 8f8d796 should finally fix this. Thanks for letting me know!

**Comment by torpak** [comment]
yes that fixed it for me. :-)

**Comment by pellenation** [comment]
I had the same issue. But now im getting other errors.

```text
Package cl is deprecated
Failed to load ’git-commit’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’magit’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-compat’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-list’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-pcomplete’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-src’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-footnote’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-macro’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’ob’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-agenda’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org-capture’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
Failed to load ’org’ package incrementally, because: (wrong-type-argument stringp (t . doom-detect-indentation-h))
evil-collection error: (wrong-type-argument stringp (t . doom-detect-indentation-h))
```

anyone who knows how to fix this?

**Comment by hlissner** [comment]
@pellenation Can't reproduce that. Could you run `doom sync`? If that doesn't help, [generate a backtrace from the error](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).

**Comment by pellenation** [comment]
I ran doom sync but it didnt help. Also tried to reinstall doom emacs and that didnt help either. 

This is the backtrace. Dont know if it's the correct one?

Im running emacs `27.0.90`

```text
Debugger entered--Lisp error: (wrong-type-argument stringp mouse-wheel-down-event)
  string-match("\\(\\`\\|/\\)buff-menu\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\..." mouse-wheel-down-event)
  load-history-filename-element("\\(\\`\\|/\\)buff-menu\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\...")
  eval-after-load("buff-menu" (closure ((req . "buff-menu") (--dolist-tail-- "buff-menu") (reqs "buff-menu") (m . buff-menu) (mode buff-menu "buff-menu") (--dolist-tail-- (buff-menu "buff-menu")) (modes (buff-menu "buff-menu")) t) nil (evil-collection-require m) (funcall (intern (concat "evil-collection-" (symbol-name m) "-setup"))) (let ((mode-keymaps (condition-case nil (progn (symbol-value ...)) (error nil)))) (run-hook-with-args 'evil-collection-setup-hook m mode-keymaps))))
  (let ((req (car --dolist-tail--))) (eval-after-load req #'(lambda nil (evil-collection-require m) (funcall (intern (concat "evil-collection-" (symbol-name m) "-setup"))) (let ((mode-keymaps (condition-case nil ... ...))) (run-hook-with-args 'evil-collection-setup-hook m mode-keymaps)))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((req (car --dolist-tail--))) (eval-after-load req #'(lambda nil (evil-collection-require m) (funcall (intern (concat "evil-collection-" ... "-setup"))) (let ((mode-keymaps ...)) (run-hook-with-args 'evil-collection-setup-hook m mode-keymaps)))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- reqs)) (while --dolist-tail-- (let ((req (car --dolist-tail--))) (eval-after-load req #'(lambda nil (evil-collection-require m) (funcall (intern ...)) (let (...) (run-hook-with-args ... m mode-keymaps)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let ((m mode) (reqs (list mode))) (if (listp mode) (progn (setq m (car mode) reqs (cdr mode)))) (let ((--dolist-tail-- reqs)) (while --dolist-tail-- (let ((req (car --dolist-tail--))) (eval-after-load req #'(lambda nil (evil-collection-require m) (funcall ...) (let ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (let ((mode (car --dolist-tail--))) (let ((m mode) (reqs (list mode))) (if (listp mode) (progn (setq m (car mode) reqs (cdr mode)))) (let ((--dolist-tail-- reqs)) (while --dolist-tail-- (let ((req (car --dolist-tail--))) (eval-after-load req #'(lambda nil ... ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((mode (car --dolist-tail--))) (let ((m mode) (reqs (list mode))) (if (listp mode) (progn (setq m (car mode) reqs (cdr mode)))) (let ((--dolist-tail-- reqs)) (while --dolist-tail-- (let ((req ...)) (eval-after-load req #'...) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- modes)) (while --dolist-tail-- (let ((mode (car --dolist-tail--))) (let ((m mode) (reqs (list mode))) (if (listp mode) (progn (setq m (car mode) reqs (cdr mode)))) (let ((--dolist-tail-- reqs)) (while --dolist-tail-- (let (...) (eval-after-load req ...) (setq --dolist-tail-- ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  evil-collection-init(((buff-menu "buff-menu")))
  (condition-case err (evil-collection-init (list module)) ((debug error) (message "evil-collection error: %s" err) nil))
  (if (memq (or (car-safe module) module) disabled-list) nil (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM [editor/evil] Initialized evil-collection-%s ..." 0 5 (face font-lock-comment-face) 5 19 (face warning)) (or (car-safe module) module) (if doom-init-time "" "(too early!)"))))) (condition-case err (evil-collection-init (list module)) ((debug error) (message "evil-collection error: %s" err) nil)))
  +evil-collection-init((buff-menu "buff-menu"))
  doom--transient-2-h()
  apply(doom--transient-2-h nil)
  Buffer-menu-mode()
  list-buffers-noselect(nil)
  buffer-menu(nil)
  funcall-interactively(buffer-menu nil)
  call-interactively(buffer-menu)
  evil-ex-call-command(nil #("ls" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil)
  eval((evil-ex-call-command nil #("ls" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil))
  evil-ex-execute(#("ls" 0 1 (ex-index 1) 1 2 (ex-index 2)))
  #f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat (cond ((and (evil-visual-state-p) evil-ex-visual-char-range (memq (evil-visual-type) '(inclusive exclusive))) "`<,`>") ((evil-visual-state-p) "'<,'>") (current-prefix-arg (let ((arg (prefix-numeric-value current-prefix-arg))) (cond ((< arg 0) (setq arg (1+ arg))) ((> arg 0) (setq arg (1- arg)))) (if (= arg 0) "." (format ".,.%+d" arg))))) evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1ff60dd2af3d>)(nil)
  apply(#f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat ... evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1ff60dd2af3d>) nil)
  #f(advice-wrapper :before #f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat (cond ((and (evil-visual-state-p) evil-ex-visual-char-range (memq (evil-visual-type) '(inclusive exclusive))) "`<,`>") ((evil-visual-state-p) "'<,'>") (current-prefix-arg (let ((arg (prefix-numeric-value current-prefix-arg))) (cond ((< arg 0) (setq arg (1+ arg))) ((> arg 0) (setq arg (1- arg)))) (if (= arg 0) "." (format ".,.%+d" arg))))) evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1ff60dd2af3d>) doom--transient-8-h)(nil)
  apply(#f(advice-wrapper :before #f(compiled-function (&optional initial-input) (interactive (list (let ((s ...)) (and (> ... 0) s)))) #<bytecode 0x1ff60dd2af3d>) doom--transient-8-h) nil)
  (let ((completion-in-region-function #'completion--in-region)) (apply orig-fn args))
  +ivy--inhibit-completion-in-region-a(#f(advice-wrapper :before #f(compiled-function (&optional initial-input) (interactive (list (let ((s ...)) (and (> ... 0) s)))) #<bytecode 0x1ff60dd2af3d>) doom--transient-8-h) nil)
  apply(+ivy--inhibit-completion-in-region-a #f(advice-wrapper :before #f(compiled-function (&optional initial-input) (interactive (list (let ((s ...)) (and (> ... 0) s)))) #<bytecode 0x1ff60dd2af3d>) doom--transient-8-h) nil)
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
```

**Comment by hlissner** [comment]
@pellenation I'm sorry, but these issues don't make much sense to me. They're complaining about things that don't happen: comparisons against data values that don't exist, in Doom or its packages, so it must be something in your private config. Is it up somewhere I can see it?

**Comment by oli67** [comment]
I get the exact same message as the original poster (Emacs 27.0.91)

**Comment by ergenekonyigit** [comment]
I get same error too. (Emacs 27.0.91-1)

**Comment by hlissner** [comment]
@oli67 @ergenekonyigit The only explanation is you're on old versions of Doom. Please include your `M-x doom/info`.

**Comment by ergenekonyigit** [comment]
sorry for the unclear comment, https://github.com/hlissner/doom-emacs/issues/2284#issuecomment-629404145 i have got this error. 

<details>

```
emacs   version    27.0.91
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER
        build      Jun 07, 2020
        buildopts  (--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD e7678f47 2020-06-05 16:05:55 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (/full/path/to/graalvm/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin ~/.sdkman/candidates/java/current/bin /full/path/to/graalvm/bin ~/.cargo/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools ~/.fzf/bin ~/flutter/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools ~/flutter/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold multiple-cursors snippets :emacs dired electric (undo +tree) vc :checkers syntax :tools (eval +overlay) lookup lsp macos magit :lang (clojure +lsp) emacs-lisp (json +lsp) (javascript +lsp) markdown org (rust +lsp) sh (web +lsp) :config (default +bindings))
        packages   ((turkish) (kaolin-themes) (spacemacs-theme) (heaven-and-hell) (swiper) (counsel) (which-key) (ivy-hydra) (magit-delta :recipe (:host github :repo dandavison/magit-delta) :pin d988abd) (org-super-agenda))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by oli67** [comment]
It was v2.0.9 but not the newest commit. "doom upgrade" resolved the issue :-)

**Comment by ergenekonyigit** [comment]
@oli67 okay, i upgraded latest commit. issue not fixed, still `Wrong type argument: stringp, mouse-wheel-down-event`

```((emacs
  (version . "27.0.91")
  (features . "NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER")
  (build . "Jul 11, 2020")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 46d6d0b58 2020-06-29 15:12:30 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64")
  (path "/full/path/to/graalvm/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "~/.sdkman/candidates/java/current/bin" "/full/path/to/graalvm/bin" "~/.cargo/bin" "~/Library/Android/sdk/emulator" "~/Library/Android/sdk/tools" "~/Library/Android/sdk/tools/bin" "~/Library/Android/sdk/platform-tools" "~/.fzf/bin" "~/flutter/bin" "~/Library/Android/sdk/emulator" "~/Library/Android/sdk/tools" "~/Library/Android/sdk/tools/bin" "~/Library/Android/sdk/platform-tools" "~/flutter/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold multiple-cursors snippets :emacs dired electric (undo +tree) vc :checkers syntax :tools (eval +overlay) lookup lsp macos magit :lang (clojure +lsp) emacs-lisp (json +lsp) (javascript +lsp) markdown org (rust +lsp) sh (web +lsp) :config (default +bindings))
  (packages (turkish) (kaolin-themes) (spacemacs-theme) (heaven-and-hell) (swiper) (counsel) (which-key) (ivy-hydra) (magit-delta :recipe (:host github :repo "dandavison/magit-delta") :pin "d988abd") (org-super-agenda) (solaire-mode :disable t))
  (unpin "n/a")
  (elpa "n/a")))```

**Comment by hlissner** [comment]
If you are suffering `Wrong type argument: stringp, mouse-wheel-down-event` errors please create a new issue for it as it is no longer relevant to this thread.
