### ISSUE TITLE
+lookup/references evil-collection Error

### ISSUE THREAD

**Issue by eyingxuan** [hlissner/doom-emacs#2394]
**What did you expect to happen?**
+lookup/references to invoke merlin-occurences and work

**What actually happened?**
merlin-occurences was not called, and the following error was thrown. 
`evil-collection error: (file-missing Cannot open load file No such file or directory /Users/yingxuan/.emacs.d/.local/straight/build/evil-collection/modes/replace/evil-collection-replace)`

merlin-occurences still works if invoked with M-x.

**Additional details:**
Backtrace 
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "/Users/yingxuan/.emacs.d/.local/straight/build/evil-collection/modes/replace/evil-collection-replace")
  require(evil-collection-replace "/Users/yingxuan/.emacs.d/.local/straight/build/evil-collection/modes/replace/evil-collection-replace" nil)
  evil-collection-require(replace)
  #f(compiled-function () #<bytecode 0x44976215>)()
  eval-after-load(replace #f(compiled-function () #<bytecode 0x44976215>))
  evil-collection-init((replace))
  (condition-case err (evil-collection-init (list module)) ((debug error) (message "evil-collection error: %s" err) nil))
  (if (memq (or (car-safe module) module) disabled-list) nil (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM [editor/evil] Initialized evil-collection-%s %s" 0 5 (face font-lock-comment-face) 5 19 (face warning)) (or (car-safe module) module) (if doom-init-time "" "(too early!)"))))) (condition-case err (evil-collection-init (list module)) ((debug error) (message "evil-collection error: %s" err) nil)))
  +evil-collection-init(replace)
  doom--transient-17226783-h()
  apply(doom--transient-17226783-h nil)
  occur-mode()
  merlin-occurrences-populate-buffer((((assoc) (start (assoc) (line . 350) (col . 4)) (end (assoc) (line . 350) (col . 13))) ((assoc) (start (assoc) (line . 356) (col . 33)) (end (assoc) (line . 356) (col . 42)))))
  merlin-occurrences-list((((assoc) (start (assoc) (line . 350) (col . 4)) (end (assoc) (line . 350) (col . 13))) ((assoc) (start (assoc) (line . 356) (col . 33)) (end (assoc) (line . 356) (col . 42)))))
  merlin-occurrences()
  funcall-interactively(merlin-occurrences)
  call-interactively(merlin-occurrences)
```

**Steps to reproduce:**
1. Open an ocaml file
2. Call +lookup/references

**System information:**
<details><pre>
```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Dec 23, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 453e20534 2020-01-15 11:19:32 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (~/.opam/4.09.0/bin /Users/username/.pyenv ~/.pyenv/shims ~/.cargo/bin #/usr/local/opt/llvm/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin ~/Google Drive/College/Research/plink_mac_20181202 /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /opt/X11/bin /Users/username/.pyenv ~/.NVM_DIR/versions/node/v11.10.1/bin)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets (word-wrap +global-word-wrap-mode) :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools debugger editorconfig ein (eval +overlay) (lookup +docsets) lsp macos magit make pdf :lang (cc +lsp) coq data emacs-lisp javascript (latex +latexmk) markdown ocaml (org +dragndrop +pomodoro +present) (python +lsp +pyenv) (rust +lsp) sh web :app calendar :config (default +bindings +smartparens))
        packages   ((proof-general :pin "bee3f802ada921fb8988edb96a8b41429f7c622c") px multi-term calfw-ical)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
As of 8a01ef9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by eyingxuan** [comment]
Thanks for the quick response! 


The previous error seems to be fixed, and this might be a separate issue, but I'm not sure why merlin-occurences still doesn't work with SPC c D. The function seems to be called (I see it with debug mode) but the minibuffer doesn't update. It does work if I invoke it with M-x though. 

The minibuffer that pops up with M-x also doesn't seem to have evil-mode enabled, if this is related.

**Comment by hlissner** [comment]
Does this fix it?

```elisp
(after! tuareg
  (set-lookup-handlers! 'tuareg-mode :async t
    :definition #'merlin-locate
    :references #'merlin-occurrences
    :documentation #'merlin-document))
```

> The minibuffer that pops up with M-x also doesn't seem to have evil-mode enabled, if this is related.

That is unrelated. This just means there is no evil configuration for whatever buffer those commands pop up. As I don't use ocaml, I am unable to implement it myself, but I am open a PR.

**Comment by eyingxuan** [comment]
That seems to have did the trick! Thanks. 

As for evil-mode for the minibuffer, I don't think I'm well versed enough in Emacs Lisp at this point to submit a PR, but I might in the future.
