### ISSUE TITLE
swiper error: void-variable ivy-regex

### ISSUE THREAD

**Issue by mpardalos** [hlissner/doom-emacs#2433]
When running (swiper) I get the error
```
Error in post-command-hook (ivy--queue-exhibit): (void-variable ivy-regex)
```
I do get swiper in the minibuffer afterwards but it's empty. It's also pretty weird that enabling (toggle-debug-on-error) does not give a stacktrace

Setting ivy-regex to nil in my config makes the problem go away. It also appears with all combinations of +prescient and +fuzzy (thought I would give that a try)

My private config: 
https://github.com/mpardalos/dotfiles/tree/master/doom_emacs

And my doom-info
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop de6732b4a 2020-01-25 15:58:09 -0500
        dir        ~/.config/dotfiles/doom_emacs/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/sh
        uname      Linux 5.4.12-arch1-1 #1 SMP PREEMPT Tue, 14 Jan 2020 21:44:31 +0000 x86_64
        path       (/opt/omnisharp-roslyn/ ~/.bin/ ~/.emacs.d/bin ~/.emacs.d/bin ~/.local/bin ~/.bin /usr/local/sbin /usr/local/bin /usr/bin /opt/intel/mediasdk/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (ivy +icons +prescient +fuzzy) (company +auto) :ui doom modeline ophints hl-todo nav-flash treemacs (popup +all +defaults) (pretty-code +fira) vc-gutter vi-tilde-fringe window-select hydra zen :editor (evil +everywhere +commands) snippets file-templates multiple-cursors rotate-text fold :emacs (dired +icons) electric vc :tools (lookup +docsets) eval make magit lsp editorconfig pdf ein :lang (sh +fish) emacs-lisp markdown (csharp +unity) (haskell +lsp) (org +attach +babel +export +present) (cc +lsp) ocaml idris (web +html +css) (latex +latexmk +viewers) (python +lsp) (fsharp +lsp) :checkers spell syntax :term vterm eshell :config default)
        packages   (bison-mode vimrc-mode ripgrep (alloy-mode :recipe (:host github :repo "dwwmmn/alloy-mode")) org-ref fill-column-indicator (evil-snipe :disable t :pin "3ec8adfd4990f95fa0fab2b7019ead3596857673") rebecca-theme)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this. Are you sure ivy is up-to-date? There were recently a number of breaking updates upstream that were fixed. Run `doom update` to update your packages.

**Comment by mpardalos** [comment]
I just ran `doom upgrade` and `doom update` and I'm still getting the same behaviour. 

Maybe it's something in my config? The weird thing is I have not set any ivy-related options.

**Comment by mpardalos** [comment]
deleting `~/.emacs.d/.local/straight/build/ivy/` and then `doom refresh` fixed the issue. I don't know what actually happened but this tends to work generally so who knows. 

Closing

**Comment by jgarvin** [comment]
This just happened to me after moving my old ~/.emacs.d/packages-blah out of the way to force everything to reinstall, and I'm not using doom-emacs. I think the ivy version in melpa is foobar.

**Comment by jgarvin** [comment]
also note the setting to nil workaround doesn't fully work, you instead get this in messages:

Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument integer-or-marker-p nil)

**Comment by jgarvin** [comment]
The problem is mixing gnu and melpa repos. Making melpa be preferred fixed it.
