### ISSUE TITLE
Support Embedded Elixir files (.eex) with web-mode

### ISSUE THREAD

**Issue by darioghilardi** [hlissner/doom-emacs#2564]
Doom does not correctly handle Embedded Elixir files (.eex), as instead of opening them in `web-mode`, which supports those files, it opens them in `mhtml-mode`.

The following lines are a temporary fix until the configuration for `web-mode` in Doom is fixed:
```
(add-to-list 'auto-mode-alist '("\\.html\\.eex\\'" . web-mode))
(setq web-mode-engines-alist
      '(("elixir" . "\\.html\\.eex\\'")))
```

**Comment by hlissner** [comment]
As of f0bc835 and 4b8986c this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by darioghilardi** [comment]
It's working perfectly! Thank you! 👍

**Comment by jsmestad** [comment]
@hlissner I am still getting mhtml-mode when opening `.eex` or `.leex` files. I have to manually switch over to `web-mode`.

Happy to diagnose, but not sure how to trace it if you can point me in the right direction.
