### ISSUE TITLE
With Evil disabled transient mark doesn't work with home/end bindings

### ISSUE THREAD

**Issue by drrlvn** [hlissner/doom-emacs#2756]
**What did you expect to happen?**
When pressing `C-S-a` (bound by default to `doom/backward-to-bol-or-indent`), I expect the cursor to move to the beginning of the line and the text between the previous position and the new one to be selected.

**What actually happened?**
The cursor moves but nothing is selected.

**Additional details:**
I think the issue is that the custom function doom uses for home/end doesn't support transient mark mode. According to [Emacs documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Shift-Selection.html#Shift-Selection):

> Shift-selection only works if the shifted cursor motion key is not already bound to a separate command (see Customization). For example, if you bind S-C-f to another command, typing S-C-f runs that command instead of performing a shift-selected version of C-f (forward-char).

Private config: https://github.com/drrlvn/.doom.d

**Steps to reproduce:**
1. Place cursor in middle of a line of text
2. Press `C-S-a` (Control-Shift-a)

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Mar 20, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.local/bin ~/.cargo/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/python/libexec/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.3.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp markdown (org +dragndrop +present) (python +lsp) (rust +lsp) (sh +fish) :config (default +bindings))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Does this fix `doom/backward-to-bol-or-indent`?

```elisp
;; add to ~/.doom.d/config.el
(defadvice! shift-translate-command (fn &rest args)
  :around #'doom/backward-to-bol-or-indent
  (let ((this-command-keys-shift-translated t))
    (apply fn args)))
```

**Comment by hlissner** [comment]
Nevermind the snippet above. This should be fixed as of f4ff7fd. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by drrlvn** [comment]
Thanks for the quick response and fix!

This is partially resolved though - while `C-S-a` now activates the mark, it remains active when letting go of Shift and moving the cursor around. This is not the usual behavior with transient mark mode - compare to `M-S-b` which activates the mark but when the cursor is moved without Shift pressed the it gets deactivated.

**Comment by hlissner** [comment]
I can't say I understand the nuances of the mark, `shift-select-mode`, and `transient-mark-mode`, being an exclusive evil user. Do you have an example of shift-select motion whose command _isn't_ defined in C? I cannot find any examples of this functionality implemented in elisp, so I don't know how to extend this functionality to custom commands.

**Comment by hlissner** [comment]
Nevermind, https://www.emacswiki.org/emacs/ShiftSelectMode gave me the clue I needed. As of 8f685a3 both `C-a` and `C-e` should be properly shift-select aware.

**Comment by drrlvn** [comment]
Perfect, thank you very much! 😄
