### ISSUE TITLE
Error during the installation process (err=[-50] The request is invalid)

### ISSUE THREAD

**Issue by igorlakic** [hlissner/doom-emacs#2781]
I get this error message during the installation process:
```
$ ~/.emacs.d/bin/doom install
Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping

gnutls.el: (err=[-50] The request is invalid.) boot: (:priority SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3 :hostname raw.githubusercontent.com :loglevel 0 :min-prime-bits 3072 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error t :callbacks nil)
x There was an unexpected error:
  Type: gnutls-error
  Message:
    GnuTLS error
  Data:
    #<process raw.githubusercontent.com>
    -50

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d install

If you file a bug report, please include it!
```
I'm a newbie in the world of Emacs (I'm a Vim user but heard awesome things about your Emacs distribution) so if I left out something, sorry in advance!

`M-x view-echo-area-messages`:
```
Autoload file error: autoloads.el -> (file-missing Cannot open load file No such file or directory /home/igor/.emacs.d/.local/autoloads)
Autoload file error: autoloads.pkg.el -> (file-missing Cannot open load file No such file or directory /home/igor/.emacs.d/.local/autoloads.pkg)
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3 :hostname raw.githubusercontent.com :loglevel 0 :min-prime-bits 3072 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error t :callbacks nil)
Error in pre-command-hook (doom--transient-1-h): (void-function gcmh-mode)
You can run the command ‘view-echo-area-messages’ with C-h e
Mark set [2 times]

```
**System information:**
<details><pre>
emacs   version    26.3
	features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
	build      Sep 16, 2019
	buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
	windowsys  x
	daemonp    nil
doom    version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD 61faef708 2020-03-27 15:08:55 -0400
	dir        ~/.doom.d/
system  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64
	path       (~/.cargo/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
With #2782 merged this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by igorlakic** [comment]
@hlissner Works like a charm! Thank you Henrik!

**Comment by dbechrd** [comment]
@hlissner I'm still getting this error on the latest develop branch. It's weird that develop is the default branch not master.. i tried master and there's no `doom` executable in `.emacs.d/bin` so I'm assuming develop is the effective master? 🤔

**Comment by hlissner** [comment]
@dbechrd `develop` is the main branch at the moment, yes.

If you are still getting this issue, please show me your `M-x doom/info` and the value of `libgnutls-version` (you can acquire it through `SPC h v libgnutls-version`).

**Comment by dbechrd** [comment]
@hlissner 
```
emacs   version    26.3
	features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
	build      Aug 29, 2019
	buildopts  (--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3')
	windowsys  w32
	daemonp    nil
doom    version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD c80573e5b 2020-04-01 17:31:09 -0400
	dir        c:/Users/user/.doom.d/
system  type       windows-nt
	config     x86_64-w64-mingw32
	shell      C:\Program Files\Git\usr\bin\bash.exe
	uname      n/a
	path       (...)
config  envfile    nil
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp markdown org sh :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
```
```
libgnutls-version’s value is 30608
```

**Comment by hlissner** [comment]
@dbechrd See #2816
