### ISSUE TITLE
Non-image files not behaving as expected with dragndrop

### ISSUE THREAD

**Issue by jlmaccal** [hlissner/doom-emacs#3056]
**What did you expect to happen?**
With `org-download-method` set to `'attach`, when an image is dragged onto an org buffer:
- the image is stored using `org-attach`
- an ID property will be created on the parent heading
- the file will be copied into a subdirectory of `.attach` depending on the id
- a link similar to `[[attachment:DATE_TIMEimage.png]]` will. be created.

Non-image files should be similarly stored using `org-attach`.

**What actually happened?**
Upon dragndrop, non-image files are not stored using `org-attach`, but are stored in the `.attach` directory directly, i.e. not in a subdirectory.

If no image has been previously dragged in this session, the link produced will have the form `[[attachment:.attach/_DATE_TIMEfilename.ext]]`.

However, if an image has been previously dragged, the link produced will instead have the form 
``[[attachment:../../_DATE_TIMEfilename.ext]]``.

**Additional details:**

**Private Config**
<details>
<pre>
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "Source Code Pro" :size 16))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)

(setq org-directory "~/Org/")

(setq org-roam-directory "~/Org/")

(use-package! org
  :custom
  (org-startup-folded nil))

(after! org-download
  (setq org-download-image-org-width 500))

(after! org-journal
  (setq org-journal-dir "~/Org/")
  (setq org-journal-file-type 'weekly)
  (setq org-journal-file-format "journal-%Y-%m-%d.org")
  (setq org-journal-date-format "%A, %d %B %Y")
  (setq org-journal-find-file 'find-file)
  (setq org-journal-carryover-items ""))

(after! pdf-tools
  (map! :map pdf-view-mode-map
        :gn "C-d" 'pdf-view-scroll-up-or-next-page
        :gn "C-u" 'pdf-view-scroll-down-or-previous-page) )
</pre>
</details>

**Steps to reproduce:**
1. Open an org buffer
2. Drag a non-image (e.g. PDF) file

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "May 02, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 9a628c7a1 2020-05-06 16:43:42 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/anaconda3/bin" "~/anaconda3/condabin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup lsp macos magit pdf :lang cc data emacs-lisp latex markdown (org +dragndrop +journal +roam +noter +present) (python +lsp +conda) sh :config literate (default +bindings +smartparens))
  (packages (helm-org-rifle) (dash) (f) (s))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 994028b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jlmaccal** [comment]
@hlissner This doesn't have any effect; I still get the same behaviour. This is with 0f696ec8b .

**Comment by hlissner** [comment]
4757144 should hopefully resolve this. Let me know if it doesn't and I'll reopen it.
