### ISSUE TITLE
Package undo-fu does not autostart undo-fu-mode.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#3089]
**What did you expect to happen?**
I have set `(:emacs undo)` without `+tree`. I expect `undo-fu` to load and `undo-fu-mode` to start automatically, so my bindings to `undo` and `redo` get activated.

**What actually happened?**
`undo-fu` is not loaded and `redo` and `undo-fu-mode` are unbound.

**Additional details:**
- The issue lies with [this line](https://github.com/hlissner/doom-emacs/blob/1529dcaaf57fc8a7ba3681931bb03cfad222fac6/modules/emacs/undo/config.el#L5) which references a function `doom-switch-buffer`, which doesn't exist.
- It can be solved by either adding `undo-fu` to `after-init-hook` or replacing `doom-switch-buffer` with an existing function. One such function might be `switch-to-buffer`, although I have not tested it.

**Steps to reproduce:**
1. Activate `(:emacs undo)` in `init.el`.
2. Bind `redo` to a key (e.g. `C-r`) in `config.el`.
3. Restart Emacs.
4. Press said key.
4. An error occurs: `Wrong type argument: commandp, redo`

**Workaround:**
```emacs-lisp
(when (and (featurep! :emacs undo)
           (not (featurep! :emacs undo +tree)))
  (require 'undo-fu))
```

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 1529dcaaf 2020-05-11 05:32:51 -0400")
  (dir . "~/.config/doom-emacs/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.6.10-3-MANJARO #1 SMP PREEMPT Sun May 3 11:03:28 UTC 2020 x86_64")
  (path "~/bin" "~/opt/bin" "/usr/local/bin" "/usr/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin" "~/.dotnet/tools" "~/var/go/bin" "~/.local/share/cabal/bin" "~/opt/ghcup/bin" "~/.gem/ruby/2.7.0" "~/.local/share/cargo/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold fmt rotate-text snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit :lang (cc +lsp) clojure common-lisp data emacs-lisp haskell latex (lua +moonscript) markdown org (python +lsp) (rust +lsp) sh :config literate (default +evil +bindings +smartparens))
  (packages (arduino-mode) (meson-mode) (php-mode) (evil-escape :disable t) (form-feed) (hungry-delete) (company-quickhelp) (company-jedi) (reformatter))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 5e7d684 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Janfel** [comment]
It seems the issue is not fixed. Also there is no indication that a function is actually being added to `doom-switch-buffer-hook`. I have already run `doom clean`.

**Comment by hlissner** [comment]
> Also there is no indication that a function is actually being added to doom-switch-buffer-hook

That's to be expected. `:after-call` adds a transient hook/advice to hooks/functions passed to it. Meaning they run once, then delete themselves.

Instead, check `SPC h v undo-fu-mode` to see if it has been activated.

**Comment by Janfel** [comment]
> Instead, check `SPC h v undo-fu-mode` to see if it has been activated.

The variable is not defined until I manually call `undo-fu-mode` or `after-find-file` is called.

**Comment by Janfel** [comment]
It seems this issue only occurs when I open a new buffer with `SPC b N`. When I switch to an existing buffer or open a `helpful` buffer, the package loads normally.

**Comment by hlissner** [comment]
`doom-switch-buffer-hook` was too late, so I switched it to `pre-command-hook` in 5c49354, which should resolve this issue. Let me know if that isn't the case and I'll reopen this.
