### ISSUE TITLE
flyspell-lazy not working

### ISSUE THREAD

**Issue by 1337ever** [hlissner/doom-emacs#3282]
Forgive me because I'm new to emacs so I'm not entirely sure if this is doom's fault or my own.

**What did you expect to happen?**
I've been trying to reduce input latency and I found flyspell-lazy, which is included in the doom spell module. After enabling the spell module, I expected spellchecking to be done lazily about every 3 seconds, as appears to be the default.

**What actually happened?**
Spellchecking was done immediately after every input, as if flyspell-lazy wasn't even enabled. I did SPC-h-v flyspell-lazy-mode and found that it was set to nil. I also found that the variable `flyspell-lazy-last-text` remained blank no matter what. After browsing the source for the spell module, I found that flyspell-lazy is loaded after flyspell, and flyspell-lazy-mode is never called. However, the examples on the readme for flyspell-lazy show flyspell-lazy being loaded and flyspell-lazy-mode being run *before* flyspell proper. After messing around with different combinations of enabling and disabling flyspell and flyspell-lazy, i found that flyspell-lazy does appear to need to be loaded and run before flyspell. this leads me to believe that flyspell-lazy in the doom spell module isn't doing anything, which seems to contradict the message in the commit that added it, which stated that it would hopefully speed things up.

Apologies if I've misunderstood anything. If any more information is needed I will provide it.

**Comment by hlissner** [comment]
I'm considering replacing flyspell-mode with spell-fu. You may want to try it yourself, as it is a fair bit faster. For the time being, however, I've enabled flyspell-lazy-mode in 46c1f7a, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by 1337ever** [comment]
It seems like this still isn't working, because flyspell-lazy-mode still runs _after_ flyspell-mode. The example from the flyspell-lazy repo shows fly-spell-lazy-mode being run first.

**Comment by hlissner** [comment]
The way it is set up now, `flyspell-lazy-mode` is loaded before the first invocation of `flyspell-mode`. e.g.

```elisp
(add-hook! 'flyspell-mode-hook (message "flyspell init"))
(add-hook! 'flyspell-lazy-mode-hook (message "flyspell-lazy init"))
```

Will yield 'flyspell-lazy init` long before `flyspell init`.

flyspell-lazy appears to be working as expected in vanilla Doom.
