### ISSUE TITLE
Java seems to be missing from /modules/tools/debugger/config.el

### ISSUE THREAD

**Issue by nipuna-perera** [hlissner/doom-emacs#3695]
**What did you expect to happen?**
dap-java to work

**What actually happened?**
when I run dap-debug it asks if dap-java is enabled

**Additional details:**
java is missing from this config

https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/debugger/config.el

<details><pre>
I get the message

Have you loaded 'java' specific dap package?
</pre></details>

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS")
  (build . "Mar 05, 2020")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-gnutls")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 00a8f750e 2020-08-05 03:32:21 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/var/folders/d7/d8rs7cm10zsb65q00_d9qv51mxn334/T/fnm-shell-1051100/bin" "/var/folders/d7/d8rs7cm10zsb65q00_d9qv51mxn334/T/fnm-shell-8307381/bin" "~/.dotfiles/bin" "/usr/local/sbin" "/usr/local/opt/grep/libexec/gnubin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "$HOME/go/bin" "~/go/bin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +fuzzy +icons +prescient +childframe) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) treemacs vc-gutter vi-tilde-fringe window-select workspaces minimap :editor (evil +everywhere) file-templates fold format snippets :emacs (dired +icons) electric (ibuffer +icons) vc :term eshell :checkers syntax :tools (debugger +lsp) (docker +lsp) editorconfig (eval +overlay) lookup (lsp +peek) macos magit pdf rgb upload :lang csharp data emacs-lisp (go +lsp) (java +lsp) javascript markdown (org +dragndrop +journal +roam +pandoc +pomodoro +present) (python +lsp) sh (web +lsp) :app (rss +org) :config (default +bindings +snippets +evil-commands +smartparens))
  (packages (groovy-mode) (k8s-mode) (groovy-imports) (org-super-agenda) (prettier-js) (deadgrep) (markdown-changelog))
  (unpin "n/a")
  (elpa "s" "pythonic" "org-fancy-priorities" "f" "elfeed" "dash" "company-anaconda" "company" "anaconda-mode")))
</pre></details>

**Comment by hlissner** [comment]
As of d9fd738 this issue should be resolved. `dap-java` was moved to `lsp-java`, so we're loading that instead of `dap-java`. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by nipuna-perera** [comment]
@hlissner I don't think it's fixed yet. I see the update and I upgraded my emacs. I still can't get java to debug. dap-debug fails with the following message

`Have you loaded the 'java' specific dap package?`

And running SPC m t t gives the following

`Symbol's function definition is void: dap-java-run-test-method`

I also get this error in my private config.el

```elisp
(dap-register-debug-template "localhost:5005"
                             (list :type "java"
                                   :request "attach"
                                   :hostName "localhost"
                                   :port 5005))```

`Symbol's function definition is void: dap-register-debug-template`

I don't think dap for java is loaded properly.
