### ISSUE TITLE
`doom/window-enlargen` will restore window configure from other workspace

### ISSUE THREAD

**Issue by ezchi** [hlissner/doom-emacs#3747]
I have multiple workspaces and expect the `doom/window-enlargen` only restore the window configure in the same workspace. 

But it will restore the window configure from other workspace if last enlargen command is called in different workspace. 

I think each workspace should have its own stored window configuration.

**Comment by hlissner** [comment]
As of 702fb6e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ezchi** [comment]
First, thank for the quick fix for this. 

I have tried it. It is not mixed the workspace now. But I still have issue, here is the example:

1. In workspace `1`,  let's call the window configure as `window config 1`, do enlarge `SPC w o`
2. Switch to workspace `2`, ` SPC w o`
4. jump back to workspace `1`, the `SPC w o` does nothing, I expect it should restore it back to `window config 1`

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
(add-to-list 'window-persistent-parameters '(doom--maximize-last-wconf . t))
(add-to-list 'window-persistent-parameters '(doom--enlargen-last-wconf . t))
```

**Comment by ezchi** [comment]
Sorry to say it doesn't. Still same behaviour
