### ISSUE TITLE
Running LSP mode for a new type of language server disables flycheck for buffers running other language servers.

### ISSUE THREAD

**Issue by JordanAnthonyKing** [hlissner/doom-emacs#3767]
**What did you expect to happen?**

Switching between buffers should work as normal, all LSP and Flycheck features should be unaffected by which modes and language servers are being used on a per-buffer basis.

**What actually happened?**

I am currently working on an angular project. I use LSP for html, ts and (s)css files. If I switch from an html to a ts file for instance flycheck will show the 'no checker' icon in the modeline. Inputting some bad code will not be highlighted by flycheck. All other LSP features seem to still work, I can navigate to a symbol's definition for instance. Running M-x LSP or performing an LSP related command will bring flycheck back. LSP shows no sign of there being an issue. the lsp-log and individual language server logs show no errors either.

I've looked on the github issues for LSP but see nothing relating to this behaviour.

**Additional details:**
- Using default config for LSP/+LSP and Syntax

**Steps to reproduce:**
1. Open a file and activate LSP mode with appropriate language server installed.
2. Open another file and activate LSP-mode with an appropriate language server installed but different to the previous.
3. Switch between the two files, Flycheck will become disabled

**System information:**
<details><pre>
```
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Jul 20, 2020
        buildopts  (--with-json --with-threads)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> personal b94338e9d 2020-08-15 22:40:16 +0100
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/dotnet/ /mnt/c/Program Files (x86)/GnuPG/bin /mnt/c/Program Files/lf /mnt/c/Program Files/rg /mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/ /mnt/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn/ /mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ /mnt/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/ /mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/ /mnt/c/Program Files/Microsoft SQL Server/150/DTS/Binn/ /mnt/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin /mnt/c/Program Files/Git/cmd /mnt/c/Program Files/Docker/Docker/resources/bin /mnt/c/ProgramData/DockerDesktop/version-bin /mnt/c/Program Files/nodejs/ /mnt/c/ProgramData/chocolatey/bin /mnt/c/Users/jordan.cross/AppData/Local/Microsoft/WindowsApps /mnt/c/Users/jordan.cross/.dotnet/tools /mnt/c/Users/jordan.cross/AppData/Roaming/npm /snap/bin ~/dotnet /usr/local/libexec/emacs/27.0.91/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) treemacs vc-gutter window-select workspaces zen :editor (evil +everywhere) file-templates fold format snippets word-wrap :emacs dired electric undo vc :term term :checkers (syntax +childframe) :tools docker editorconfig (eval +overlay) lookup lsp magit :lang (csharp +lsp) emacs-lisp javascript markdown org sh web :config (default +bindings +smartparens))
        packages   ((ng2-mode) (yascroll))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this behavior. Could you try updating to cf2663ab7; I've since bumped many of Doom's packages, including lsp-mode. Hopefully this was fixed upstream.

**Comment by JordanAnthonyKing** [comment]
@hlissner I am still encountering this behaviour post-update. Do you have any advice to help debug this?

**Comment by hlissner** [comment]
Here are two things to try:

1. If you disable `yascroll` does the issue go away?
2. Can you try to reproduce the issue in [vanilla doom+](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by JordanAnthonyKing** [comment]
I am closing this bug as I have verified it occurs in vanilla emacs. I have raised an upstream issue: https://github.com/emacs-lsp/lsp-mode/issues/2117
