### ISSUE TITLE
evil-next-line or evil-next-visual-line

### ISSUE THREAD

**Issue by xarthurx** [hlissner/doom-emacs#401]
The moving bahivour at present for `"j"` is assigned to `evil-next-line`.
Does it make sense to assign it to `evil-next-visual-line` (which is now assigned to `g j`.

For programming, the switch should not make much difference as most of lines are not long.
But for text editing, it feels the `evil-next-visual-line` is more convenient and assign it to `j` would make things easier.

Just a suggestion.

**Comment by hlissner** [comment]
This was actually a bug, because `evil-respect-visual-line-mode` wasn't set early enough. It is now fixed, and thus `j` and `k` should be remapped to the visual line functions when visual-line-mode is active.

**Comment by adrianstaniec** [comment]
I am not sure, but have the impression that this bug is back.

**Comment by hlissner** [comment]
@adrianparvino Since https://github.com/hlissner/doom-emacs/commit/c733a6aa27a61763b65a4b868d0851fc5a361e47 and due to #2447, `evil-respect-visual-line-mode` is now set to `nil`.

To change it, add this to `~/.doom.d/init.el`:

```elisp
(setq evil-respect-visual-line-mode t)
```

**Comment by schloes** [comment]
I added `(setq evil-respect-visual-line-mode t)` to my configuration, but using "j" and "k" still skips the entire line. I can confirm with `helpful-variable` that `evil-respect-visual-line-mode` is non-nil, but the behavior is not working anyway. If I use regular `next-line` and `previous-line` it does work correctly. Any ideas?

**Comment by hlissner** [comment]
@schloes Did you add it to `~/.doom.d/init.el` (not `~/.doom.d/config.el`), as suggested? If you did, it's likely an issue with your config, because this setting works for me in vanilla Doom.

**Comment by exp2ipi** [comment]
@hlissner just to clarify: it looks like it is not possible to turn on next-visual-line behavior by using `(setq evil-respect-visual-line-mode t)` for some buffer, correct?

This becomes quite problematic when using org-mode; it is often useful to operate in visual line mode (e.g. if you are intending to paste the text somewhere), however gj/gk in org-mode are rebound to org navigation :(
