### ISSUE TITLE
Background of PNG in org-mode LaTeX preview is that of the non-solaire bg color

### ISSUE THREAD

**Issue by pkazmier** [hlissner/doom-emacs#4023]
**What did you expect to happen?**
I expect that the PNG generated for a LaTeX preview in org-mode should have the same background as the org-mode buffer so that it blends in with the rest of the buffer. I expect to see the following:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/747855/95028130-ada91380-0663-11eb-880e-e66980d652fd.png">

**What actually happened?**
The background of the PNG generated preview is that of the non-solaire-mode color as shown in the following:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/747855/95028125-9e29ca80-0663-11eb-99d5-97b66b70bb82.png">

**Additional details:**
If one reloads the current theme `SPC h t`, and then clicks on a preview twice (to force it to render again), the background of the PNG _will_ match the buffer's solaire-mode background.

Sample org file:
<details><pre>
#+TITLE: Test
#+STARTUP: latexpreview

* Solaire and Org Latex

The background of the following LaTeX preview does not match that of the theme.

$$ a = \frac{a + b}{\sqrt{x}} + \frac{b^2}{2\pi} $$

$$ y^2 + 10 $$
</pre></details>

**Steps to reproduce:**
1. Save the file included above to your filesystem.
2. Start emacs.
3. Open org file (assumes you have LaTeX installed, you don't need the doom latex module)

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/bin ~/go/bin ~/.emacs.d/bin ~/.dotfiles/bin /usr/local/bin ~/.cache/zsh4humans/bin ~/.cache/zsh4humans/junegunn/fzf/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/Cellar/emacs-plus@27/27.0.91/libexec/emacs/27.0.91/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.0.91
        build      Aug 08, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.0.91/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.0.91 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 0769b47c 2020-09-19 14:43:53 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo (ligatures +pragmata-pro) modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +pretty) (python +lsp) sh yaml :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ox-twbs))
        unpin      (doom-themes)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 018a95c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by chuxubank** [comment]
Sadly, this fix does not solve the problem.
I'm using `doom-dracula-theme` and the init value of `org-format-latex-options :background` is `#1E2029`
After `M-x doom/reload-theme` the value of `org-format-latex-options :background` is `#282a36`
These two values came from the [doom-dracula-theme.el](https://github.com/hlissner/emacs-doom-themes/blob/d6ee47dc8ed2cf9e585f62243214af03ba5b1687/themes/doom-dracula-theme.el#L42) file which all represent the background color.

I have no idea why the background color changed when I reload the theme, since they both picked from `+org-refresh-latex-background-h`

**Comment by hlissner** [comment]
Give 6a30a11 a try.

**Comment by pkazmier** [comment]
The problem still persists for me after doing a `doom upgrade`. This time, however, the workaround of using `SPC h t` to load the current theme again does not fix the issue. 

<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/bin ~/go/bin ~/.emacs.d/bin ~/.dotfiles/bin /usr/local/bin ~/.cache/zsh4humans/bin ~/.cache/zsh4humans/junegunn/fzf/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/Cellar/emacs-plus@27/27.0.91/libexec/emacs/27.0.91/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.0.91
        build      Aug 08, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.0.91/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.0.91 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 5b2b660e 2020-10-04 23:25:53 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo (ligatures +pragmata-pro) modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +pretty) (python +lsp) sh yaml :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ox-twbs))
        unpin      (doom-themes)
        elpa       (n/a)
```
</details>

**Comment by chuxubank** [comment]
@pkazmier Be sure to upgrade all packages and remove the latex cache
`rm -f ~/.emacs.d/.local/cache/org-latex/*`

In my cases, it works, and background color won't change when reloading theme after this fix.

**Comment by pkazmier** [comment]
I've deleted the cache file you suggest. I've run a `doom purge`, `doom clean`, `doom upgrade`. The problem still happens for the first of the two LaTeX blocks in my example. See image below:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/747855/95117003-7abb5a00-070d-11eb-9dc4-5543c5b98f5f.png">

**Comment by hlissner** [comment]
@pkazmier I can't repro that. Have you tinkered with `org-format-latex-options`? Are you absolutely sure there are no image files in `~/.emacs.d/.local/cache/org-latex/`?

**Comment by pkazmier** [comment]
@hlissner I have not tinkered with any LaTeX options. I removed the cache directory entirely and confirmed no files exist. Then I start a fresh emacs and open the sample org file provided, and I'm presented with the screenshot above.

A few additional observations if it helps:

- After the org file is opened, I can add new LaTeX fragments and they will be rendered correctly.
- If I disable `#+STARTUP: latexpreview`, after opening the document, if I use `org-latex-preview` all of the fragments are rendered correctly.
- If I add more than 2 blocks in the sample org file, it's always the first block that is not rendered correctly.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/747855/95135511-207cc200-072a-11eb-8550-c43b0e670b67.png">

Is there anything else I can provide to assist in the debugging? Would you like me to do a barebones Doom install? Do I just same my `.doom.d` dir and then install fresh? I don't think I do anything esoteric as I'm a basic user.

**Comment by hlissner** [comment]
Ah, seems that the problem is that org is generating the first preview too early in the org-mode startup process (before org-mode-hook is triggered and solaire-mode is activated). Since they are async, the second preview (and onwards) are started late enough that they are produced with the correct background.

There is no real solution to this problem, except to either 

1. Forcibly enable solaire-mode early in the org-mode startup process:

```elisp
(defadvice! solaire-mode-on-org-mode (orig-fn &rest args)
  :before #'org-latex-preview
  (turn-on-solaire-mode))
```

2. Or get the org devs to move [all this initialization work](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L4896-L4901) into `org-mode-hook` hooks or something.

I'll explore other solutions later. I'll keep this open for the time being.

**Comment by pkazmier** [comment]
Thanks for the workaround. Works great!

**Comment by hlissner** [comment]
As of 81f325f this should finally be resolved. Let me know if that isn't the case.

**Comment by pkazmier** [comment]
Confirmed. The issue has been resolved. Thank you for your help.

**Comment by WhatDothLife** [comment]
Strangely, this does not work for me:
![fragment](https://user-images.githubusercontent.com/33008303/100541914-5aa8a280-3247-11eb-8157-d6c707580ae9.png)

Haven't tweaked any preview variables or any related stuff.

**Comment by WhatDothLife** [comment]
Adding this to my config.el solved the issue:
```
(after! org
  ;; fix color handling in org-preview-latex-fragment
  (let ((dvipng--plist (alist-get 'dvipng org-preview-latex-process-alist)))
    (plist-put dvipng--plist :use-xcolor t)
    (plist-put dvipng--plist :image-converter '("dvipng -D %D -T tight -o %O %f"))))
```
