### ISSUE TITLE
Org-capture - ""Capture abort: Args out of range: 0, 1"

### ISSUE THREAD

**Issue by brianmcgillion** [hlissner/doom-emacs#4087]
**What did you expect to happen?**

Org-capture to capture the data.

**What actually happened?**
```
Debugger entered--Lisp error: (error "Capture abort: Args out of range: 0, 1")
  signal(error ("Capture abort: Args out of range: 0, 1"))
  error("Capture abort: %s" "Args out of range: 0, 1")
  org-capture(nil)
  #<subr funcall-interactively>(org-capture nil)
  apply(#<subr funcall-interactively> (org-capture nil))
  funcall-interactively(org-capture nil)
  #<subr call-interactively>(org-capture nil nil)
  apply(#<subr call-interactively> (org-capture nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> org-capture nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (org-capture nil nil))
  call-interactively(org-capture nil nil)
  command-execute(org-capture)
```

**Steps to reproduce:**
1. using emacs bindings (C-c n n to invoke org-capture menu)
2. select an option such as "t"
3. Backtrace

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64")
  (path "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.emacs.d/bin" "/snap/bin" "/var/lib/snapd/snap/bin" "/usr/lib/emacs/27.1/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 19, 2020")
  (buildopts . "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> bibtex 542834056 2020-10-13 11:02:56 +0400")
  (elc-files . 175)
  (modules :completion (company +childframe) (helm +fuzzy) :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter (window-select +numbers) workspaces zen :editor file-templates fold (format +onsave) snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term eshell term :checkers (syntax +childframe) (spell +everywhere) grammar :tools biblio (debugger +lsp) docker editorconfig (eval +overlay) (lookup +dictionary +offline +wordnet +docsets) (lsp +peek) magit make pass pdf :lang (cc +lsp) data emacs-lisp (go +lsp) latex markdown (org +dragndrop +pandoc +pretty +present +gnuplot +roam +noter) (python +lsp +pyenv) (sh +lsp) :app (rss +org) :config literate (default +bindings +smartparens))
  (packages (elfeed-goodies) (org-chef) (company-tabnine) (super-save) (crux) (imenu-anywhere) (atomic-chrome))
  (unpin org-roam helm)
  (elpa "n/a")))

</pre></details>

**Comment by CliveK** [comment]
Having the same issue!!

**Comment by meslier** [comment]
Same issue. Some curiosities:

1. The capture fails with that error message on all non-org mode related buffers. Such as Dashboard (the el plugin), scratch buffer etc. 
2. It fails in the same way for Doom's capture templates as well as custom capture templates. 
3. Reinstalling doom did not help. Clearing all custom settings (cleaning up packages.el, config.el etc.) does not help. 
4. An identical configuration on the desktop works just fine! 

Captures work fine with emacs -q. 

Debugger: 

> Debugger entered--Lisp error: (error "Capture abort: Args out of range: 1, 8")
>   signal(error ("Capture abort: Args out of range: 1, 8"))
>   error("Capture abort: %s" "Args out of range: 1, 8")
>   org-capture(nil)
>   funcall-interactively(org-capture nil)
>   call-interactively(org-capture record nil)
>   command-execute(org-capture record)
>   counsel-M-x-action("org-capture")
>   ivy-call()
>   ivy-read("M-x " ("toggle-debug-on-error" "org-capture" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" "ediff" "edirs" "hanoi" "imenu" ...) :predicate #f(compiled-function (x) #<bytecode 0x1590fc3a8591>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
>   counsel-M-x()
>   funcall-interactively(counsel-M-x)
>   call-interactively(counsel-M-x nil nil)
>   command-execute(counsel-M-x)
> 
> 
>

**Comment by brianmcgillion** [comment]
@AloisJanicek Thank you for the suggestion and work around. I can confirm that adding the new package source works for both the org-capture and org-protocol issues that I was seeing.

**Comment by hlissner** [comment]
As of 8d2a430 I've pinned it to `6c75b002172b26b5592a3076ef0bd3e9a37e73ce`, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by flyingns** [comment]
The issue of falling back to commit `6c75b00` is not resolved.
