### ISSUE TITLE
Auto-save "on" by default, or warning and better documentation about how to activate it

### ISSUE THREAD

**Issue by d4h0** [hlissner/doom-emacs#4096]
Hi,

This is kind of a combination of a bug report (IMO. Alternatively, a feature request), and a request for help.

It would be great if auto-save was activated by default. Or at the very least, users should be made very aware that auto-save is disabled, and how to activate it (for example, via a wizzard during the installation).

Two months ago I lost notes worth at least a week. Sure, it was not very smart, to not save the files for so long – but all of my editors that I have used during the last 10 to 15 years have auto-save activated by default (and don't freeze if the window size changes).

After this loss, I researched how to activate auto-save in Doom Emacs to activate it – and then I lost data again!

(Btw., if you are wondering, why I didn't open an issue earlier – just let's say, I had to wait this long, to be able to write a constructive message. Even now, I try to suppress my memory of the comment that is above the code that deactivates the auto-save feature in Doom Emacs, to be completely honest. In the meantime, I basically saved all files every time I write something... 😅).

So first of all, I'd like to ask for a change of the auto-save default settings for new users. It seems pretty insane, to deactivate this feature by default.

I can't follow the reasoning of the comment mentioned above. It talks about having potentially sensitive data spread around the file system.

This makes no sense to me, because most Doom users, most likely, mostly use plain-text files. So these files are anyway available from the file system in plain text.

If someone uses Doom for sensitive data and doesn't want these sensitive data spread around the file system, then these users should deactivate auto-save.

Or do I miss something?

I still can't believe that auto-save is deactivated by default – so if there is some way to restore crashed sessions that I missed, I'd be very interested in hearing about it! 😉

Otherwise, it would be fantastic if someone would tell me how to activate auto-save.

My failed attempt is:

```
(setq auto-save-default t
      create-lockfiles t
      make-backup-files t)
```

**System information**

<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/var/lib/flatpak/exports/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.emacs.d/bin/" "~/.cargo/bin/" "~/.emacs.d/bin/" "~/.cargo/bin/" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop a776664eb 2020-10-14 01:40:11 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp markdown (org +dragndrop +present) (rust +lsp) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))</pre></details>

**Comment by hlissner** [comment]
Those three lines are all you need, but perhaps you've misunderstood how they work. They make copies of your files in `~/.emacs.d/.local/cache/{autosave,backup}`. You can restore them with `M-x` and `recover-file`, `recover-session`, or `recover-this-file`.

This does not "automatically save the buffer" as if `C-x C-s` (`save-buffer`) was called for you, but if you activate `auto-save-visited-mode`, it would.

> This makes no sense to me, because most Doom users, most likely, mostly use plain-text files. So these files are anyway available from the file system in plain text.

Many users work with encrypted text files, or view sensitive plain-text files (like system logs) that `auto-save` writes to world-readable files. For example, system logs that may be readable only to your user group are now suddenly world-readable elsewhere.

> It seems pretty insane, to deactivate this feature by default.

Two more reasons why it's disabled by default (besides security):

1. There are many approaches to auto-saving buffers, and none of them stand out as more "correct" than the other. Users may have prefer...
   + `auto-save-default` over `auto-save-mode`.
   + `auto-save-visited-mode` over `auto-save-mode`.
   + `magit-wip-mode` over any of the above.
   + [focus-autosave-mode.el](https://github.com/Vifon/focus-autosave-mode.el/tree/2e0844fabb6f0dc9e0f31928e4785febf38b9e35)
   + or [super-save](https://github.com/bbatsov/super-save).
   + or use `(add-hook! 'focus-out-hook (save-some-buffers t))` to save whenever you unfocus Emacs.
   + or use `(run-with-idle-timer 3 t #'save-some-buffers t)` to save after any 3s of idle time.
   + Or simply have the discipline to save or commit their stuff frequently.
2. There's more to "saving a buffer" than writing bytes to a file. This can trigger linters, formatters, inotify handlers/file watchers, transparent recompression, tramp calls -- a litany of things that could change the state and contents of the buffer without you realizing. Formatters are especially problematic, because they can't tell apart legitimate files and the auto-save file.

> If someone uses Doom for sensitive data and doesn't want these sensitive data spread around the file system, then these users should deactivate auto-save.

Or if you don't mind its shortcomings, these users can activate auto-save.

> I'd like to ask for a change of the auto-save default settings for new users

I already had plans to re-enable auto-saving, but I haven't assessed all my options yet. Maybe, with some luck, I can mitigate its shortcomings. If not, then I won't be changing the default. I'll let you know once I've figured it out.

**Comment by d4h0** [comment]
Thanks for the quick response, @hlissner!

> but perhaps you've misunderstood how it works.

No this is exactly what I was expecting.

> After a crash, they can be restored with M-x and recover-file, recover-session, or recover-this-file.

That is exactly what I tried several times. When I tried to recover the session, it says `No files can be recovered from this file'. The session was greyed out, and these sessions actually still seem to exist. But there are no corresponding files (the displayed size is 0).

It is a bit embracing to admit, but a few seconds ago I tried again, and now it seems to work. After the second data loss, I tested the recovery feature several times (the last time, two weeks ago or so), and for some reason, nothing was saved. Really odd...

Now when I kill emacs with an unsaved file and press `M-x and recover-file` after a restart, I see the unsaved file. When I click on it, it opens with the unsaved content, and I can see it in the file system (all of which was previously not the case).

But I still can't recover it.

The [manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/After-a-Crash.html) says "Move point to the [session] you choose, and type C-c C-c" – but when I do that (I press "ctrl" and then two times "c" while the cursor is over the file name), the message "Args out of range" is displayed.

Am I missing anything?

> Many users work with encrypted text files, or view sensitive plain-text files (like system logs) that auto-save writes to world-readable files.

Alright. I still think it is very bad UX to disable auto-save by default :)

As far as I know, all slightly advanced text editors – including emacs – have an auto-save feature, which is activated by default. So the current situation is not something a new user would expect.

The worst thing isn't even that auto-save is deactivated by default: It is that this is not communicated to the user in any way (as far as I can see).

I'm pretty sure that I have read all of the available documentation when I started to use Doom Emacs, and I don't remember anything about a deactivated auto-save feature. I only found out about it, after I scanned the source code (which took me some time).

And besides that: I'm sure it would be very easy with emacs to deactivate auto-save for specific files (for example, for files outside the home directory, or for encrypted files with certain file extensions).

I actually used vanilla emacs and org-mode for a few months 10 years or so ago. I used an encrypted file for a diary, and the tutorial I used to set-up my diary showed how to disable auto-save for ".gpg" files.

So if someone wants this – which would certainly make sense in some circumstances – then it's very easy to archive. On the other hand, there are most likely a lot of users who don't realize that the auto-save feature is deactivated.

> Two more reasons why it's disabled by default (besides security):

Ah, come on that are no reasons to disable auto-save by default.

Re. 1: Any auto-save feature is better than none.

Re. 2: It would make more sense to properly configure these tools. Besides, the default auto-save folder seems to be `~/.emacs.d/.local/cache/autosave/`. Why would any of the mentioned tools work on files in that directory? And why should auto-save be deactivated for all users just because some people are not able to configure their tools properly?

> Or if you don't mind its shortcomings, these users can activate auto-save.

That is true. But a user first has to find out that auto-save is disabled (see above).

> I already had plans to re-enable auto-saving, but I haven't assessed all my options yet. Maybe, with some luck, I can mitigate its shortcomings. If not, then I won't be changing the default. I'll let you know once I've figured it out.

That sounds great!

The most important thing for me would be, to let users know when auto-save is disabled for any file. Maybe there could be a dialog when Doom is started for the first time?

You could show a message that explains the advantages and disadvantages of auto-save, and then let the user decide – for example by offering several options to select.

I think "completely off", "off for critical files", and "completely on" would be good options.

Ideally – because the consequences can be pretty dire – these options would not be easy to select (by pressing enter). Either a number would have to be pressed, or (my preference) the user would be required to enter one or more words that indicate the choice.

Anyway, losing my data certainly wasn't a pleasurable experience, but I'm still a happy Doom user and I'm very grateful for your hard work! It's insane how much time you seem to invest in this project :)

**Comment by d4h0** [comment]
Ah! I just restarted emacs and opened the file that I couldn't recover in my test above. There was a message on the bottom that mentioned that there is a saved recovery file and that I can press "M-x recover-this-file" – which worked!

But I'm 100% sure that I never saw this before (and I tried many times to recover files). As I wrote above: very odd.

However, I'm still interested in learning how I recover a full session with "M-x recover-session" + "C-c C-c".

**Comment by hlissner** [comment]
As of 24cc098 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by d4h0** [comment]
Awesome!

However, `restore-session` still doesn't work. I still get `args out of range: "#", 1, -1` when I try to restore a session by moving the cursor over the file and pressing `ctrl-c ctrl-c`.

Any idea what the problem could be?

```
      ;; Don't auto-disable auto-save after deleting big chunks. Kind of
      ;; defaults the purpose of a fallback in case of crashes.
```

Small typo here, I think ("defaults")

**Comment by hlissner** [comment]
> However, restore-session still doesn't work. I still get args out of range: "#", 1, -1 when I try to restore a session by moving the cursor over the file and pressing ctrl-c ctrl-c.

I can't reproduce this. Could you [generate a backtrace from it?](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error)

**Comment by d4h0** [comment]
Sure. Here it is:

```
Debugger entered--Lisp error: (args-out-of-range "#" 1 -1)
  substring("#" 1 -1)
  recover-session-finish()
  #<subr funcall-interactively>(recover-session-finish)
  apply(#<subr funcall-interactively> recover-session-finish)
  funcall-interactively(recover-session-finish)
  #<subr call-interactively>(recover-session-finish nil nil)
  apply(#<subr call-interactively> (recover-session-finish nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> recover-session-finish nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (recover-session-finish nil nil))
  call-interactively(recover-session-finish nil nil)
  command-execute(recover-session-finish)
```

**Comment by hlissner** [comment]
It'd be best to delete what you already have in `~/.emacs.d/.local/cache/autosave/*` (make sure you get hidden files too). If the source is to be believed:

```

**Comment by d4h0** [comment]
Okay, I have deleted everything. But it's still not working:

```
Debugger entered--Lisp error: (args-out-of-range "" 1 -1)
  substring("" 1 -1)
  recover-session-finish()
  #<subr funcall-interactively>(recover-session-finish)
  apply(#<subr funcall-interactively> recover-session-finish)
  funcall-interactively(recover-session-finish)
  #<subr call-interactively>(recover-session-finish nil nil)
  apply(#<subr call-interactively> (recover-session-finish nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> recover-session-finish nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (recover-session-finish nil nil))
  call-interactively(recover-session-finish nil nil)
  command-execute(recover-session-finish)
```

There isn't anything left, of what I have added to my config.el for auto-save.
