### ISSUE TITLE
File mode specification error when eshell is enabled

### ISSUE THREAD

**Issue by CrimsonKoba** [hlissner/doom-emacs#4176]
```
Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  define-key(nil "\4" +eshell/quit-or-delete-char)
  general--define-key-dispatch(nil eshell-mode-map ("\4" +eshell/quit-or-delete-char (:def +eshell/quit-or-delete-char) "\23" +eshell/search-history (:def +eshell/search-history) "\5" end-of-line (:def end-of-line) "\3s" +eshell/split-below (:def +eshell/split-below) "\3v" +eshell/split-right (:def +eshell/split-right) "\3x" +eshell/kill-and-close (:def +eshell/kill-and-close) [remap split-window-below] +eshell/split-below (:def +eshell/split-below) [remap split-window-right] +eshell/split-right (:def +eshell/split-right) [remap doom/backward-to-bol-or-indent] eshell-bol (:def eshell-bol) [remap doom/backward-kill-to-bol-and-indent] eshell-kill-input (:def eshell-kill-input) [remap evil-delete-back-to-indentation] eshell-kill-input (:def eshell-kill-input) [remap evil-window-split] +eshell/split-below (:def +eshell/split-below) [remap evil-window-vsplit] +eshell/split-right (:def +eshell/split-right)) (:wk-match-keys t :wk-match-binding t :wk-full-keys t :keymaps (eshell-mode-map) :states (nil) :keymaps (eshell-mode-map)))
  general--define-key(nil eshell-mode-map ("\4" +eshell/quit-or-delete-char "\23" +eshell/search-history "\5" end-of-line "\3s" +eshell/split-below "\3v" +eshell/split-right "\3x" +eshell/kill-and-close [remap split-window-below] +eshell/split-below [remap split-window-right] +eshell/split-right [remap doom/backward-to-bol-or-indent] eshell-bol [remap doom/backward-kill-to-bol-and-indent] eshell-kill-input [remap evil-delete-back-to-indentation] eshell-kill-input [remap evil-window-split] +eshell/split-below [remap evil-window-vsplit] +eshell/split-right) nil nil (:wk-match-keys t :wk-match-binding t :wk-full-keys t :keymaps (eshell-mode-map) :states (nil) :keymaps (eshell-mode-map)))
  eval((general--define-key 'nil 'eshell-mode-map '("\4" +eshell/quit-or-delete-char "\23" +eshell/search-history "\5" end-of-line "\3s" +eshell/split-below "\3v" +eshell/split-right "\3x" +eshell/kill-and-close [remap split-window-below] +eshell/split-below [remap split-window-right] +eshell/split-right [remap doom/backward-to-bol-or-indent] eshell-bol [remap doom/backward-kill-to-bol-and-indent] eshell-kill-input [remap evil-delete-back-to-indentation] eshell-kill-input [remap evil-window-split] +eshell/split-below [remap evil-window-vsplit] +eshell/split-right) 'nil 'nil '(:wk-match-keys t :wk-match-binding t :wk-full-keys t :keymaps (eshell-mode-map) :states (nil) :keymaps (eshell-mode-map))))
  general--delay((or (boundp 'eshell-mode-map) (and (memq 'eshell-mode-map '(local global)) (if 'nil (and (boundp 'evil-state-properties) (assq 'nil evil-state-properties)) t))) (general--define-key 'nil 'eshell-mode-map '("\4" +eshell/quit-or-delete-char "\23" +eshell/search-history "\5" end-of-line "\3s" +eshell/split-below "\3v" +eshell/split-right "\3x" +eshell/kill-and-close [remap split-window-below] +eshell/split-below [remap split-window-right] +eshell/split-right [remap doom/backward-to-bol-or-indent] eshell-bol [remap doom/backward-kill-to-bol-and-indent] eshell-kill-input [remap evil-delete-back-to-indentation] eshell-kill-input [remap evil-window-split] +eshell/split-below [remap evil-window-vsplit] +eshell/split-right) 'nil 'nil '(:wk-match-keys t :wk-match-binding t :wk-full-keys t :keymaps (eshell-mode-map) :states (nil) :keymaps (eshell-mode-map))) after-load-functions t nil "general-define-key-in-eshell-mode-map294")
  general-define-key(:keymaps (eshell-mode-map) "C-d" +eshell/quit-or-delete-char "C-s" +eshell/search-history "C-e" end-of-line "C-c s" +eshell/split-below "C-c v" +eshell/split-right "C-c x" +eshell/kill-and-close [remap split-window-below] +eshell/split-below [remap split-window-right] +eshell/split-right [remap doom/backward-to-bol-or-indent] eshell-bol [remap doom/backward-kill-to-bol-and-indent] eshell-kill-input [remap evil-delete-back-to-indentation] eshell-kill-input [remap evil-window-split] +eshell/split-below [remap evil-window-vsplit] +eshell/split-right)
  (progn (general-define-key :keymaps '(eshell-mode-map) "C-d" #'+eshell/quit-or-delete-char "C-s" #'+eshell/search-history "C-e" #'end-of-line "C-c s" #'+eshell/split-below "C-c v" #'+eshell/split-right "C-c x" #'+eshell/kill-and-close [remap split-window-below] #'+eshell/split-below [remap split-window-right] #'+eshell/split-right [remap doom/backward-to-bol-or-indent] #'eshell-bol [remap doom/backward-kill-to-bol-and-indent] #'eshell-kill-input [remap evil-delete-back-to-indentation] #'eshell-kill-input [remap evil-window-split] #'+eshell/split-below [remap evil-window-vsplit] #'+eshell/split-right) (general-define-key :states 'insert :keymaps '(eshell-mode-map) "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input "C-d" #'+eshell/quit-or-delete-char "C-c h" #'evil-window-left "C-c j" #'evil-window-down "C-c k" #'evil-window-up "C-c l" #'evil-window-right) (general-define-key :states 'normal :keymaps '(eshell-mode-map) "RET" #'+eshell/goto-end-of-prompt [return] #'+eshell/goto-end-of-prompt "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input))
  (progn (progn (general-define-key :keymaps '(eshell-mode-map) "C-d" #'+eshell/quit-or-delete-char "C-s" #'+eshell/search-history "C-e" #'end-of-line "C-c s" #'+eshell/split-below "C-c v" #'+eshell/split-right "C-c x" #'+eshell/kill-and-close [remap split-window-below] #'+eshell/split-below [remap split-window-right] #'+eshell/split-right [remap doom/backward-to-bol-or-indent] #'eshell-bol [remap doom/backward-kill-to-bol-and-indent] #'eshell-kill-input [remap evil-delete-back-to-indentation] #'eshell-kill-input [remap evil-window-split] #'+eshell/split-below [remap evil-window-vsplit] #'+eshell/split-right) (general-define-key :states 'insert :keymaps '(eshell-mode-map) "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input "C-d" #'+eshell/quit-or-delete-char "C-c h" #'evil-window-left "C-c j" #'evil-window-down "C-c k" #'evil-window-up "C-c l" #'evil-window-right) (general-define-key :states 'normal :keymaps '(eshell-mode-map) "RET" #'+eshell/goto-end-of-prompt [return] #'+eshell/goto-end-of-prompt "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input)) (general-define-key :states '(normal visual motion emacs insert) :major-modes t :prefix doom-localleader-key :non-normal-prefix doom-localleader-alt-key :keymaps '(eshell-mode-map) "b" #'eshell-insert-buffer-name "e" #'eshell-insert-envvar "s" #'+eshell/search-history))
  (progn (setq eshell-banner-message '(format "%s %s\n" (propertize (format " %s " (string-trim (buffer-name))) 'face 'mode-line-highlight) (propertize (current-time-string) 'face 'font-lock-keyword-face)) eshell-scroll-to-bottom-on-input 'all eshell-scroll-to-bottom-on-output 'all eshell-buffer-shorthand t eshell-kill-processes-on-exit t eshell-hist-ignoredups t eshell-input-filter #'(lambda (input) (not (string-match-p "\\`\\s-+" input))) eshell-prompt-regexp "^.* λ " eshell-prompt-function #'+eshell-default-prompt-fn eshell-glob-case-insensitive t eshell-error-if-no-glob t) (add-hook 'eshell-mode-hook #'doom-mark-buffer-as-real-h) (add-hook 'eshell-mode-hook #'+eshell-init-h) (add-hook 'eshell-exit-hook #'+eshell-cleanup-h) (add-hook 'eshell-mode-hook #'smartparens-mode) (if t (progn (add-hook 'persp-activated-functions #'+eshell-switch-workspace-fn) (add-hook 'persp-before-switch-functions #'+eshell-save-workspace-fn))) (progn (defalias '+eshell-remove-fringes-h #'(lambda nil (set-window-fringes nil 0 0) (set-window-margins nil 1 nil))) (add-hook 'eshell-mode-hook #'+eshell-remove-fringes-h nil nil)) (progn (defalias '+eshell-enable-text-wrapping-h #'(lambda nil (visual-line-mode 1) (set-display-table-slot standard-display-table 0 32))) (add-hook 'eshell-mode-hook #'+eshell-enable-text-wrapping-h nil nil)) (add-hook 'eshell-mode-hook #'hide-mode-line-mode) (advice-add #'eshell-write-aliases-list :override #'ignore) (progn (if (featurep 'em-term) (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let ((result ...)) (setq eshell-visual-commands (if ... eshell-visual-commands ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (with-no-warnings eshell-visual-commands)) (eval-after-load 'em-term #'(lambda nil (let (...) (while --dolist-tail-- ...) (with-no-warnings eshell-visual-commands)))))) (progn (defalias '+eshell-init-aliases-h #'(lambda nil (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases)))) (add-hook 'eshell-alias-load-hook #'+eshell-init-aliases-h nil nil)) (progn (progn (general-define-key :keymaps '(eshell-mode-map) "C-d" #'+eshell/quit-or-delete-char "C-s" #'+eshell/search-history "C-e" #'end-of-line "C-c s" #'+eshell/split-below "C-c v" #'+eshell/split-right "C-c x" #'+eshell/kill-and-close [remap split-window-below] #'+eshell/split-below [remap split-window-right] #'+eshell/split-right [remap doom/backward-to-bol-or-indent] #'eshell-bol [remap doom/backward-kill-to-bol-and-indent] #'eshell-kill-input [remap evil-delete-back-to-indentation] #'eshell-kill-input [remap evil-window-split] #'+eshell/split-below [remap evil-window-vsplit] #'+eshell/split-right) (general-define-key :states 'insert :keymaps '(eshell-mode-map) "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input "C-d" #'+eshell/quit-or-delete-char "C-c h" #'evil-window-left "C-c j" #'evil-window-down "C-c k" #'evil-window-up "C-c l" #'evil-window-right) (general-define-key :states 'normal :keymaps '(eshell-mode-map) "RET" #'+eshell/goto-end-of-prompt [return] #'+eshell/goto-end-of-prompt "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input)) (general-define-key :states '(normal visual motion emacs insert) :major-modes t :prefix doom-localleader-key :non-normal-prefix doom-localleader-alt-key :keymaps '(eshell-mode-map) "b" #'eshell-insert-buffer-name "e" #'eshell-insert-envvar "s" #'+eshell/search-history)) (progn (defalias '+eshell-fix-keymap-h #'(lambda nil "Undo buffer-local `eshell-mode-map', so global key..." (kill-local-variable 'eshell-mode-map) (use-local-map eshell-mode-map))) (add-hook 'eshell-mode-hook #'+eshell-fix-keymap-h nil nil)))
  (closure (t) nil (progn (setq eshell-banner-message '(format "%s %s\n" (propertize (format " %s " (string-trim ...)) 'face 'mode-line-highlight) (propertize (current-time-string) 'face 'font-lock-keyword-face)) eshell-scroll-to-bottom-on-input 'all eshell-scroll-to-bottom-on-output 'all eshell-buffer-shorthand t eshell-kill-processes-on-exit t eshell-hist-ignoredups t eshell-input-filter #'(lambda (input) (not (string-match-p "\\`\\s-+" input))) eshell-prompt-regexp "^.* λ " eshell-prompt-function #'+eshell-default-prompt-fn eshell-glob-case-insensitive t eshell-error-if-no-glob t) (add-hook 'eshell-mode-hook #'doom-mark-buffer-as-real-h) (add-hook 'eshell-mode-hook #'+eshell-init-h) (add-hook 'eshell-exit-hook #'+eshell-cleanup-h) (add-hook 'eshell-mode-hook #'smartparens-mode) (if t (progn (add-hook 'persp-activated-functions #'+eshell-switch-workspace-fn) (add-hook 'persp-before-switch-functions #'+eshell-save-workspace-fn))) (progn (defalias '+eshell-remove-fringes-h #'(lambda nil (set-window-fringes nil 0 0) (set-window-margins nil 1 nil))) (add-hook 'eshell-mode-hook #'+eshell-remove-fringes-h nil nil)) (progn (defalias '+eshell-enable-text-wrapping-h #'(lambda nil (visual-line-mode 1) (set-display-table-slot standard-display-table 0 32))) (add-hook 'eshell-mode-hook #'+eshell-enable-text-wrapping-h nil nil)) (add-hook 'eshell-mode-hook #'hide-mode-line-mode) (advice-add #'eshell-write-aliases-list :override #'ignore) (progn (if (featurep 'em-term) (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let (...) (setq eshell-visual-commands ...) (setq --dolist-tail-- ...))) (with-no-warnings eshell-visual-commands)) (eval-after-load 'em-term #'(lambda nil (let ... ... ...))))) (progn (defalias '+eshell-init-aliases-h #'(lambda nil (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases)))) (add-hook 'eshell-alias-load-hook #'+eshell-init-aliases-h nil nil)) (progn (progn (general-define-key :keymaps '(eshell-mode-map) "C-d" #'+eshell/quit-or-delete-char "C-s" #'+eshell/search-history "C-e" #'end-of-line "C-c s" #'+eshell/split-below "C-c v" #'+eshell/split-right "C-c x" #'+eshell/kill-and-close [remap split-window-below] #'+eshell/split-below [remap split-window-right] #'+eshell/split-right [remap doom/backward-to-bol-or-indent] #'eshell-bol [remap doom/backward-kill-to-bol-and-indent] #'eshell-kill-input [remap evil-delete-back-to-indentation] #'eshell-kill-input [remap evil-window-split] #'+eshell/split-below [remap evil-window-vsplit] #'+eshell/split-right) (general-define-key :states 'insert :keymaps '(eshell-mode-map) "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input "C-d" #'+eshell/quit-or-delete-char "C-c h" #'evil-window-left "C-c j" #'evil-window-down "C-c k" #'evil-window-up "C-c l" #'evil-window-right) (general-define-key :states 'normal :keymaps '(eshell-mode-map) "RET" #'+eshell/goto-end-of-prompt [return] #'+eshell/goto-end-of-prompt "C-j" #'eshell-next-matching-input-from-input "C-k" #'eshell-previous-matching-input-from-input)) (general-define-key :states '(normal visual motion emacs insert) :major-modes t :prefix doom-localleader-key :non-normal-prefix doom-localleader-alt-key :keymaps '(eshell-mode-map) "b" #'eshell-insert-buffer-name "e" #'eshell-insert-envvar "s" #'+eshell/search-history)) (progn (defalias '+eshell-fix-keymap-h #'(lambda nil "Undo buffer-local `eshell-mode-map', so global key..." (kill-local-variable 'eshell-mode-map) (use-local-map eshell-mode-map))) (add-hook 'eshell-mode-hook #'+eshell-fix-keymap-h nil nil))))()
  eval-after-load-helper("/usr/share/emacs/27.1/lisp/eshell/eshell.elc")
  run-hook-with-args(eval-after-load-helper "/usr/share/emacs/27.1/lisp/eshell/eshell.elc")
  do-after-load-evaluation("/usr/share/emacs/27.1/lisp/eshell/eshell.elc")
  require(eshell)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310\311\312&\7\210\313\314\315\316\317DD\320\321\314\322\323\311\304&\11\210\313\324\315\316\325DD\326\321\327\322\323\311\304..." [require eshell json custom-declare-group pyvenv nil "Python Virtual Environment Interface." :prefix "pyvenv-" :group languages custom-declare-variable pyvenv-workon funcall function #f(compiled-function () #<bytecode 0x146ef29>) "The intended virtualenv in the virtualenvwrapper d..." :type :safe stringp pyvenv-activate #f(compiled-function () #<bytecode 0x146ef35>) "The intended virtualenv directory.\n\nThis is rarely..." directory pyvenv-tracking-ask-before-change #f(compiled-function () #<bytecode 0x146f729>) "Non-nil means pyvenv will ask before automatically..." boolean pyvenv-virtualenvwrapper-python #f(compiled-function () #<bytecode 0x146f735>) "The python process which has access to the virtual..." (file :must-match t) file-directory-p pyvenv-exec-shell #f(compiled-function () #<bytecode 0x7a88f5>) "The path to a POSIX compliant shell to use for run..." (file :must-match t) pyvenv-default-virtual-env-name #f(compiled-function () #<bytecode 0x2047021>) "Default directory to use when prompting for a virt..." string] 10)
  require(pyvenv nil nil)
  (progn (use-package-statistics-gather :init 'pyvenv nil) (if t (progn (add-hook 'pyvenv-post-activate-hooks #'+modeline-update-env-in-all-windows-h) (add-hook 'pyvenv-pre-deactivate-hooks #'+modeline-clear-env-in-all-windows-h))) (require 'pyvenv nil nil) (use-package-statistics-gather :config 'pyvenv nil) (add-hook 'python-mode-local-vars-hook #'pyvenv-track-virtualenv) (add-to-list 'global-mode-string '(pyvenv-virtual-env-name (" venv:" pyvenv-virtual-env-name " ")) 'append) t (use-package-statistics-gather :config 'pyvenv t) (use-package-statistics-gather :init 'pyvenv t))
```

**Comment by frankxzhang** [comment]
When I try to open a python file or activate python via pyvenv-activate command, I got similar problem. This happened after I updated doom emacs this morning.

**Comment by hlissner** [comment]
As of 1b44cf9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it.

-----

In the future please:

1. Do not ignore the issue template and *always* include a) steps to reproduce your issue and b) the output of `M-x doom/info`. It's lucky I didn't need it this time, but please don't count on luck.
2. Please take the time to properly format your post. You can click the ellipses on the top right of your post and click "edit" to do so:

   ![image](https://user-images.githubusercontent.com/510883/97531238-27de6680-198a-11eb-88b2-63a5a8c0a86f.png)

   Surround backtraces in code fences, otherwise they are impossible to read. For example:

   \`\`\`
   backtrace goes here
   \`\`\`

**Comment by oedon23** [comment]
I still have the "Wrong type argument: keymapp, nil" error when opening eshell.

**Comment by hlissner** [comment]
@oedon23 `M-x doom/info`

**Comment by oedon23** [comment]
![grafik](https://user-images.githubusercontent.com/72317378/97545754-b7583980-19cb-11eb-9623-286b24a7c9fd.png)

**Comment by hlissner** [comment]
57ef63d should finally fix this. Let me know if that isn't the case.

**Comment by oedon23** [comment]
@hlissner 
Yes, it is fixed. Thank you very much for the quick response and fix!
