### ISSUE TITLE
which-key not working when localleader is set to ","

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#4231]
**What did you expect to happen?**
`which-key` should show the available shortcuts when I press `,` (my localleader), like it happens when localleader is set to default (`SPC m`).

**What actually happened?**
I got the following error in the status bar after waiting for sometime: `Error running timer ‘which-key--update’: (wrong-type-argument listp evil-snipe-repeat-reverse)`.

**Additional details:**
- Include a link to your private config: https://github.com/thiagokokada/dotfiles/tree/master/doom-emacs/.config/doom. But I can reproduce this commenting my whole `config.el` and just setting a `(setq doom-localleader-key ",")`
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it):

  ```
  
  `t' Minor Mode Bindings Starting With ,:
  key             binding
  ---             -------

  Error running timer ‘which-key--update’: (wrong-type-argument listp evil-snipe-repeat-reverse)
  ```

**Steps to reproduce:**
1. Add `(setq doom-localleader-key ",")` to `config.el`
2. Open a file and press `,`, wait until the `which-key` timeout occurs

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.8.17 #1-NixOS SMP Thu Oct 29 09:08:31 UTC 2020 x86_64
        path       (/nix/store/1zlq72zgll2cfg19x5whfq751s2dvi5d-emacs-packages-deps/bin ~/.local/bin ~/.cargo/bin ~/.npm-packages/bin ~/Projects/RG350-buildroot/output/host/bin ~/Projects/buildroot/output/host/bin ~/.config/emacs/bin /nix/store/ygy19xf7gim44x0kvw2v37yjiabkhssg-kitty-0.18.3/bin /nix/store/96bz457g68lnbdzcr1dzrl6zcd7s0kbb-imagemagick-6.9.11-14/bin /nix/store/8cil6lql1lkq4lxlrk9d0yg0qk62sz82-xsel-unstable-2019-08-21/bin /nix/store/ncgqkpqj9gjaz6abxlwv15jpdn2nc818-ncurses-6.2-dev/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/yf8p9v8kmp3aby4i4qmf0smm369cyi9c-emacs-gcc-20201105.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.config/emacs/
        version    28.0.50
        build      nov 07, 2020
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-gcc-20201105.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER
        traits     (server-running)
DOOM    dir        ~/.dotfiles/doom-emacs/.config/doom/
        version    2.0.9
        build      HEAD -> develop 7205b727a 2020-11-06 21:16:04 -0500
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo (modeline +light) ophints (popup +defaults +all) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools docker (eval +overlay) lookup lsp magit :os tty :lang cc (clojure +lsp) data (dart +flutter +lsp) elixir emacs-lisp (go +lsp) hy json markdown nim nix org (python +lsp +poetry) (ruby +rails) rust scala sh yaml :config (default +bindings +smartparens))
        packages   ((adoc-mode) (evil-escape :disable t) (flycheck-clj-kondo :disable t) (graphql-mode) (lispyville) (lsp-ui :disable t) (sort-words) (uuidgen))
        unpin      (n/a)
        elpa       (vterm)
```

</details>

**Comment by thiagokokada** [comment]
Disabling `evil-snipe` works, but this still seems a bug since it used to work before (and I am not in the middle of a "snipe" during my tests).

**Comment by hlissner** [comment]
This is known incompatibility with `which-key` and Emacs 28, which was fixed upstream some time ago. I've bumped which-key in 92c9127 which should fix your issue. Let me know if that isn't the case and I'll reopen it. Thanks!

**Comment by thiagokokada** [comment]
@hlissner Still the same issue sadly.

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.8.17 #1-NixOS SMP Thu Oct 29 09:08:31 UTC 2020 x86_64
        path       (/nix/store/1zlq72zgll2cfg19x5whfq751s2dvi5d-emacs-packages-deps/bin ~/.local/bin ~/.cargo/bin ~/.npm-packages/bin ~/Projects/RG350-buildroot/output/host/bin ~/Projects/buildroot/output/host/bin ~/.config/emacs/bin /nix/store/ygy19xf7gim44x0kvw2v37yjiabkhssg-kitty-0.18.3/bin /nix/store/96bz457g68lnbdzcr1dzrl6zcd7s0kbb-imagemagick-6.9.11-14/bin /nix/store/8cil6lql1lkq4lxlrk9d0yg0qk62sz82-xsel-unstable-2019-08-21/bin /nix/store/ncgqkpqj9gjaz6abxlwv15jpdn2nc818-ncurses-6.2-dev/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/yf8p9v8kmp3aby4i4qmf0smm369cyi9c-emacs-gcc-20201105.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.config/emacs/
        version    28.0.50
        build      nov 07, 2020
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-gcc-20201105.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER
        traits     (server-running)
DOOM    dir        ~/.dotfiles/doom-emacs/.config/doom/
        version    2.0.9
        build      HEAD -> develop 92c9127b8 2020-11-07 00:20:07 -0500
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo (modeline +light) ophints (popup +defaults +all) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools docker (eval +overlay) lookup lsp magit :os tty :lang cc (clojure +lsp) data (dart +flutter +lsp) elixir emacs-lisp (go +lsp) hy json markdown nim nix org (python +lsp +poetry) (ruby +rails) rust scala sh yaml :config (default +bindings +smartparens))
        packages   ((adoc-mode) (evil-escape :disable t) (flycheck-clj-kondo :disable t) (graphql-mode) (lispyville) (lsp-ui :disable t) (sort-words) (uuidgen))
        unpin      (n/a)
        elpa       (vterm)
```
BTW, if Emacs 28 issues are not valid you can keep this close. I don't think this is a big bug anyway.
