### ISSUE TITLE
emacsclient not connecting to daemon on Windows 10

### ISSUE THREAD

**Issue by matzesc** [hlissner/doom-emacs#4384]
**What did you expect to happen?**
1. start emacs server from git-bash with
`/d/emacs/27.1/bin/emacs.exe --daemon`

2. start emacsclient with
`/d/emacs/27.1/bin/emacsclientw.exe --alternate-editor="D:\emacs\27.1\bin\runemacs.exe" -c`

3. open scratch buffer inside emacs, type `(daemonp)` and analyze expression to `t`

**What actually happened?**
1. start emacs server from git-bash with
`/d/emacs/27.1/bin/emacs.exe --daemon`

2. start emacsclient with
`/d/emacs/27.1/bin/emacsclientw.exe --alternate-editor="D:\emacs\27.1\bin\runemacs.exe" -c`

3. open scratch buffer inside emacs, type `(daemonp)` and analyze expression to `nil`

**Additional details:**

I already run `git bisect` to narrow this issue down to a certain commit
```
$ git bisect log
git bisect start
# bad: [9137cbaaa472025e119097d4cb35ef26034a587b] Bump :completion
git bisect bad 9137cbaaa472025e119097d4cb35ef26034a587b
# good: [110d70bdff12c61fb4bfebf8e9f6b3a18684076d] Merge pull request #4274 from EoinDoherty/racket-unicode
git bisect good 110d70bdff12c61fb4bfebf8e9f6b3a18684076d
# good: [2acce11a491cf5dbbe88b8fbd5e8145582be7eb7] Merge pull request #4332 from gagbo/fix/bepo-evil-magit-migration
git bisect good 2acce11a491cf5dbbe88b8fbd5e8145582be7eb7
# good: [7b11f67c7642b46a2ac67aebee2a5133a74c64ef] counsel-bookmark use filename only if available
git bisect good 7b11f67c7642b46a2ac67aebee2a5133a74c64ef
# bad: [d88e0795b68bd0a261872b2c1e80b7b567a862ae] Allow eldoc after doom/escape or evil state change
git bisect bad d88e0795b68bd0a261872b2c1e80b7b567a862ae
# bad: [2ddba1e7b8ea17966e84ff8bf0eba5a6099f5a70] Merge pull request #4350 from catap/broke-upgrade-loop
git bisect bad 2ddba1e7b8ea17966e84ff8bf0eba5a6099f5a70
# bad: [f5dacce7f57cfdf7907a27abf0538171af097cb7] Merge pull request #4349 from catap/macports
git bisect bad f5dacce7f57cfdf7907a27abf0538171af097cb7
# bad: [affd076d530f3b51212dbdec29ba706c696d5298] Minor refactors & reformatting
git bisect bad affd076d530f3b51212dbdec29ba706c696d5298
# bad: [c517be8e692c71ea31c448381336727a514b5045] Advise locate-user-emacs-file to use doom-etc-dir
git bisect bad c517be8e692c71ea31c448381336727a514b5045
# first bad commit: [c517be8e692c71ea31c448381336727a514b5045] Advise locate-user-emacs-file to use doom-etc-dir
```

It seems commit c517be8e692c71ea31c448381336727a514b5045 introduces this issue.

**System information:**
<details><pre>
```
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:\Program Files\Git\usr\bin\bash.exe
        uname      n/a
        path       (~/bin C:/Program Files/Git/mingw64/bin C:/Program Files/Git/usr/local/bin C:/Program Files/Git/usr/bin C:/Program Files/Git/usr/bin C:/Program Files/Git/mingw64/bin C:/Program Files/Git/usr/bin ~/bin C:/Python39/Scripts C:/Python39 C:/Program Files (x86)/Common Files/Oracle/Java/javapath C:/ProgramData/Oracle/Java/javapath C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/libnvvp C:/ProgramData/chocolatey/bin C:/Program Files (x86)/GtkSharp/2.12/bin C:/Program Files/Microsoft/Web Platform Installer C:/Program Files/dotnet C:/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn C:/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn C:/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/extras/CUPTI/libx64 C:/WINDOWS/system32 C:/WINDOWS C:/WINDOWS/System32/Wbem C:/WINDOWS/System32/WindowsPowerShell/v1.0 C:/WINDOWS/System32/OpenSSH C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR C:/Program Files/Java/jdk1.8.0_221/bin C:/Program Files/Microsoft SQL Server/130/Tools/Binn C:/Program Files/Microsoft VS Code/bin C:/Program Files/Java/jdk1.8.0_231/bin C:/Program Files/PuTTY C:/Program Files/LLVM/bin C:/Program Files/TortoiseGit/bin C:/Program Files/Git/cmd C:/Program Files/nodejs ~/AppData/Local/Microsoft/WindowsApps C:/Program Files/Microsoft VS Code/bin C:/tools/neovim/Neovim/bin C:/tools/Cmder ~/.dotnet/tools ~/AppData/Roaming/npm C:/Program Files/Git/usr/bin/vendor_perl C:/Program Files/Git/usr/bin/core_perl D:/emacs/27.1/bin/ d:/emacs/27.1/libexec/emacs/27.1/x86_64-w64-mingw32)
EMACS   dir        ~/.config/emacs/
        version    27.1
        build      Aug 21, 2020
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (batch server-running)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD, refs/bisect/bad c517be8e6 2020-12-01 13:53:10 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown (org +roam) python sh :config (default +bindings +smartparens))
        packages   ((sr-speedbar) (imenu-list))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
As of 4652511 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by matzesc** [comment]
Hi @hlissner , thanks for this awesome emacs distro. Sadly this change did not resolve the original problem.

I was checking the Emacs documentation about [TCP Emacs server](https://www.gnu.org/software/emacs/manual/html_node/emacs/TCP-Emacs-server.html) and this is the last paragraph:

> To tell emacsclient to connect to the server over TCP with a specific server file, use the `-f` or `--server-file` option, or set the `EMACS_SERVER_FILE` environment variable (see [emacsclient Options](https://www.gnu.org/software/emacs/manual/html_node/emacs/emacsclient-Options.html#emacsclient-Options)). If `server-auth-dir` is set to a non-standard value, or if `server-name` is set to an absolute file name, emacsclient needs an absolute file name to the server file, as the default `server-auth-dir` is hard-coded in emacsclient to be used as the directory for resolving relative filenames. 

In there it is mentioned that the emacsclient has the `server-auth-dir` path hard coded. So it seems the only other option is to use the command line options `-f` or `--server-file` or set the environment variable `EMACS_SERVER_FILE` to the new path of the server file.

I added the `-f` command line option to the alias for the emacsclient in my `.bashrc` like this:

```
# emacs path
export PATH=$PATH:/d/emacs/27.1/bin/
# emacs alias
alias emacsd='emacs --daemon'
alias emacs='emacsclientw -a runemacs -c -f ~/.config/emacs/.local/etc/server/server'
alias doom='~/.config/emacs/bin/doom'
```

which allowed me to connect to the daemon with the emacsclient again.
