### ISSUE TITLE
Comments in TSX files

### ISSUE THREAD

**Issue by t0ster** [hlissner/doom-emacs#4431]
Create .tsx file, try to comment portion of code that contains tags, result will be:
`// <SomeComponent />`

Expected result:
`{/* <SomeComponent /> */}`

https://github.com/hlissner/doom-emacs/blob/49f3bc193a4984f0b5a01a71ad91bb26f643c6d8/modules/lang/web/%2Bhtml.el#L68
For now I just changed `("javascript" "jsx")` to `("javascript")` here. This fixes the issue.

Best regards,
Roman

**Comment by hlissner** [comment]
Now try commenting out the non-tag portion of your JSX. Does it use the right delimiters?

**Comment by t0ster** [comment]
Just tried, it uses `//`. Looks fine.

**Comment by hlissner** [comment]
As of a4392b2 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by saevarb** [comment]
I don't think this is a good fix. I frequently (i.e. during debugging) comment and uncomment parts of code, and this requires me to comment out some code, uncomment all of it and then recomment parts of it again.

**Comment by afonsoduarte** [comment]
I'm still seeing this issue. Like OP, on a `.tsx` file, when I comment out some JSX, I get `// <Component/>` instead of `{/* <Component /> */}`
