### ISSUE TITLE
Default keybinding for org-clock is broken in 96d7e50f3e1a6b95889f34ae07601af9c8b14fd9

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#4457]
**What did you expect to happen?**
`C-c C-x C-i` runs `org-clock-in` per default org-mode keybinding: https://orgmode.org/manual/Clocking-commands.html

**What actually happened?**
`C-c C-x C-i` emits message: `C-c C-x <C-i> is undefined`

**Additional details:**
Broken in 96d7e50f3e1a6b95889f34ae07601af9c8b14fd9.

**Comment by hlissner** [comment]
I'm not aware of a good fix for this. `C-i` issues have been a thorn in my side since day one of using Emacs. For the time being, your best bet is to use one of the other keybinds Doom sets for you:

+ If you use evil: <kbd>SPC</kbd><kbd>m</kbd><kbd>c</kbd><kbd>i</kbd>
+ If you don't: <kbd>C-c</kbd><kbd>l</kbd><kbd>c</kbd><kbd>i</kbd>

Or to re-do the default keybind:

```elisp
;; add to ~/.doom.d/config.el
(map! "C-c C-x <C-i>" #'org-clock-in)
```

**Comment by hlissner** [comment]
Actually, see if this fixes the issue:

```elisp
;; add to ~/.doom.d/config.el
(define-key key-translation-map [?\C-i]
  (cmd! (if (let ((keys (this-single-command-raw-keys)))
              (and (not (cl-position 'tab    keys))
                   (not (cl-position 'kp-tab keys))
                   (this-single-command-keys)
                   (display-graphic-p)
                   (cl-loop with _ = (setf (aref keys (1- (length keys))) 'C-i)
                            for map
                            in (append (list (current-local-map))
                                       (mapcar #'cdr minor-mode-alist)
                                       (and (boundp 'evil-mode-map-alist)
                                            (mapcar #'cdr evil-mode-map-alist))
                                       (list (current-global-map)))
                            for lookup = (lookup-key map keys)
                            unless (or (null lookup) (numberp lookup))
                            return lookup)))
            [C-i] [?\C-i])))

(global-set-key [C-i] nil)
```

**Comment by hlissner** [comment]
As of a567834 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ineu** [comment]
It is fixed, thank you!

**Comment by Eising** [comment]
It did not fix it for me unfortunately, but a new error appears:

```
let: Wrong type argument: keymapp, ((evil-normal-state-local-minor-mode keymap) (evil-org-mode keymap "Auxiliary keymap for Normal state" (122 keymap (105 . org-toggle-inline-images) (82 . +org/open-all-folds) (114 . +org/show-next-fold-level) (79 . outline-show-subtree) (111 . +org/open-fold) (110 . org-tree-to-indirect-buffer) (77 . +org/close-all-folds) (109 . +org/hide-next-fold-level) ...) (103 keymap (81 . org-fill-paragraph)) (13 . +org/dwim-at-point) (return . +org/dwim-at-point) (33554442 . org-shiftdown) (33554443 . org-shiftup) (33554444 . org-shiftright) ...) (evil-snipe-local-mode keymap "Auxiliary keymap for Normal state" (83 . evil-snipe-S) (115 . evil-snipe-s)) (t keymap (keymap "Auxiliary keymap for Normal state" (32 keymap (109 keymap (115 keymap (112 keymap (117 . org-priority-up) (112 . org-priority) (100 . org-priority-down)) (83 . org-sort) (78 . widen) (65 . org-archive-subtree) (115 . org-sparse-tree) (114 . org-refile) (110 . org-narrow-to-subtree) (108 . org-demote-subtree) ...) (114 keymap (114 . org-refile) (118 . +org/refile-to-visible) (79 . +org/refile-to-other-buffer) (111 . +org/refile-to-other-window) (102 . +org/refile-to-file) (108 . +org/refile-to-last-location) (99 . +org/refile-to-running-clock) (46 . +org/refile-to-current-file)) (80 keymap (115 . org-publish-sitemap) (80 . org-publish-current-project) (112 . org-publish) (102 . org-publish-current-file) (97 . org-publish-all)) (108 keymap (116 . org-toggle-link-display) (83 . org-insert-last-stored-link) (115 . org-store-link) (76 . org-insert-all-links) (108 . org-insert-link) (105 . org-id-store-link) (100 . +org/remove-link) (99 . org-cliplink)) (103 keymap (120 . org-capture-goto-last-stored) (118 . +org/goto-visible) (114 . org-refile-goto-last-stored) (105 . org-id-goto) (67 closure (t) (&rest _) (interactive) (org-clock-goto (quote select))) (99 . org-clock-goto) (71 . counsel-org-goto-all) (103 . counsel-org-goto)) (100 keymap (84 . org-time-stamp-inactive) (116 . org-time-stamp) (115 . org-schedule) (100 . org-deadline)) (99 keymap (45 . org-clock-timestamps-down) (61 . org-clock-timestamps-up) (116 . org-evaluate-time-range) (82 . org-clock-report) (114 . org-resolve-clocks) (111 . org-clock-out) (73 . org-clock-in-last) (105 . org-clock-in) ...) (98 keymap (116 keymap (111 . org-table-toggle-coordinate-overlays) (102 . org-table-toggle-formula-debugger)) (105 keymap (72 . org-table-hline-and-move) (114 . org-table-insert-row) (104 . org-table-insert-hline) (99 . org-table-insert-column)) (100 keymap (114 . org-table-kill-row) (99 . org-table-delete-column)) (82 . org-table-recalculate-buffer-tables) (114 . org-table-recalculate) (115 . org-table-sort-lines) (104 . org-table-field-info) (102 . org-table-edit-formulas) ...) ...))) keymap "Auxiliary keymap for Normal state" (M-return . outline-insert-heading) (27 keymap (108 . outline-demote) (107 . outline-move-subtree-up) (106 . outline-move-subtree-down) (104 . outline-promote)) (103 keymap (106 . outline-forward-same-level) (107 . outline-backward-same-level)) (10 . outline-forward-same-level) (11 . outline-backward-same-level) ...) (evil-normal-state-minor-mode keymap (C-tab . aya-create) (8388656 . +workspace/switch-to-final) (8388665 . +workspace/switch-to-8) (8388664 . +workspace/switch-to-7) (8388663 . +workspace/switch-to-6) (8388662 . +workspace/switch-to-5) (8388661 . +workspace/switch-to-4) (8388660 . +workspace/switch-to-3) ...) (t keymap "Auxiliary keymap for Motion state" (32 . doom/leader) (intercept-state . motion)) (evil-motion-state-local-minor-mode keymap) (evil-org-mode keymap "Auxiliary keymap for Motion state" (91 keymap (99 . org-babel-previous-src-block) (108 . org-previous-link) (104 . org-backward-heading-same-level)) (93 keymap (99 . org-babel-next-src-block) (108 . org-next-link) (104 . org-forward-heading-same-level)) (103 keymap (115 keymap (104 . +org/goto-visible)) (72 . evil-org-top) (106 . org-forward-element) (107 . org-backward-element) (108 . org-down-element) (104 . org-up-element)) (123 . org-backward-paragraph) (125 . org-forward-paragraph) (40 . evil-org-backward-sentence) (41 . evil-org-forward-sentence) ...) (evil-snipe-override-local-mode keymap "Auxiliary keymap for Motion state" (44 . evil-snipe-repeat-reverse) (59 . evil-snipe-repeat) (84 . evil-snipe-T) (116 . evil-snipe-t) (70 . evil-snipe-F) (102 . evil-snipe-f)) (evil-snipe-local-mode keymap "Auxiliary keymap for Motion state" (83 . evil-snipe-S) (115 . evil-snipe-s)) ...)"
```

**Comment by hlissner** [comment]
@Eising Could you post [the full backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error)?
