### ISSUE TITLE
M-x ess-rdired leads to args-out-of-range error

### ISSUE THREAD

**Issue by WouterSpekkink** [hlissner/doom-emacs#4466]
**What did you expect to happen?**
I expected the M-x ess-rdired command to create a buffer that shows the objects in the R global environment. I expected the buffer to actually show the objects I created.

**What actually happened?**
The R Dired buffer gets created, but doesn't show any of the objects I created. I get an error report. See the screenshot for the backtrace. I compared the .el file in the sreenshot with the original on the ESS github, and I don't see any issues there. I am really at a loss about what could be the issue. This is a fresh install of Doom emacs. 

Links to my config files:
https://github.com/WouterSpekkink/dotfiles/blob/master/.doom.d./config.el
https://github.com/WouterSpekkink/dotfiles/blob/master/.doom.d./init.el
https://github.com/WouterSpekkink/dotfiles/blob/master/.doom.d./packages.el

I didn't change any of the default keybindings.

This is the output of M-x view-echo-area-message (not very informative I'm afraid):
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [2 times]
Garbage collecting...done (0.092s)
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [14 times]
DOOM [ui/doom-dashboard] Changed dashboard’s PWD to /home/wouter/.emacs.d/.local/straight/repos/ESS/
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225)
Garbage collecting...done (0.067s)
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [2 times]
Garbage collecting...done (0.090s)
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [4 times]
Garbage collecting...done (0.062s)
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [52 times]
Quit
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225)
Garbage collecting...done (0.066s)
Error running timer ‘ess-rdired-refresh’: (args-out-of-range #<buffer  *ess-rdired-output*> 1 225) [57 times]

![screenshot](https://user-images.githubusercontent.com/6826078/102937392-52d8c880-44aa-11eb-990c-9bc2d4a77f8c.png)

**Steps to reproduce:**
1. Start R (M-x R)
2. Create some objects (e.g., x <- 5)
3. Attempt to run ess-rdired (M-x ess-rdired)
4. Despair.

**System information:**
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64
        path       (~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil semi-light nil nil 15 nil nil nil nil>
        theme      doom-dracula
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 0c925641 2020-12-15 04:14:40 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline neotree ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang cc emacs-lisp ess json latex markdown org qt sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by OmarElAshkar** [comment]
@WouterSpekkink I have also faced this one. Any workarounds so far?

**Comment by WouterSpekkink** [comment]
Hi @OmarElAshkar! Nope, unfortunately not. I also haven't been able to test whether this is a doom emacs thing or an upstream thing. So far I have just been getting by with using the ls() command to list objects in the environment.

**Comment by nessdoor** [comment]
> I also haven't been able to test whether this is a doom emacs thing or an upstream thing.

Used to be in upstream, too, but the issue seems resolved now. Maybe you just have to wait a little bit more for the fix to come down (hopefully).

**Comment by davidbudzynski** [comment]
I'm facing the same issue. Tried unpinning the package but that didn't solve the problem.
