### ISSUE TITLE
Goto beginning-of-line only affects the first among multiple cursors

### ISSUE THREAD

**Issue by ronisbr** [hlissner/doom-emacs#4614]
**What did you expect to happen?**

When you have multiple cursors and press `0`, I would expect that all go to the beginning of their lines. Just like when pressing `$` they all go to the end of their lines.

**What actually happened?**

Only the last cursor goes to the beginning of the line.

**Steps to reproduce:**

1. Type CTRL+v.
2. Type down two or more times.
3. Type `gzz` to create a cursor in every line.
4. Type `0`.

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin20.2.0
        shell      /bin/zsh
        uname      Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
        path       (/Library/TeX/texbin ~/bin /usr/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin20.2.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Jan 20, 2021
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil MesloLGMDZ Nerd Font nil nil nil nil nil 13 nil nil nil nil>
        theme      doom-gruvbox
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 2ad1eab 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion company ivy :ui (popup +defaults) doom doom-dashboard hl-todo modeline neotree ophints unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers (spell +aspell +everywhere +flyspell) grammar syntax :tools (eval +overlay) lookup magit :lang cc emacs-lisp julia latex markdown org python qt sh :config (default +bindings +smartparens))
        packages   ((doct) (org-journal))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by ymarco** [comment]
It works for me in org-mode and c-mode, i.e all cursors go to the beginning. What major mode did you try in?
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.8-2-default #1 SMP Thu Nov 12 07:43:32 UTC 2020 (ea93937) x86_64
        path       (~/.nix-profile/bin ~/.guix-profile/bin /tools/bin ~/.scripts/rofi ~/.scripts /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin /gnu/store/jrs4vn2by2g5fkbl3b3c1190vk6dr419-emacs-pgtk-native-comp-28.0.50-124.990d252/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.config/emacs/
        version    28.0.50
        build      Feb 05, 2021
        buildopts  CONFIG_SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash --prefix=/gnu/store/jrs4vn2by2g5fkbl3b3c1190vk6dr419-emacs-pgtk-native-comp-28.0.50-124.990d252 --enable-fast-install --with-pgtk --with-xwidgets --with-nativecomp --with-modules --with-cairo --disable-build-details
        features   JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS JSON PDUMPER
        traits     (gui server-running)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil nil nil nil 20 nil nil nil nil>
        theme      doom-spacegrey
        build      HEAD -> develop 0304023b5 2021-01-27 02:24:40 +0200
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard hl-todo (modeline +light) nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen hydra :editor (evil +everywhere) file-templates fold format lispy multiple-cursors snippets :emacs (dired +icons) ibuffer electric vc undo :term eshell term :tools (debugger +lsp) editorconfig eval lookup (lsp +peek) (magit +forge) rgb :checkers (syntax +childframe) :lang yaml json (cc +lsp) data emacs-lisp go haskell scheme (javascript +lsp) (latex +fold +latexmk) lua markdown nix (org +dragndrop) python rust (sh +lsp) web :email (mu4e +gmail) :app irc (rss +org) :config (default +bindings +smartparens))
        packages   ((exwm :pin 45ac28cc9cffe910c3b70979bc321a1a60e002ea) (nov :pin 3d32aac0f895c8605e254c8b7f246537816744f5) (webkit-katex-render :recipe (:local-repo packages/emacs-webkit-katex-render :files (*.el *.html))) (evil-escape :disable t) (sxhkd-mode :recipe (:local-repo packages/sxhkd-mode)) (hebrew-mode :recipe (:host github :repo yoavm448/hebrew-mode)) (evil-tex) (latex-auto-activating-snippets :recipe (:local-repo packages/latex-auto-activating-snippets)) (auto-activating-snippets :recipe (:local-repo packages/auto-activating-snippets)) (calibredb :recipe (:host github :repo chenyanming/calibredb.el) :pin a27b71b727ebf726ed0742d968717e0e89db9786) (pdf-tools :recipe (:host github :repo flatwhatson/pdf-tools :branch fix-macros)) (snapshot-timemachine :pin 99efcebab309b11ed512a8dc62555d3834df5efb) (inkscape :recipe (:local-repo packages/inkscape.el :files (*.el *.svg))) (xenops :pin 2a72cf519bda25ee8852672e14b6c265388bc74b) (lexic :recipe (:host github :repo tecosaur/lexic)) (explain-pause-mode :disable t) (guix :pin d246b2c443bbb9d49575b63bb78c14699c4448cf) (crdt :recipe (:repo https://code.librehq.com/qhong/crdt.el)) (tree-sitter) (tree-sitter-langs) (info-colors) (meson-mode))
        unpin      (doom-snippets)
        elpa       (n/a)

(I'm using flat's native-comp-pgtk build, and tecosaur's mu4e PR branch.)
</pre></details>

**Comment by ronisbr** [comment]
Interesting! I am seeing these problems in LaTeX.

**Comment by hlissner** [comment]
`evil-mc` operates on a whitelist. So commands are allowed to work across multiple cursors, they must be registered in `evil-mc-custom-known-commands`. That it works in many modes but not in latex buffers means that whatever is bound to `0` is not in that whitelist. So what is it bound to? See `SPC h k 0` or `C-h k 0`.

**Comment by ronisbr** [comment]
`SPC h k 0` in tex shows me this:

```
evil-digit-argument-or-evil-beginning-of-visual-line is an interactive
and compiled function defined in evil-integration.el.

Signature
(evil-digit-argument-or-evil-beginning-of-visual-line)

Key Bindings
This command is not in any keymaps.

References
evil-digit-argument-or-evil-beginning-of-visual-line is unused in evil-integration.el.

Find all references Find callees

Debugging
Enable edebug Enable tracing
Disassemble Forget

Source Code
;; Defined in ~/.emacs.d/.local/straight/repos/evil/evil-integration.el
;; visual-line-mode integration
(when evil-respect-visual-line-mode
  (evil-define-command evil-digit-argument-or-evil-beginning-of-visual-line ()
    :digit-argument-redirection evil-beginning-of-visual-line
    :keep-visual t
    :repeat nil
    (interactive)
    (cond
     (current-prefix-arg
      (setq this-command #'digit-argument)
      (call-interactively #'digit-argument))
     (t
      (setq this-command 'evil-beginning-of-visual-line)
      (call-interactively 'evil-beginning-of-visual-line))))

  (evil-define-minor-mode-key 'motion 'visual-line-mode
    "j" 'evil-next-visual-line
    "gj" 'evil-next-line
    "k" 'evil-previous-visual-line
    "gk" 'evil-previous-line
    "0" 'evil-digit-argument-or-evil-beginning-of-visual-line
    "g0" 'evil-beginning-of-line
    "$" 'evil-end-of-visual-line
    "g$" 'evil-end-of-line
    "V" 'evil-visual-screen-line))

Symbol Properties
event-symbol-element-mask
  (evil-digit-argument-or-evil-beginning-of-visual-line 0)
event-symbol-elements
  (evil-digit-argument-or-evil-beginning-of-visual-line)
modifier-cache
  ((0 . evil-digit-argument-or-evil-beginning-of-visual-line))
```

**Comment by hlissner** [comment]
Yep, that's not in `evil-mc-custom-known-commands`. Try this:

```elisp
;; add to ~/.doom.d/config.el
(after! evil-mc
  (add-to-list 'evil-mc-custom-known-commands
               '(evil-digit-argument-or-evil-beginning-of-line
                 (:default . evil-mc-execute-default-call)
                 (visual . evil-mc-execute-visual-call))))
```

**Comment by hlissner** [comment]
I've added it in 36a63d1, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ronisbr** [comment]
hi @hlissner !

Sorry for the delay. Unfortunately your commit did not fix my problem. What I needed to fix this was this code in `config.el`:

```
(after! evil-mc
  (add-to-list 'evil-mc-custom-known-commands
               '(evil-digit-argument-or-evil-beginning-of-visual-line
                 (:default . evil-mc-execute-default-call)
                 (visual . evil-mc-execute-visual-call))))
```

Notice that I add the function `evil-digit-argument-or-evil-beginning-of-visual-line` to the whitelist instead of the function `evil-digit-argument-or-evil-beginning-of-line`.

**Comment by hlissner** [comment]
Ah, my bad. Should be fixed in 7679c08

**Comment by ronisbr** [comment]
Yes! It is working perfectly now. Thanks @hlissner !! :)
