### ISSUE TITLE
Modeline highlight doesn't change when I change windows

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#4660]
**What did you expect to happen?**
Split window, change window (`C-x o`), and change the modeline highlight accordingly.

**What actually happened?**
Split window, change window (`C-x o`), and the modeline stays the same.
Then, if I `alt-TAB` to another window and `alt-TAB` back, it changes the modeline.

**Additional details:**
- I removed my personal config, and did a new install.
- I don't if #4607 is related, but might be.

Start:
![Screenshot from 2021-02-16 15-04-29](https://user-images.githubusercontent.com/3268882/108081291-b295bf00-7068-11eb-9381-6a131763cde0.png)
Change to right window:
![Screenshot from 2021-02-16 15-04-37](https://user-images.githubusercontent.com/3268882/108081288-b295bf00-7068-11eb-8ac9-37caaf2964b8.png)
`alt-tab`, `alt-tab`:![Screenshot from 2021-02-16 15-05-01](https://user-images.githubusercontent.com/3268882/108081285-b1fd2880-7068-11eb-9b76-c8c6fd5d9107.png)

Also, if I maximize, it changes again:
![Screenshot from 2021-02-16 15-05-20](https://user-images.githubusercontent.com/3268882/108081411-d8bb5f00-7068-11eb-92ae-0b197aea5a38.png)

**Steps to reproduce:**
See above.

**System information:**
<details><pre>
```
SYSTEM  info       (Ubuntu 20.04.2 LTS . Linux 5.8.0-43-generic x86_64)
        shell      /usr/bin/zsh
        path       (~/.zplug/bin ~/miniconda3/bin ~/miniconda3/condabin ~/.platformio/penv/bin /usr/local/cuda/bin ~/.krew/bin ~/.emacs.d/bin ~/.local/bin ~/local/bin ~/.cargo/bin ~/bin ~/go/bin /usr/local/go/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin /usr/lib/emacs/26.3/x86_64-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    (26.3 Mar 26, 2020)
        buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD 5e8a668 2021-02-14 21:14:07 -0500)
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil
 +everywhere) fold format multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :checkers syntax spell :tools docker (eval +overlay) lookup (lsp +peek) magit :lang (cc +lsp) data emacs-lisp (json +lsp) (javascript +lsp) (latex +latexmk) markdown (org +dragndrop +pandoc +present) (python +cython +conda +lsp +pyright) sh (web +lsp) (yaml +lsp) :config (default +bindings +smartparens))
        packages   ((platformio-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this issue. Check \*Messages\* (`C-h e` or `SPC h e` to open it) for warnings or errors.

This looks like an issue I've seen before with a faulty compositor (are you using compton or picom; disable them if you are)?

[Can you reproduce it in the sandbox? (With your private config disabled, or vanilla emacs)](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by vakker** [comment]
Thanks for the response.
There's nothing in the `*Messages*`.

I tried `Doom + modules - your private config   C-c C-p` -> the issue persists
but with `vanilla Doom (only Doom core)          C-c C-d` -> the issue seems to be not present. But also, the modeline is much more simple, so it's not apples to apples (see screenshots below).

I'm not using compton or picom, just vanilla Ubuntu 20.04.

Also, this started after I did a fresh install last week. If I swap back the previous `.emacs.d` directory, which is at:
```
commit b03fdabe4fa8a07a7bd74cd02d9413339a485253 (grafted, HEAD -> develop, origin/develop, origin/HEAD)
Author: Henrik Lissner <henrik@lissner.net>
Date:   Wed Jan 13 14:05:43 2021 -0500
```
then the issue does not persists.

![Screenshot from 2021-02-20 16-05-34](https://user-images.githubusercontent.com/3268882/108601639-79758b80-7395-11eb-8fb7-19eff91b8d54.png)
![Screenshot from 2021-02-20 16-05-31](https://user-images.githubusercontent.com/3268882/108601641-7a0e2200-7395-11eb-954d-178db0bf7e3a.png)

**Comment by ebrov** [comment]
I am having the same issue. Like @vakker, I'm running Ubuntu 20.04 without compton or picom and the issue tracked exactly like they described.

When running the sandbox and the issue only appears when running `C-c C-p` for "vanilla Doom+". Running "vanilla Doom" and "vanilla Emacs" through the sandbox does not have his issue. 

Seeing that "vanilla Doom+" loads the `doom!` section of the `.doom.d/init.el` file which contains the `modeline` package under the `ui` header, the problem is likely in the `modeline` package.

**Comment by hlissner** [comment]
Do you still seet his behavior if you use `:ui (modeline +light)` instead of `:ui modeline`?

**Comment by ebrov** [comment]
> Do you still seet his behavior if you use `:ui (modeline +light)` instead of `:ui modeline`?

No, using `:ui (modeline +light)` does not show this problem

**Comment by hlissner** [comment]
Can you produce this on the latest commit of Doom? Your `M-x doom/info` says you were using 5e8a668 (dated 2021-02-14) at the time, but `doom-modeline` has been bumped once or twice in that time. Perhaps it was addressed upstream in that time. I suspect it may be an upstream issue.

**Comment by ebrov** [comment]
I just updated to commit `6b173c5cc` (2021-03-06) an I'm still experiencing the same problem. `modeline` does not highlight the active window and `(modeline +light)` does not have this problem.

**Comment by ebrov** [comment]
I recently had to delete my local copy of doom emacs and cloning and reinstalling a clean version fixed the issue. I completely deleted the `.doom.d` and `.emacs.d` directories (backing up my `.emacs.d/init.el` of course). I had a few modules I had modified for personal preference (`lang/cc`,`emacs/undo`) but I had copied those files out to a backup directory then copied them back into `.emacs.d/modules` after the clone and reinstall.

I'm still not sure what caused this issue. Results from `git status` showed no change to anything in the `modeline` module, so beats me. Hopefully this helps somehow.
