### ISSUE TITLE
Cannot delete characters in org mode tables

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#472]
When triggering `+org|delete-backward-char`, an error is thrown out: `void variable n`.
There is indeed, in [this linked line](https://github.com/hlissner/doom-emacs/blob/e89ed0e9aed443ca8cc16e3c4a6166b734240137/modules/lang/org/autoload/org.el#L298) a mysterious looking variable.

https://github.com/hlissner/doom-emacs/blob/e89ed0e9aed443ca8cc16e3c4a6166b734240137/modules/lang/org/autoload/org.el#L298

**Comment by hlissner** [comment]
Thanks for letting me know! I've pushed a fix to develop.

**Comment by UndeadKernel** [comment]
This fix has brought in another problem: when deleting inside a table, the character after the cursor is deleted and then a space is added. Deleting inside an org table is still not working as expected.

**Comment by hlissner** [comment]
My bad. This should be fixed now, please try it again.
