### ISSUE TITLE
Go-to-reference broken in Golang with gopls after commit #430d628

### ISSUE THREAD

**Issue by mhersson** [hlissner/doom-emacs#4771]
After upgrading and applying commit #430d628 " tools/lsp: use xref backend as lookup handler"
The go-to-reference shortcuts (gD or SPC-c-D bound to +lookup/references) does not work with gopls. 

Reverting this commit  and adding the following two lines to the lsp module remedies the problem.
```
    :definition #'lsp-find-definition
    :references #'lsp-find-references
```

**What did you expect to happen?**
Menu pops up with all references to the function, once one is selected cursor is moved to point of reference.

**What actually happened?**
Doom freezes for a couple of seconds utilizing 100% cpu, then outputs "Go guru finished".

**Additional details:**
The solution to the problem might be in the go module

From modues/lang/go/config.el
```
   6 (after! go-mode
   7   (set-docsets! 'go-mode "Go")
   8   (set-repl-handler! 'go-mode #'gorepl-run)
   9   (set-lookup-handlers! 'go-mode
  10     :definition #'go-guru-definition
  11     :references #'go-guru-referrers
  12     :documentation #'godoc-at-point)
```

I tried commenting out lines 10 and 11, and that kind of fixed the issue, but for some reason it didn't work everywhere, but Doom didn't freeze up. I couldn't make out why it only worked some places in the code.

**EDIT**: Just found out that when it workes the lookup returnes multiple references. When only 1 reference is returned cursor/focus is not moved upon selection.

**EDIT 2**: The issue isn't only with the number of references which I claimed in the previous edit. It's with where there this single reference is. If the only reference is in another file. Then It does not work. It actually does find the reference and moves the cursor there in the file, but the buffers are not switched. If the single reference is in the same file it works. If there are multiple references it always works, same file or different file, no matter.

**Steps to reproduce:**
1. Brand new install of Doom Emacs - only change for default: enable lsp and (go +lsp) in init.el
2. Create a new go project or open exsting just make sure LSP is enabled. Can be tested with something as simple as
```
   1 package main
   2 
   3 import "fmt"
   4 
   5 func Hello() {
   6     fmt.Println("Greetings!")
   7 }
   8 
   9 func main() {
  10     Hello()                                                                                                                                        
  11 }
```

3. Move cursor to Hello on line 5 and press gD or SPC-c-D

**System information**
https://pastebin.com/MxWTUjeV

**Comment by markflarup** [comment]
I can verify this problem.

**System information**
```
  generated  Mar 10, 2021 16:01:44
     distro  MacOS 10.14.6 Darwin 18.7.0 x86_64
      emacs  27.1 ~/.emacs.d/
       doom  2.0.9 HEAD -> develop 4a08acd23 2021-03-09 16:22:25 -0500 ~/.doom.d/ -> ~/.doom.d/
      shell  /bin/zsh
   features  NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP
     traits  batch server-running envvar-file
    modules  :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell) :tools (debugger +lsp) (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (go +lsp) markdown org sh yaml :config (default +bindings +smartparens)
   packages  (evil-tutor) (evil-terminal-cursor-changer)
       elpa  n/a
```

**Comment by sebastiansturm** [comment]
not sure if this is related, but I recently noticed that `+lookup/references` no longer works for me if there's only one candidate to select (using the lsp backend, not sure if that matters). I'm not seeing increases in CPU usage, or freezes; Emacs just won't jump to the selected candidate. Guessing that this might be related to the `(cdr xrefs)` condition in `+lookup--xref-show`, I made `+lookup--xref-show` return `'deferred` whenever `xrefs` is non-nil. This seems to fix the issue at hand, but I don't know what other functionality I may have broken in the process.

**Comment by razzmatazz** [comment]
> not sure if this is related, but I recently noticed that `+lookup/references` no longer works for me if there's only one candidate to select (using the lsp backend, not sure if that matters). I'm not seeing increases in CPU usage, or freezes; Emacs just won't jump to the selected candidate. Guessing that this might be related to the `(cdr xrefs)` condition in `+lookup--xref-show`, I made `+lookup--xref-show` return `'deferred` whenever `xrefs` is non-nil. This seems to fix the issue at hand, but I don't know what other functionality I may have broken in the process.

Can confirm this for C# mode with lsp backend too.

**Comment by razzmatazz** [comment]
> not sure if this is related, but I recently noticed that `+lookup/references` no longer works for me if there's only one candidate to select (using the lsp backend, not sure if that matters). I'm not seeing increases in CPU usage, or freezes; Emacs just won't jump to the selected candidate. Guessing that this might be related to the `(cdr xrefs)` condition in `+lookup--xref-show`, I made `+lookup--xref-show` return `'deferred` whenever `xrefs` is non-nil. This seems to fix the issue at hand, but I don't know what other functionality I may have broken in the process.

@sebastiansturm can you paste your patch?

**Comment by sebastiansturm** [comment]
I simply have `+lookup--xref-show` return deferred even when `(cdr xrefs)` is nil:
```
(defun +lookup--xref-show (fn identifier &optional show-fn)
  (let ((xrefs (funcall fn
                        (xref-find-backend)
                        identifier)))
    (when xrefs
      (funcall (or show-fn #'xref--show-defs)
               (lambda () xrefs)
               nil)
      'deferred)))
```
But please keep in mind that this is not supposed to be a proper fix; I'm pretty sure the `(cdr xrefs)` is there for a reason, so most likely this patch will break something else

**Comment by hlissner** [comment]
Sorry for the tremendously late response. This should be fixed as of d4eb7ea. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by mhersson** [comment]
@hlissner 
d4eb7ea fixed part of the problem. It fixed the problem for golang where go-guru is invoked and crashes.

However it still does not follow references if the reference is in another file. 

From original post:
>EDIT 2: The issue isn't only with the number of references which I claimed in the previous edit. It's with where this single reference is. If the only reference is in another file. Then It does not work. It actually does find the reference and moves the cursor there in the file, but the buffers are not switched. If the single reference is in the same file it works. If there are multiple references it always works, same file or different file, no matter.

Now it does not seem to work if there are multiple references either. 
I've been using @sebastiansturm patch, but that has also stopped working for me now.

Please let me know if there is anything I can do to help out.

Thank you.

**Comment by thiagokokada** [comment]
> However it still does not follow references if the reference is in another file.

This second issue also affects other languages, i.e.: I can reproduce this on Clojure too.
