### ISSUE TITLE
Attempts to use native compilation on non-native compilation build on 28.0.50

### ISSUE THREAD

**Issue by kelvie** [hlissner/doom-emacs#4947]
**What did you expect to happen?**

An upgrade to properly build dependent packages.

**What actually happened?**
```
  > Installing packages...
    → Building company...
    x There was an unexpected error
      Message: error
      Data: (error . "Emacs was not compiled with native compiler support (--with-native-compilation)")
      Backtrace:
        (signal error ("Emacs was not compiled with native compiler support (--wit
        (error "Emacs was not compiled with native compiler support (--with-native
        (cond ((null (featurep 'nativecomp)) (error "Emacs was not compiled with n
        (comp-ensure-native-compiler)
        (native--compile-async "/home/user/.emacs.d/.local/straight/build-28.0.50/
        (let ((load (not (not load)))) (native--compile-async files recursively lo
        (native-compile-async "/home/user/.emacs.d/.local/straight/build-28.0.50/c
        (let ((inhibit-message t) (message-log-max nil)) (native-compile-async (st
        (progn (let ((inhibit-message t) (message-log-max nil)) (native-compile-as
        (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- '
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**Additional details:**
https://pastebin.com/LNC3vh9X

**Steps to reproduce:**
1. Install emacs-snapshot from https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa on ubuntu 20.04
2. Do a doom upgrade

**System information:**
https://pastebin.com/cDpPU8P2

The emacs version actually is:
Version: 20210428:104933-244499292e~ubuntu20.04.1
and comes from this PPA: https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa
```
generated    Apr 29, 2021 08:38:31
distro       Ubuntu 20.04.2 LTS Linux 5.10.25-linuxkit x86_64
emacs        28.0.50 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop, origin/develop, origin/HEAD 82eebdca1 2021-04-28 16:49:12 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/sh
features     ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB
traits       batch envvar-file
modules      :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets word-wrap :emacs dired electric undo vc :checkers syntax :tools docker (eval +overlay) lookup lsp magit pass pdf rgb taskrunner upload :lang cc (dart +flutter) emacs-lisp (go +lsp) (haskell +dante) json (java +meghanada +lsp) javascript kotlin latex lua markdown org python qt rust sh web yaml :config (default +bindings +smartparens)
packages     (protobuf-mode) (evil-snipe :disable t) (mixed-pitch) (graphviz-dot-mode)

```

**Comment by hlissner** [comment]
As of 43623d7 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kelvie** [comment]
Doesn't look like it fixed it:

https://pastebin.com/KtWh0vyx

I also did a clean first, do I perhaps need to delete some files and rebuild?

**Comment by kelvie** [comment]
I don't think I have the permissions to re-open this

**Comment by kelvie** [comment]
@hlissner ^ not sure if you wanted a ping

**Comment by hlissner** [comment]
Seems the issue is with [straight.el](https://github.com/raxod502/straight.el). The fix is already up on their end, so I'll bump it on ours soon.

**Comment by hlissner** [comment]
As of f60f576 this issue should be finally resolved (straight's been updated). Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by gjm** [comment]
@hlissner I'm still having issues...

I can `sync` but `upgrade` and `build` fail...

```
$ doom sync
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
    - Skipping native bytecode
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ✓ Generated .local/autoloads.28.0.50.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
```

```
$ doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
```

```
$ doom build
> (Re)building all packages...
  → Building auto-minor-mode...
  x There was an unexpected error
    Message: error
    Data: (error . "Emacs was not compiled with native compiler support (--with-native-compilation)")
    Backtrace:
      (signal error ("Emacs was not compiled with native compiler support (--wit
      (error "Emacs was not compiled with native compiler support (--with-native
      (cond ((null (featurep 'nativecomp)) (error "Emacs was not compiled with n
      (comp-ensure-native-compiler)
      (native--compile-async "/home/gjm/files/emacs/doom-emacs/.local/straight/b
      (let ((load (not (not load)))) (native--compile-async files recursively lo
      (native-compile-async "/home/gjm/files/emacs/doom-emacs/.local/straight/bu
      (let ((inhibit-message t) (message-log-max nil)) (native-compile-async (st
      (progn (let ((inhibit-message t) (message-log-max nil)) (native-compile-as
      (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- '
```

**Comment by erasmas** [comment]
I'm having exactly the same problem with `emacsGit` Nix package and latest Doom. 

```
> ./bin/doom sync
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - Checked out lsp-treemacs: 4cfb46d7fe69cc537a8a86389c5d8d9fd3fbfabe
    → Building lsp-treemacs...
    x There was an unexpected error
      Message: error
      Data: (error . "Emacs was not compiled with native compiler support (--with-native-compilation)")
      Backtrace:
        (signal error ("Emacs was not compiled with native compiler support (--wit
        (error "Emacs was not compiled with native compiler support (--with-native
        (cond ((null (featurep 'nativecomp)) (error "Emacs was not compiled with n
        (comp-ensure-native-compiler)
        (native--compile-async "/home/erasmas/.dotfiles/config/emacs/.emacs.d/.loc
        (let ((load (not (not load)))) (native--compile-async files recursively lo
        (native-compile-async "/home/erasmas/.dotfiles/config/emacs/.emacs.d/.loca
        (let ((inhibit-message t) (message-log-max nil)) (native-compile-async (st
        (progn (let ((inhibit-message t) (message-log-max nil)) (native-compile-as
        (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- '
    ! Extended backtrace logged to .local/doom.error.log
```

**Comment by pimeys** [comment]
I have the same problem with `emacsPgtk`, and with `emacsPgtkGcc` that has the native compilation on, I get:

```
Debugger entered--Lisp error: (native-lisp-load-failed "file does not exists" "/nix/store/yq76d7kl4l0704kg895dp2smv2azjafy-straig...")
  native-elisp-load("/nix/store/yq76d7kl4l0704kg895dp2smv2azjafy-straig..." nil)
  #f(compiled-function (process event) #<bytecode -0x1253a5cd2f9631a5>)(#<process Compiling: /nix/store/yq76d7kl4l0704kg895dp2smv2azjafy-straight-emacs-env/strai
  sleep-for(0.1)
  (let ((inhibit-message t)) (sleep-for 0.1))
  (if (/= previous pending) (progn (doom--print (doom--format (format (doom--output-class 'info "\33[KWaiting for %d async jobs...\33[1A" pending)))) (setq previ
  (while (progn (setq pending (doom--native-compile-jobs)) (not (= 0 pending))) (if (/= previous pending) (progn (doom--print (doom--format (format (doom--output
  (let* ((pending nil) (previous 0) (--cl-var-- t)) (while (progn (setq pending (doom--native-compile-jobs)) (not (= 0 pending))) (if (/= previous pending) (prog
  doom--wait-for-compile-jobs()
  (progn (doom--compile-site-packages) (doom--wait-for-compile-jobs) (doom--write-missing-eln-errors) (doom--print (doom--format (format (doom--output-class 'suc
  (if built (progn (doom--compile-site-packages) (doom--wait-for-compile-jobs) (doom--write-missing-eln-errors) (doom--print (doom--format (format (doom--output-
  (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons ... straight-use-package-pre-build
  (let ((doom-output-indent (+ doom-output-indent-increment doom-output-indent))) (add-hook 'comp-async-cu-done-hook #'doom--native-compile-done-h) (let* ((built
  (let ((pinned (doom-package-pinned-list))) (let ((doom-output-indent (+ doom-output-indent-increment doom-output-indent))) (add-hook 'comp-async-cu-done-hook #
  doom-cli-packages-install()
```

**Comment by kelvie** [comment]
Yeah definitely still doesn't work for me:

https://pastebin.com/dby3V827

**Comment by hlissner** [comment]
@gjm @erasmas @pimeys @kelvie These are all unrelated issues.

> Emacs was not compiled with native compiler support (--with-native-compilation)

This should be fixed in f60f57604, now that straight has been bumped.

> (void-function . straight--process-buffer)

```sh
rm -rf ~/.emacs.d/.local/straight/repos/straight.el
doom sync
```

Then restart Emacs.

> (native-lisp-load-failed "file does not exists" "/nix/store/yq76d7kl4l0704kg895dp2smv2azjafy-straig...")

I don't understand this error. It's implying that straight or one of your elisp packages is installed in your nix store, but Doom does not do this (it can't), so you must have an unconventional setup. Neither Doom or I can help you with that.

**Comment by kelvie** [comment]
Deleting the `straight.el` directory seemed to be the step I was missing, thanks!

**Comment by pimeys** [comment]
Hmm. I tried `nix-collect-garbage`, and `nix flake update`, switched back to `emacsPgtk` without native compilation and I'm still getting the error from straight that emacs was not compiled with native enabled. Can this be some kind of version mismatch, because the `Pgtk` package is version 28 and the one in the unstable branch is 27. Or, is the garbage collection not cleaning the right files?

**Comment by hlissner** [comment]
@pimeys I couldn't tell you. Like I said, the error says `straight` has been installed in your nix-store. This is not Doom's doing, and it doesn't seem related to where you install Emacs from, but rather what packages you've installed it with.
