### ISSUE TITLE
pdf-tools retina display for mac?

### ISSUE THREAD

**Issue by quarkquartet** [hlissner/doom-emacs#4989]
I'm using emacs-plus@27.2 on MacOS X 10.15. When I open pdf with pdf-tools, the image is not as clear as retina display should be. If I use emacs-mac then it is OK. But it should be the emacs-mac-port who fixes this.

I checked the doom code for pdf-tools. I found there is a section for retina display. I do not understand why this cannot work.

If I borrow the configuration from 
https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-reader.el
and add to `config.el`, then it works.

Maybe fix this?

**System Information**
https://pastebin.com/gM9zYdLY

**Comment by hlissner** [comment]
Can you narrow it down to what part from init-reader.el fixed it? Perhaps remove parts until it stops working? They're using 99% the same code (looks like it was generalized from an older version of our module), so it's bizarre that it would behave any different.

**Comment by quarkquartet** [comment]
> Can you narrow it down what part from init-reader.el fixed it? Perhaps remove parts until it stops working? They're using 99% the same code (looks like it was generalized from an older version of our module), so it's bizarre that it would behave any different.
> 
> Also, _please_ do not ignore the issue template in the future. Please provide your `M-x doom/info`.

I'm using from this line:
[https://github.com/seagle0128/.emacs.d/blob/929ccd2aab14f47c7e1b6fd09891ce6849f4da19/lisp/init-reader.el#L80](url)
Let me go to find the doom/info now.

**Comment by quarkquartet** [comment]
> Can you narrow it down what part from init-reader.el fixed it? Perhaps remove parts until it stops working? They're using 99% the same code (looks like it was generalized from an older version of our module), so it's bizarre that it would behave any different.
> 
> Also, _please_ do not ignore the issue template in the future. Please provide your `M-x doom/info`.

Here is my doom/into

> generated    May 05, 2021 17:57:47
distro       MacOS 10.15.7 Darwin 19.6.0 x86_64
emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop b65d8ae3a 2021-05-04 16:37:05 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP
traits       gui server-running envvar-file
modules      :input chinese :completion (company +childframe) ivy :ui doom doom-dashboard hl-todo indent-guides modeline ophints (popup +defaults) treemacs unicode (window-select +switch-window +numbers) :editor file-templates fold (format +onsave) snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools debugger (eval +overlay) lookup lsp magit pdf :os macos :lang (cc +lsp) emacs-lisp (json +lsp) (latex +cdlatex +latexmk) markdown (org +pretty +hugo) (python +lsp +pyright +cython) (sh +lsp) (yaml + lsp) :config (default +bindings +smartparens)
packages     (kaolin-themes) (all-the-icons-ivy-rich) (pdf-continuous-scroll-mode :recipe (:host github :repo dalanicolai/pdf-continuous-scroll-mode.el)) (eaf :recipe (:host github :repo manateelazycat/emacs-application-framework :files (*))) (ctable) (deferred) (epc) (s)

**Comment by quarkquartet** [comment]
> Can you narrow it down what part from init-reader.el fixed it? Perhaps remove parts until it stops working? They're using 99% the same code (looks like it was generalized from an older version of our module), so it's bizarre that it would behave any different.
> 
> Also, _please_ do not ignore the issue template in the future. Please provide your `M-x doom/info`.

I followed your suggestions and tried to remove parts until it stops working. If I remove this part
[https://github.com/seagle0128/.emacs.d/blob/929ccd2aab14f47c7e1b6fd09891ce6849f4da19/lisp/init-reader.el#L94](url)
Then it does not work.

**Comment by hlissner** [comment]
Could you check if the following change [in tools/pdf/config.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/pdf/config.el#L111-L124) fixes your issue? (Remember to remove the code you copied from centaur emacs)

```diff
    (defadvice! +pdf--scale-up-on-retina-display-a (orig-fn &rest args)
      "Scale up the PDF on retina displays."
      :around #'pdf-util-frame-scale-factor
      (cond ((not pdf-view-use-scaling) 1)
            ((and (memq (pdf-view-image-type) '(imagemagick image-io))
                  (fboundp 'frame-monitor-attributes))
             (funcall orig-fn))
            ;; Add special support for retina displays on MacOS
-           ((and (eq (framep-on-display) 'ns)
+           ((and (memq (framep-on-display) '(ns mac))
                  (not +pdf--scaled-p)
                  EMACS27+)
             (setq-local +pdf--scaled-p t)
             2)
            (1)))
```

**Comment by quarkquartet** [comment]
No, it doesn't.
My current code is:
``` elisp
(when (display-graphic-p)
  (use-package! pdf-tools
    :mode ("\\.pdf\\'" . pdf-view-mode)
    :magic ("%PDF" . pdf-view-mode)
    :config
    (defadvice! +pdf--scale-up-on-retina-display-a (orig-fn &rest args)
      "Scale up the PDF on retina displays."
      :around #'pdf-util-frame-scale-factor
      (cond ((not pdf-view-use-scaling) 1)
            ((and (memq (pdf-view-image-type) '(imagemagick image-io))
                  (fboundp 'frame-monitor-attributes))
             (funcall orig-fn))
            ;; Add special support for retina displays on MacOS
            ((and (memq (framep-on-display) '(ns mac))
                  (not +pdf--scaled-p)
                  EMACS27+)
             (setq-local +pdf--scaled-p t)
             2)
            (1)))
))
```

**Comment by hlissner** [comment]
That code won't necessarily work. Please try this instead:

```lisp
(defadvice! fixed+pdf--scale-up-on-retina-display-a (orig-fn &rest args)
  :override #'+pdf--scale-up-on-retina-display-a
  (cond ((not pdf-view-use-scaling) 1)
        ((and (memq (pdf-view-image-type) '(imagemagick image-io))
              (fboundp 'frame-monitor-attributes))
         (funcall orig-fn))
        ;; Add special support for retina displays on MacOS
        ((and (memq (framep-on-display) '(ns mac))
              (not +pdf--scaled-p)
              EMACS27+)
         (setq-local +pdf--scaled-p t)
         2)
        (1)))
```

**Comment by quarkquartet** [comment]
I tried both. Unfortunately none of them works. 

To check if I understand it correctly: the first suggestion is to fix that line in `.emacs.d/modules/tools/pdf/config.el`, the second one is in my personal `config.el` without any `use-package!` or `after!`.

**Comment by hlissner** [comment]
As of ea9753a this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by quarkquartet** [comment]
> As of [ea9753a](https://github.com/hlissner/doom-emacs/commit/ea9753a5f2e9654068fbafa73f3bb475cc26a964) this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Unfortunately, it seems the problem is still here.
<img width="943" alt="blur" src="https://user-images.githubusercontent.com/26316540/117594721-b6d3f480-b10c-11eb-8b9e-50187183eb8d.png">
<img width="952" alt="clear" src="https://user-images.githubusercontent.com/26316540/117594724-b89db800-b10c-11eb-9297-4753ad2c9433.png">
The first plot is the case when I upgrade doom just now.
The second is the one after I use Centaur's pdf config.
I feel really strange about this, since I also think doom's code should work.
Let me disable all my personal config and try what will happen. Maybe it is caused by some of my personal settings.

**Comment by quarkquartet** [comment]
<img width="957" alt="blur2" src="https://user-images.githubusercontent.com/26316540/117595022-8fc9f280-b10d-11eb-9007-570fc9f348df.png">
I tried to uninstall everything and reinstall doom without any personal config, then turn on the pdf-tools. This is the result, seems it's still not retina behavior.

I'm using MacOS Catalina 10.15.7, emacs-plus 27.2. Again, problem does not exist if I use emacs-mac.

Thanks a lot for your effort.

**Comment by hlissner** [comment]
The pdf-tools package has implemented better hiDPI support, so I've bumped it in 38bc1ab, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by quarkquartet** [comment]
> The pdf-tools package has implemented better hiDPI support, so I've bumped it in [38bc1ab](https://github.com/hlissner/doom-emacs/commit/38bc1ab81af6cdc4c4fb9aa163bb44711969af36), which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

I updated doom to v3.0.0 and recompiled everything. Here is the current situation: the left one is by eaf, the right one is by pdf-tool. Still some difference.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26316540/124829845-2583d180-df47-11eb-875d-b53a0be31f6c.png">

I checked the code in the `~/.emacs.d/modules/tools/pdf/package.el`, it shows exactly the same pin as you mentioned.

I'm sorry to trouble all of you this much time. I'm afraid whether I have some problem setting of installing something. So if you need any further information, simply tell me and I'll do that immediately.

**Comment by hlissner** [comment]
Then perhaps this should be reported upstream, to https://github.com/vedang/pdf-tools, now that it is maintained again. What's more, https://github.com/vedang/pdf-tools/commit/f771c93781b3135200cae6dbc8e45dbb887f77b1 and https://github.com/vedang/pdf-tools/pull/13 were supposed to address this situation. That it fails to I consider an external issue.

**Comment by memeplex** [comment]
I'm having a similar issue, in a MacBook Pro 2017 documents opened by pdf-view are very blurry compared to, for example, the ones opened by the stock Preview app.  I'm using emacs 27.2, pdf-tools version 20210531.1613, with `(setq pdf-view-use-scaling t)`. The commit https://github.com/vedang/pdf-tools/commit/f771c93781b3135200cae6dbc8e45dbb887f77b1 mentions a `frame-scale-factor` that is a "new function introduced in Vanilla Emacs" but it doesn't seem to be present in my emacs install (https://emacsformacosx.com/). I believe that's just a repackaging of vanilla emacs as a macOS app, but I may be wrong.

**Comment by memeplex** [comment]
It seems that is related to the fact that vedang/pdf-tools@f771c93 requires `frame-scale-factor` but that function is not included in 27.2 but only in the development version of emacs (28). You can install it with `brew install emacs-plus@28` and give it a try, it worked for me (plus fixed svg rendering in org-mode LaTeX previews).

**Comment by everydayanchovies** [comment]
Some may care to know that when using the emacs-mac-app port (Mitsuharu's or railwaycat's), you can render the PDF using the MacOS-native rendering method (same as in Preview.app). This is radically faster and the render is more pronounced. It's actually so fast that you are better off disabling caching all together.

Before:

<img width="1346" height="951" alt="Image" src="https://github.com/user-attachments/assets/b6b984e0-c1c2-405d-b87e-378fbe66270b" />

After:

<img width="1346" height="951" alt="Image" src="https://github.com/user-attachments/assets/fa2b2128-f414-4f5a-88cf-280dd39194d6" />

```elisp
(when (featurep :system 'macos)
    (setq pdf-cache-image-inihibit t)

    (defadvice! +pdf-view-create-page--maybe-macos-native
      (orig-fn page &optional window size)
      :around #'pdf-view-create-page
      (let* ((size (or size (pdf-view-desired-image-size page window)))
                (hotspots (pdf-view-apply-hotspot-functions window page size)))
        (create-image buffer-file-name 'image-io nil
                      :index (- page 1)
                      :transform-smoothing t
                      :width (car size)
                      :rotation (or pdf-view--current-rotation 0)
                      :map hotspots
                      :original-map hotspots
                      :pointer 'arrow))))
```

See https://codeberg.org/rahguzar/pdf-tools/issues/13 for more details.
