### ISSUE TITLE
d4dec35 broke `variable-pitch` fonts in `mixed-pitch-mode` + `writeroom-mode`

### ISSUE THREAD

**Issue by zzamboni** [hlissner/doom-emacs#4991]
**What did you expect to happen?**

My configured fonts to work correctly on macOS, using `emacs-mac` Formula (Emacs 27.2).

**What actually happened?**

After commit d4dec3565870b96abff0f08f1b638b9d527a7086, my doom-variable-pitch-font is not being displayed correctly - I get Helvetica, which I guess is the default font. This happened from one restart to the next, with some doom upgrade in the middle, but not sure if that's what caused it. The variable is set correctly according to my config:
```elisp
(setq doom-font (font-spec :family "Fira Code" :size 18)
      doom-variable-pitch-font (font-spec :family "Alegreya" :size 18))
```
```
doom-variable-pitch-font is a variable defined in core-ui.el.

Value
#<font-spec nil nil Alegreya nil nil nil nil nil 18 nil nil nil nil>
```
But I still don't see the font. My doom-font is shown correctly:
![image](https://user-images.githubusercontent.com/32876/117299134-778d7580-ae78-11eb-885d-607d59f3f546.png)

**Additional details:**

Rolling back to commit b63441387b47a69c45dc76f7a330c0cf8160cd1f fixes the problem.

**Steps to reproduce:**

As described above.

**System information:**

https://pastebin.com/iEu5e95T

**Comment by hlissner** [comment]
Is the `variable-pitch` face's `:family` (or `:font`) property correctly set? (`C-h F variable-pitch` to check)

**Comment by Magnuscake** [comment]
Can confirm, facing the same issue as well. @hlissner `:family` in this case shows Sans Serif, which is probably the default font on my system, when in fact it should be Ubuntu. Also, changing the font size does not do anything, even with the default font, leading me to believe that it might be something to do with the entire `doom-variable-pitch-font` face.

**Comment by hlissner** [comment]
As of 075e66f this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by zzamboni** [comment]
@hlissner thanks for looking into this - unfortunately in my case the problem persists. Here's all the information I can think of as relevant, please let me know if there's anything else you need:

My font config (my config file: https://github.com/zzamboni/dot-doom/blob/master/config.el#L89-L91):
```elisp
(setq doom-font (font-spec :family "Fira Code" :size 18)
      doom-variable-pitch-font (font-spec :family "Alegreya" :size 18))
```
However, `variable-pitch`s :family is incorrect. From `C-h F variable-pitch`:
```
Face: variable-pitch (sample) (customize this face)

Documentation:
The basic variable-pitch face.

Defined in ‘faces.el’.

           Family: Sans Serif
           ... (all other attributes are "unspecified")
```
Thanks again for your help!

**Comment by zzamboni** [comment]
Quick update: I ran `doom upgrade` again today, and one of the recent commits has now fixed this issue for me as well. Thanks!
