### ISSUE TITLE
doom-{variable,unicode}-font no longer applied at startup

### ISSUE THREAD

**Issue by marienz** [hlissner/doom-emacs#5000]
With the following font configuration in config.el:
```
(setq doom-font (font-spec :family "Terminus" :size 14 :weight 'normal)
      doom-big-font (font-spec :family "Terminus" :size 28 :weight 'normal)
      doom-unicode-font (font-spec :family "Noto Color Emoji")
      doom-variable-pitch-font (font-spec :family "sans" :size 13))
```
(and most of the rest of my config disabled just in case), after starting Emacs with --fg-daemon and opening a graphical (pgtk on wayland) frame using emacsclient, Emacs renders the test emoji in init.example.el as a replacement character (box containing "01f642") instead of an emoji. This worked correctly before commit d4dec3565870b96abff0f08f1b638b9d527a7086 (confirmed by rolling back), and still works correctly if I launch a standalone graphical Emacs directly instead of using the daemon. I can also fix it by calling `doom/reload-font`, which instantly makes the emoji character appear.

Prior to that commit, I needed to set doom-unicode-font (as above) to avoid the same problem. So it looks like doom-unicode-font (and the other fallbacks applied automatically after that commit) aren't working correctly.

I suspect what changed is that before that commit `doom-init-extra-fonts-h` called `set-fontset-font` [after loading the theme](https://github.com/hlissner/doom-emacs/commit/d4dec3565870b96abff0f08f1b638b9d527a7086#diff-ccc44f920067423981834b675383f70a3cd4509f24ae94f028afc7fe7fbd45f2L704), which happened [after opening the first frame](https://github.com/hlissner/doom-emacs/blob/d4dec3565870b96abff0f08f1b638b9d527a7086/core/core-ui.el#L704-L705), while now the [equivalent code](https://github.com/hlissner/doom-emacs/blob/d4dec3565870b96abff0f08f1b638b9d527a7086/core/core-ui.el#L584-L591) runs [at startup](https://github.com/hlissner/doom-emacs/blob/d4dec3565870b96abff0f08f1b638b9d527a7086/core/core-ui.el#L701) (before there is a graphical frame). But I haven't fully confirmed that, or figured out why initializing things earlier breaks.

(I only very rarely need this to work, and really only noticed because I checked if I could drop doom-unicode-font from my config after that commit... I'm really only filing this issue in case the fix is obvious to someone more familiar with Emacs fontsets and how they interact with frames, or in case calling `doom/reload-font` on frame creation is a reasonable fix.)

**What did you expect to happen?**
Same font setup in a graphical frame on emacs with --fg-daemon and without.

**What actually happened?**
doom-unicode-font does not work correctly with emacs --fg-daemon, but works without it.

**Additional details:**
Please let me know if I left anything out above or below.

**Steps to reproduce:**
1. Install a basic fixed-width font such as [http://terminus-font.sourceforge.net/](terminus-font) that definitely does not support emojis, and a font such as Noto Color Emoji that does
2. Set doom-font to the former, doom-unicode-font to the latter
3. Run `emacs --fg-daemon`
4. Run `emacsclient -n -c` to open a graphical frame (I'm running this in a Wayland compositor)
5. Open https://github.com/hlissner/doom-emacs/blob/develop/init.example.el#L33 and look at the test emoji

**System information:**
`M-x doom/info` from inside an Emacs with the font display issue: https://pastebin.com/wc1cDtGG

The Emacs I'm running is from https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/ (an Emacs 28 snapshot to get pgtk and nativecomp).

**Comment by hlissner** [comment]
As of 578dddd this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by egorbelibov** [comment]
https://github.com/hlissner/doom-emacs/issues/4999#issuecomment-834758549

**Comment by marienz** [comment]
I'm still seeing the same behavior after updating (to 195ad0fec).

**Comment by hlissner** [comment]
Alright, f989bf6 should do it. Let me know if that didn't work.

**Comment by marienz** [comment]
After updating (to 5a9171ed5), I'm still seeing the same behavior.

**Comment by hlissner** [comment]
In that case I can no longer reproduce the issue, and suspect your private config is the issue. Can you reproduce the issue [in vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by marienz** [comment]
Actually using the sandbox is a bit tricky (I use chemacs which breaks it, and I'm not sure if I can pass --fg-daemon to the sandbox), but hopefully this is close enough to "vanilla Doom+" and "vanilla Doom" respectively:

- Removed everything from my config.el except for
```elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq doom-font (font-spec :family "Terminus" :size 14 :weight 'normal)
      doom-big-font (font-spec :family "Terminus" :size 28 :weight 'normal)
      doom-unicode-font (font-spec :family "Noto Color Emoji")
      doom-variable-pitch-font (font-spec :family "sans" :size 13))
```
- Replaced my init.el with init.example.el
- Removed everything except comments from package.el
- Ran `doom sync`
- Ran `emacs --no-site-file --fg-daemon`
- Ran `emacsclient -n -c` to open a frame
- Used `C-x C-f init.el RET` to open init.el

I still see the same behavior (no emoji until I run `M-x doom/reload-font`).

Next, I replaced init.el with an empty file and re-ran `doom sync`. I still see the same behavior. (I also still see the same behavior if I further reduce config.el to just `(setq doom-unicode-font (font-spec :family "Noto Color Emoji"))`, but I'm not sure which font(s) that ends up using by default.)

Please don't spend more time on this if it's not reproducible on your end. I honestly doubt I would've even noticed this problem without that test emoji in init.el (other files I edit typically do not contain any emoji...), but I'll get around to troubleshooting it at some point (and am happy to bump that up my to-do list if anyone else is affected).

**Comment by marienz** [comment]
After updating to a4a64b9c6, I'm still seeing the same behavior (although I haven't yet verified again with "vanilla Doom", just my normal config both with and without cusom `doom-theme`).

I'll see if I can do some troubleshooting on my end since it sounds like there's something about my setup (fonts? Emacs version?) needed to trigger it... Just need to find time to learn about Emacs fonts/fontsets first.

**Comment by hlissner** [comment]
Fourth time's the charm? Let me know if cebbd76 fixes your issue.

**Comment by marienz** [comment]
Still no change after updating (tested "vanilla Doom+": everything other than the font settings in config.el disabled).

I promise I'll troubleshoot this on my end this weekend or so: there has to be something special about my local setup if you can't reproduce this, and I should be able to at least narrow down what that is (just need a block of time to experiment with different Emacs versions and/or investigate what the difference in the fontset state I end up with in the daemon vs non-daemon case is). When I filed this I assumed I'd just hit an edge case you hadn't tested: I'm happy to keep testing changes, but if you can't reproduce the issue I feel I owe you a better bug report.

**Comment by hlissner** [comment]
With help from #5009, I'm hoping 4397f01 should will fix this issue too. Let me know!

**Comment by marienz** [comment]
Still no change. I don't have a custom.el.

**Comment by mattsawyer77** [comment]
@hlissner 4397f01 fixed the problem for me.

**Comment by stefanocoretta** [comment]
Hi! (thanks y'all for the amazing work!) I had this same issue and upgraded doom to latest but that didn't fix it (reloading the font does work, as per above comments).

What seems to have fixed it was disabling the `unicode` module in `init.el`. As far as I can tell, fonts are correctly selected now.

<details>
<summary>My config (`doom/info`)</summary>
<pre><code>
generated    May 25, 2021 18:22:36
system       MacOS 11.3.1 Darwin 20.4.0 x86_64 mac
emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop daa50557a 2021-05-25 00:11:58 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES THREADS JSON PDUMPER GMP
traits       gui server-running envvar-file
modules      :completion company (ivy +fuzzy +prescient +childframe +icons) :ui deft doom doom-dashboard (emoji +unicode) hl-todo indent-guides ligatures modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit pdf :os macos :lang emacs-lisp ess json javascript markdown (org +roam) sh :config (default +bindings +smartparens)
packages     (emojify) (org-fancy-priorities) (forge) (pandoc-mode) (treemacs-evil) (treemacs-projectile) (treemacs-magit) (treemacs-icons-dired) (treemacs-all-the-icons) (csv-mode) (ivy-bibtex) (org-ref)
</code></pre>
</details>
