### ISSUE TITLE
custom-set-faces! and custom-theme-set-faces! don't apply at startup anymore

### ISSUE THREAD

**Issue by Wetlize** [hlissner/doom-emacs#5009]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.

### What did you expect to happen?

Applying customization through the mentioned macros should change appearance of the selected face *at startup*.

### What actually happened?

After recent changes on the upstream the customization to faces doesn't apply anymore. I guess f989bf60f00a0da4fdb56e1768c464b52b4dddda and 1c549f21d688f78a129d27d4c417f4fae2b227ce are the offenders.

### Describe your attempts to resolve the issue
Reloading theme at runtime (e.g. with `doom/reload-theme` or `counsel-load-theme`) does change faces as expected, so the only problem is somewhere in the startup related pipeline.

### Steps to reproduce

1. In the sandbox or a config file:
```lisp
(after! org
  (custom-set-faces!
    '(org-drawer :inherit org-document-info-keyword :foreground unspecified :height .8)
    '(org-meta-line :inherit org-document-info-keyword :foreground unspecified :height .9))
```
2. Start a new Emacs process.
3. Open an org file and check that the customization didn't apply to the mentioned faces.
4. Run `doom/reload-theme` and see that the customization now works as expected.

### System Information

https://pastebin.com/2HCdACGe

**Comment by Wetlize** [comment]
Could be connected now with #5000.

**Comment by Wetlize** [comment]
Applying
```lisp
(custom-set-faces!
    '(org-drawer :inherit org-document-info-keyword :foreground unspecified :height .8)
    '(org-meta-line :inherit org-document-info-keyword :foreground unspecified :height .9)
```
without wrapping the form with `after!` (or similar) will fix the issue, but I'm not sure if this intended now? 
Before the new commits it worked just fine.

**Comment by hlissner** [comment]
As of f3c496d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Wetlize** [comment]
@hlissner Sadly, the issue still persists after the new commit and in exact the same way.

**Comment by Wetlize** [comment]
On top of all that, after cab8f03a513fe3d88879239f36483920dc5c5ace and 8f3b7986209817305f544fac83baa7cd0f1d5ced hitting the same issue as #5015 if I try to run `doom/reload-theme` or `counsel-load-theme`.

**Comment by hlissner** [comment]
Second time's a charm? Let me know if cebbd76 fixes the issue.

**Comment by throwawayaccount-el** [comment]
https://github.com/hlissner/doom-emacs/blob/68ba7e0f56570537cd6c79fd8b8bbeacad03fac6/core/autoload/themes.el#L40
It appears the above expression doesn't ever evaluate to `t`.

**Comment by hlissner** [comment]
@throwawayaccount-el That was it! Good catch.

-----

Here's to hoping 4397f01 finally puts this issue to rest! Let me know if it hasn't and I'll reopen it.
