### ISSUE TITLE
Doom cli command fails because of doom.sh not found

### ISSUE THREAD

**Issue by lovebug356** [hlissner/doom-emacs#5071]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

All cli commands like ```doom sync``` fail, I would expect that they are not failing.

### What actually happened?

All cli commands like ```doom sync``` fail with an error message it can't find doom.sh:

```
$ ./bin/doom sync
> Compiling your literate config...
  - Tangled 22 code blocks from config.org.xh1OtI
  - Restarting...
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    > Updating recipe repos...
      x There was an unexpected error
        Message: Symbol's function definition is void
        Data: (void-function . straight--process-buffer)
        Backtrace:
          (straight--process-buffer)
          (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
          (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
          (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
          (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
          (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
          (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
          (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
          (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
      ! Extended backtrace logged to .local/doom.error.log
sh: /tmp//doom.sh: No such file or directory

```

### Describe your attempts to resolve the issue

- I tried to remove ```.emacs.d``` and start with a clean checkout.
- The command also fails with ```doom doctor```, no error messages are printed before.
```
$ ./bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected error
    Message: File is missing
    Data: (file-missing . "Cannot open load file")
    Backtrace:
      (load "/home/tvermeir/.emacs.d/.local/autoloads.27.2" nil nomessage)
      (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) n
      (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message
      (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-de
      (doom-initialize force)
      (let ((doom-interactive-p 'doctor)) (doom-initialize 'force) (doom-initial
      (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
      (condition-case ex (let ((doom-output-indent (+ doom-output-indent-increme
      (let nil :bare t (doom--print (doom--format (format "The doctor will see y
      ((closure ((plist :bare t :group "Diagnostics") (aliases doc) (name . doct
  ! Extended backtrace logged to .local/doom.error.log
sh: /tmp//doom.sh: No such file or directory
```

### Steps to reproduce

1. with a clean install
2. do ```./bin/doom sync``` (or any other command)
3. My .doom.d/init.rc (in [this pastebin](https://pastebin.com/7Cr2mifT))

### System Information

https://pastebin.com/rE61GgkY

**Comment by lovebug356** [comment]
FWIW, the last lines of the ```doom.error.log```:

```
...
(if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 7)) (doom--cli-process cli (remq nil args))) (user-error "Couldn't find any %S command" command))

(let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 7)) (doom--cli-process cli (remq nil args))) (user-error "Couldn't find any %S command" command)))

(doom-cli-execute :doom "sync")

```

**Comment by alphaQ314** [comment]
I'm getting the same error.

**Comment by hlissner** [comment]
As of ef7113d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by lovebug356** [comment]
This does not fix it for me, however the output of the error is different:
```
$./bin/doom -y upgrade 
- Confirmations auto-accept enabled
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Compiling your literate config...
  - Tangled 22 code blocks from config.org.8aB2Ha
  - Restarting...
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    > Updating recipe repos...
      x There was an unexpected error
        Message: Symbol's function definition is void
        Data: (void-function . straight--process-buffer)
        Backtrace:
          (straight--process-buffer)
          (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
          (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
          (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
          (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
          (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
          (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
          (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
          (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
      ! Extended backtrace logged to .local/doom.error.log
```
last lines of the logs are similar:
```
$ tail -n 3 .local/doom.error.log 
(let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 7)) (doom--cli-process cli (remq nil args))) (user-error "Couldn't find any %S command" command)))

(doom-cli-execute :doom "-y" "upgrade")

```

**Comment by hlissner** [comment]
@lovebug356 then your original issue is fixed. FYour new issue is unrelated. See #4950 for explanation+fix.

**Comment by lovebug356** [comment]
Ok, thanks for the quick response!

**Comment by alphaQ314** [comment]
Mine was having several issues, so I just reinstalled my doom haha! Its all fine now. Your quick turnaround is appreciated @hlissner :)
