### ISSUE TITLE
Helm projectile commands not working anymore

### ISSUE THREAD

**Issue by dariooddenino** [hlissner/doom-emacs#512]
### Observed behavior
I'm on the latest develop commit.
Helm related commands (for example `SPC-p-p`, `SPC-:` or `M-x`) give me this error:
`Wrong type argument: bufferp, "*helm projectile: ~*"`

### Expected behavior

For the commands to work

### Steps to reproduce

1. Checkout last develop commit
2. Open emacs
3. `M-x`

### System information

```
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Doom Doctor
Emacs v25.2.2
Doom v2.0.9 (f0c46e59)
shell: /bin/bash
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL
  LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS
  GTK3 X11
uname -a:
  Linux dario-thinkpad 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC
  2018 x86_64 x86_64 x86_64 GNU/Linux

----
test-emacs
test-private-config
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar

----
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
Loading /home/dario/.emacs.d/modules/feature/snippets/packages.el (source)...

----
Everything seems fine, happy Emacs’ing!
```
</details>

**Comment by azy2** [comment]
See #507 I think that should fix your problem.

**Comment by hlissner** [comment]
As of 9e89c06 this should be fixed (on `develop`). Let me know if that isn't the case.

I'll leave this issue open until it is merged into `master`.

**Comment by dariooddenino** [comment]
Fixed for me, thanks :)

**Comment by benreyn** [comment]
This is still happening for me on `develop` I also just logged #566. Could be related?

**Comment by hlissner** [comment]
@benreyn Are you still experiencing this issue? I've made a number of changes to how Doom initializes evil-collection, so I'm hoping it's fixed itself.

**Comment by benreyn** [comment]
In all honesty Im back on spacemacs for the time being. The inability to get rspec-mode initializing properly in projects (re: #585 and various discussion we had in discord) combined with a lack of time to spend on configuring my editor (the worst) I just had to switch back to the tool I knew I could use pseudo-reliably. Im happy to reinstall and give it a whirl this weekend.

**Comment by hlissner** [comment]
@benreyn Totally understandable! No rush, but do let me know how your test run fares. In the meantime, I'll have a look at rspec-mode again (they've updated it recently).

**Comment by hlissner** [comment]
I'll close this since the original issue has been resolved. Feel free to follow up or reopen this if the issue resurfaces.
