### ISSUE TITLE
Formatting on save fails to take formatting by lsp-servers into account

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#5128]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

If I have `:editor (format +onsave)` enabled and `+format-with-lsp` set to true, I expect LSP-servers to format buffers on save, if the provide they corresponding feature.

### What actually happened?

In the situation described above, the buffer is not formatted when saving, even though the LSP-server provides document formatting capacities. The `before-save-hook` does not contain a function to invoke LSP-formatting

### Describe your attempts to resolve the issue

I tried to debug the issue and found what seems to be two issues with the following function:

```elisp
(defun +format-enable-for-lsp-on-save-maybe-h ()
  "Enable LSP formatter when LSP client is available."
  (remove-hook 'lsp-mode-hook #'+format-enable-for-lsp-on-save-maybe-h 'local)
  (cond ((not +format-with-lsp) nil)
        ((bound-and-true-p lsp-mode)
         (when (lsp-feature? "textDocument/formatting")
           (+format-enable-on-save-h))
         t)
        ((bound-and-true-p eglot--managed-mode)
         (when (eglot--server-capable :documentRangeFormattingProvider)
           (+format-enable-on-save-h))
         t)
        ((bound-and-true-p lsp--buffer-deferred)
         (add-hook 'lsp-mode-hook #'+format-enable-for-lsp-on-save-maybe-h
                   nil 'local)
         t)))
```

1. That function initially runs after a change of major mode. However, the checks for `lsp-mode` or `lsp--buffer-deferred` fail, because `lsp-mode` is usually started in the `local-vars-hook` of the corresponding major mode which runs after after-change-major-mode-hook.
2. At least for `lsp-mode` and if the lsp-server isn't already running, there is a race condition in the sense that `(bound-and-true-p lsp-mode)` might return true but `(lsp-feature? "textDocument/formatting")` returns `nil`, even though the language server provides document formatting. 

### Steps to reproduce

1. Setup Doom with `:editor (format +onsave)` and `+format-with-lsp` set to true
2. Also enable LSP support for csharp in `init.el`
3. Install omnisharp-roselyn LSP-server
4. Open a csharp-file and perform some editing operations like adding gratuitous whitespace
5. Save the buffer
6. The buffer is not formatted before it is saved
7. Manually invoke `lsp-format-buffer` to confirm that the LSP server is able to format the buffer 

### System Information

https://pastebin.com/PyqgweJd

**Comment by hlissner** [comment]
As of 68b422c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by sagittaros** [comment]
As of `9fb96f9`, `+onsave` does not trigger lsp formatting.

I am using `clojure-lsp` and it has built-in formatting capability.
Both interactive `+format/buffer` and `lsp-format-buffer` are working.

<img width="403" alt="lsp-describe-dession" src="https://user-images.githubusercontent.com/787015/120884037-4a68ea00-c613-11eb-8a22-8e99d381833f.png">

Understand that it is a Sunday, take your time :)

**Comment by RBckmnn** [comment]
I'm afraid, I have to agree. I'm on `9fb96f9` as well and the issue is already present. I'm busy today but I will try to dig into the issue over the next few days and post my findings here.

**Comment by sagittaros** [comment]
I checked out from `99a83ca` and both the LSP and `format-all` fallback mechanism work for me.

```sh
git checkout 99a83ca -- modules/editor/format
doom sync
```

The diff can be found here (between `develop` and `99a83ca`):
https://gist.github.com/sagittaros/e9ee3a324fd54e5bf65212d6b90b5795

**Comment by robinbourianes-kalisio** [comment]
Hi there, trying to dig into this issue, considering the following relevant bits from my init.el
```
:editor format
:tools (lsp +eglot)
:lang (cc +lsp)
```

I've observed that `+format-buffer-a` is **not** called with the following bits in config.el :
```
(add-hook 'c-mode-hook #'format-all-mode)               ;; enable code formatting on save
```

It is called when adjusting config.el to the following:
```
(add-hook 'c-mode-hook #'format-all-mode)               ;; enable code formatting on save
(setq-hook! 'c-mode-hook +format-with-lsp nil)
```
I'm not sure I'll be able to tell why `+format-buffer-a` is not called, my lisp skills are pretty much non-existent.
Hope that helps!

**Comment by numkem** [comment]
For what it's worth, I am having the same issue with elixir and doing what @sagittaros propsed worked for me.

**Comment by robinbourianes-kalisio** [comment]
Some more observations, maybe it'll make sense to lisp enabled people.
`+format-probe-a` ends by doing `funcall orig-fn` where orig-fn is `format-all-buffer--with`. The issue maybe around here because when doing that sort of indirect function call, it won't call the `+format-buffer-a` advice that's supposed to extend `format-all-buffer-with` to support +lsp formatting. Instead it seems it directly jump into `format-all-buffer--with` and lsp formatting is not applied.
This is with latest doom-emacs https://github.com/hlissner/doom-emacs/commit/2731685095d1e6101b3215aa689426e1834ce00f

**Comment by hlissner** [comment]
As of bbd15a1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ckruse** [comment]
I fear this is still broken. I have `lsp`, `(elixir +lsp)` and `(format +onsave)`, and this hook:

~~~elisp
(setq-hook! 'elixir-mode-hook +format-with-lsp t)
~~~

But when saving an Elixir file `format-on-save` formats the buffer (I notice it because `format-on-save` ignores my line length configuration). I have to add `elixir-mode` to the disabled modes for `format-on-save` and write this hook to get formatting via LSP working:

~~~elisp
(add-hook! elixir-mode
  (add-hook 'before-save-hook 'lsp-format-buffer nil t))
~~~

**Comment by numkem** [comment]
I can confirm this is still a problem. I have to rely on 99a83ca for getting things working again.

**Comment by numkem** [comment]
PR 5302 seems to have fixed it, I'm no longer seeing the error and it is formating correctly.
