### ISSUE TITLE
centaur-tabs' `gt`/`gT` asking for more key input.

### ISSUE THREAD

**Issue by acristoffers** [hlissner/doom-emacs#5176]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When pressing `gt` or `gT`, the tab should be switched immediately.

### What actually happened?

Instead of switching immediately, it stops waiting for another keystroke.

### Describe your attempts to resolve the issue

I saw that if you press `SPC` or a letter, it switches tabs, but if you press an arrow key, the message "No replacement character typed" appears. This message seems to come from .local/straight/repos/evil/evil-common.el:609.

I removed my config and tested with the default doom config, and there `gt` is bound to workspace switching and works normally. Enabling tabs the bug appears again. I tried to remove the keybinding for workspace (in case it was conflicting) but that does not solve the issue.

### Steps to reproduce

Install doom and enable the tabs module. Open two tabs and try to switch with `gt`.

### System Information

https://pastebin.com/65trckWw

**Comment by holyfight6** [comment]
I think the `current-prefix-arg` in:
``` emacs-lisp
(evil-define-command +tabs:next-or-goto (index)
  "Switch to the next tab, or to INDEXth tab if a count is given."
  (interactive "<C>")
  (if current-prefix-arg
      (centaur-tabs-select-visible-nth-tab current-prefix-arg)
    (centaur-tabs-forward)))
``` 
should be `index`, it's reading the prefix rather than the extra key?

**Comment by acristoffers** [comment]
Simply replacing `current-prefix-arg` by `index` and restarting emacs resulted in the functionality not working anymore. `gt` took me to the last tab and then `gT` did nothing.

**Comment by holyfight6** [comment]
@acristoffers Hi, I tried to edebug this and found out `<C>` will set the extra key's byte as the value of `index`.
So I think this function should be like this
``` emacs-lisp
(evil-define-command +tabs:next-or-goto (index)
  "Switch to the next tab, or to INDEXth tab if a count is given."
  (interactive "P")
  (if index
      (centaur-tabs-select-visible-nth-tab index)
    (centaur-tabs-forward)))
```
which takes the prefix as the tab index.  Or it needs to to parse the key to number as the real index.

**Comment by acristoffers** [comment]
Yep, tried it and it works as expected.

**Comment by hlissner** [comment]
Whoops! Good catch. This should be fixed as of 1a96f5b. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kagutaba256** [comment]
Hey, sorry, but I'm still having this problem after [https://github.com/hlissner/doom-emacs/commit/1a96f5b002c479627453d6004597bf8333c6b2be](url). It works as expected after i change `(interactive "<C>")` to `(interactive "P")` for both `next-or-goto` and `previous-and-goto`

**Comment by hlissner** [comment]
> Hey, sorry, but I'm still having this problem after [1a96f5b](https://github.com/hlissner/doom-emacs/commit/1a96f5b002c479627453d6004597bf8333c6b2be). It works as expected after i change `(interactive "<C>")` to `(interactive "P")` for both `next-or-goto` and `previous-and-goto`

It's working fine for me in vanilla Doom. And mechanically, `<c>` should (mostly) produce the same result as `P`.

**Comment by hlissner** [comment]
Ah, my bad, I was testing it incorrectly. As of 80c32ea this should be properly fixed.
