### ISSUE TITLE
org agenda follow mode doesn't follow

### ISSUE THREAD

**Issue by ronnac** [hlissner/doom-emacs#5244]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

SPC o a m today → shows all org headers tagged with "today"
z f → activates "follow mode": OK, the details of the header at point are displayed in a second buffer
In the first buffer I browse up or down to a different org header.
I expect to see the details of the header under the cursor.

### What actually happened?

the view in the 2nd buffer doesn't move.
If I deactivate and re-activate follow mode ( z f z f) in the first buffer, I see the detail of the org header at point.

I have no access to pastebin

generated    Jul 07, 2021 13:56:27
system       Windows Unknown MINGW64_NT-10.0-18363 3.1.7-340.x86_64 x86_64 w32
emacs        28.0.50 feature/native-comp ff053c706 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD 2731685 2021-06-07 21:16:29 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        C:\Users\$USER\Documents\Utilities\git-sdk-64\usr\bin\bash.exe
features     ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS ZLIB
traits       gui server-running envvar-file custom-file
custom       org-agenda-files
modules      :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)

### Describe your attempts to resolve the issue

I tried on Windows/msys2 and on Android/termux.

### Steps to reproduce

cf above

### System Information

https://pastebin.com/QiJRvYFy

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom. `zf` and `M-x org-agenda-follow-mode` both correctly activate the mode, and the second buffer is correctly updated when the cursor is over an agenda heading.

Please investigate the \*Messages\* buffer with <kbd>C-h</kbd><kbd>e</kbd>, and look for warnings or errors that occur when you toggle org-agenda-follow-mode, or when it's trying to update the second buffer.

**Comment by ronnac** [comment]
The messages buffer only says 
`Follow mode is on`
`Follow mode is off`
... on both systems.  I currently don't have access to a normal Linux machine with emacs.
Both systems (msys2, termux) are sufficiently different from each other, so I suspect it must be one of the packages I installed.

**Comment by hlissner** [comment]
Since things behave normally in vanilla Doom, I'm inclined to suspect it's a personal configuration issue, rather than a Doom issue. Can you capture a screencast of this behavior?

**Comment by hlissner** [comment]
Oh, also try unpinning the `org-mode` package. Perhaps this has been fixed in a newer version of org.

1. Add `(unpin! org-mode)` to `~/.doom.d/packages.el`
2. Run `doom sync -u` on the command line.
3. Restart Emacs.

**Comment by ronnac** [comment]
I just reinstalled emacs and doom in windows, so now I have vanilla Doom. I still have the same problem. Here is the screencast.
![follow-mode](https://user-images.githubusercontent.com/30430574/124906061-f6bd3800-dfe6-11eb-897f-bc198274545c.gif)

**Comment by Oaaazy** [comment]
Hi, any update for this issue? I am having exactly same problem.

**Comment by Oaaazy** [comment]
Update: I disabled evil and org-agenda-follow-mode behaved normal.
