### ISSUE TITLE
doom-system-cpus returns 1 on msys2 build

### ISSUE THREAD

**Issue by jsirpoma** [hlissner/doom-emacs#5347]
### What did you expect to happen?

When doing ``doom sync`` or ``doom upgrade``, native compilation is done with only one process. I would have expected it to be done with 8 processors.

### What actually happened?

- Evaluating (doom-system-cpus) returns 1 instead of 8
- (comp-effective-async-max-jobs) seems to calculate it correctly as 4

After looking into this a bit, it seems that the cl-typecase in doom-system-cpus does not handle integer type returned from w32-get-nproc earlier. See https://github.com/hlissner/doom-emacs/blob/a2a128d3a56a96610fce261f4df256d289135c74/core/autoload/system.el#L81-L107

In my system  w32-get-nproc returns 8.

### Describe your attempts to resolve the issue

Adding ``(put 'doom-system-cpus 'cached-value 8)`` to init.el seems to be a workaround.

### Steps to reproduce

1. Upgrade doom in windows system with native compilation enabled
2. Notice slow proggress of native compilation proggress
3. Verify from for example task manager that only one process is used
4. Evaluate (doom-system-cpus) and notice that it returns 1 on multicore system.

### System Information

https://pastebin.com/pbfCxHNp

**Comment by hlissner** [comment]
As of ce31880 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jsirpoma** [comment]
@hlissner: Thank you for the very fast reaction! Unfortunately this did not fix the problem. I think the issue is still that:
- The cond  below does find 'w32-get-nproc and uses it (it did so also earlier with the system-type check).
https://github.com/hlissner/doom-emacs/blob/ce31880ccc31568de45e53d9bbec5bde69661d1c/core/autoload/system.el#L87-L93
- The return type of w32-get-nproc is not string, but it is **integer**
- The cl-typecase below does not handle integer type, only string and cons cell
https://github.com/hlissner/doom-emacs/blob/ce31880ccc31568de45e53d9bbec5bde69661d1c/core/autoload/system.el#L95-L106

I am not really fluent in elisp so suggesting a correct fix is not easy, but maybe this is simple enough. Seems to work when I tried:
```
              1 (or (cl-typecase cpus
                      (integer cpus)  ;; <== Add this?
                      (string
                       (condition-case _
                           (string-to-number cpus)
                         (wrong-type-argument
                          (user-error "NUMBER_OF_PROCESSORS contains an invalid value: %S"
                                      cpus))))
                      (consp
                       (if (zerop (car cpus))
                           (string-to-number (cdr cpus))
                         (user-error "Failed to look up number of processors, because:\n\n%s"
                                     (cdr cpus)))))
                    1)))
```

**Comment by hlissner** [comment]
Thanks for the detailed analysis! I don't have a Windows system to actively test on yet, so it was a big help. In any case, this should finally be fixed in e76f538.

**Comment by jsirpoma** [comment]
👍 Works well now!

Thank you for the quick reaction times again. It makes it a lot easier to help!
