### ISSUE TITLE
Error (before-save-hook): Error running hook "org-encrypt-entries" because: (void-function native-comp-available-p)

### ISSUE THREAD

**Issue by slebedev** [hlissner/doom-emacs#5706]
### What did you expect to happen?

doom-emacs works with org-file as expected after upgrade with [org bump](https://github.com/hlissner/doom-emacs/commit/20b74b79512c1c5e5866a389513c71a032f55d83)

### What actually happened?

I'm unable to save org-file with new (or changed) todos with the following error:

```
Error (before-save-hook): Error running hook "org-encrypt-entries" because: (void-function native-comp-available-p)
```

The following backtrace was catched on debug (`M-x org-reload RET`, `M-x toggle-debug-on-error RET`):

```
Debugger entered--Lisp error: (void-function native-comp-available-p)
  native-comp-available-p()
  org-element-cache-map(ignore :granularity headline+inlinetask)
  org-element-cache-map(#f(compiled-function (el) #<bytecode 0x1ff0580dab2d>) :next-re "^\\*+ " :fail-re "^\\*+ " :narrow t)
  org-scan-tags(org-encrypt-entry (lambda (todo tags-list level) (progn (setq org-cached-props nil) (or (and (member "crypt" tags-list))))) nil)
  org-encrypt-entries()
  funcall(org-encrypt-entries)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(org-encrypt-entries)
  run-hook-wrapped(doom-run-hook org-encrypt-entries)
  (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(before-save-hook)
  apply(doom-run-hooks before-save-hook)
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

### Describe your attempts to resolve the issue

Workaround is to pin previous versions in `packages.el` and do `doom sync && doom build` after deleting local repos and build directories:

```lisp
(package! org
  :recipe (:host nil
           :repo "https://git.savannah.gnu.org/git/emacs/org-mode.git"
           :files (:defaults "etc")
           :depth 1
           :build t
           :pre-build
           (with-temp-file "org-version.el"
             (insert "(defun org-release () \"9.5\")\n"
                     (format "(defun org-git-version (&rest _) \"9.5-??-%s\")\n"
                             (cdr (doom-call-process "git" "rev-parse" "--short" "HEAD")))
                     "(provide 'org-version)\n")))
  :pin "cc2490a7061955395c4f5a1a23a088044554a2f7")
(package! org-contrib
  :pin "b8012e759bd5bf5da802b0b41734a8fec218323c")
(package! ox-hugo
  :pin "f0357fa7449cc8baecee588dab7dcf9ea243f3b4")
```

### Steps to reproduce

Do `~/.emacs.d/bin/doom upgrade` to get latest doom-emacs version.

### System Information

https://pastebin.com/raw/krNjeQiU

**Comment by slebedev** [comment]
Unfortunately I don't remember my attempts to resolve the issue without downgrading org - I tried to delete just org file and do `doom sync`, and applied another workaround from discord chat:

```lisp
(defun native-comp-available-p nil)
```

But I have no clue what side-effects may be with this workaround, so I've decided just to downgrade org package regarding [bump commit](https://github.com/hlissner/doom-emacs/commit/20b74b79512c1c5e5866a389513c71a032f55d83) I mentioned in the issue.

**Comment by jeep** [comment]
I just came here to see if this was a known issue as I did an upgrade today and started seeing it.

**Comment by slebedev** [comment]
I don't see such function for emacs-27.1/emacs-27.2, it's in [emacs-28](https://github.com/emacs-mirror/emacs/blob/emacs-28/src/comp.c#L5313)

**Comment by kyperbelt** [comment]
Having the same exact issue that just happened after the upgrade.

**Comment by slebedev** [comment]
So, it seems to be fixed (see [org-mode mailing list](https://list.orgmode.org/87tugzinxz.fsf@gmail.com/T/#u)), but there's some issue - I see [a commit with fix](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=49e2f6c1abd16f47dd849ba15917243f6234ea55) in upstream, but there's no such commit in [emacs-straight/org-mode](https://github.com/emacs-straight/org-mode/commits/main) mirror...

**Comment by BR00l** [comment]
> So, it seems to be fixed (see [org-mode mailing list](https://list.orgmode.org/87tugzinxz.fsf@gmail.com/T/#u)), but there's some issue - I see [a commit with fix](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=49e2f6c1abd16f47dd849ba15917243f6234ea55) in upstream, but there's no such commit in [emacs-straight/org-mode](https://github.com/emacs-straight/org-mode/commits/main) mirror...

Same here, tried to see if everyhting is all right now, no luck yet.

**Comment by lotusroot13** [comment]
Check this temporary fix from [org-roam issue](https://github.com/org-roam/org-roam/issues/1929) by @dirodriguezm, add `(defun native-comp-available-p () nil)` to `config.el`

**Comment by slebedev** [comment]
> Check this temporary fix from [org-roam issue](https://github.com/org-roam/org-roam/issues/1929) by @dirodriguezm, add `(defun native-comp-available-p () nil)` to `config.el`

I mentioned this workaround in my first comment here, it works also. 

This is a runtime function introduced in emacs28 - it should return non-nil if emacs was build with native-comp.

**Comment by hlissner** [comment]
This issue should now be resolved (caused by an unguarded `native-comp-available-p` call in org, upstream). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Thomashrb** [comment]
I git pulled .emacs.d (with your fix on develop), called bin/doom sync and restarted emacs just now and it is still broken for me unfortunately so I do not think it is fixed.

**Comment by slebedev** [comment]
@hlissner thank you!

I've just upgraded and checked original issue - it's resolved for me now!
