### ISSUE TITLE
org-roam v2 backlinks panel shows the whole link content instead of relevant part

### ISSUE THREAD

**Issue by brunoarine** [hlissner/doom-emacs#5766]
### What did you expect to happen?

When I open an org-roam node, the backlinks panel on the right should show all nodes that reference the currently open node, but only the backlinks' titles and the relevant paragraphs where the referenced node is linked.

### What actually happened?

The backlinks panel show the whole backlinking node content, including the `PROPERTIES` drawer. That didn't happen in revision `4eeb3c7a19` (5 weeks ago, [see comparison](https://github.com/hlissner/doom-emacs/compare/4eeb3c7a19c324f5a7839a2e3edb03fc87d23034...b4cc1c84d8e77e3a5cb2175be4908b6ce46d93a6))

![Screenshot from 2021-11-11 14-04-03](https://user-images.githubusercontent.com/5541244/141339941-64139d59-a75f-4a38-ac51-195aecfd5f57.png)

### Steps to reproduce

1. Install org-roam by including `(org +roam2)` in Doom's `init.el`
2. Run `doom sync`
3. Open emacs
4. Create an org-roam node
5. Create a second org-roam node
6. Insert a link to the first node in the second node
7. Open the first node's window and the backlinks panel will appear automatically, showing the entire second node content.

### System Information

https://pastebin.com/6brTeuQQ

**Comment by mandos** [comment]
Isn't the same problem as here https://github.com/org-roam/org-roam/issues/1934?

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by brunoarine** [comment]
Hi @hlissner, sorry for the late response! I've just upgraded Doom and the issue is still there.

```
Doom emacs	v21.12.0-alpha   HEAD -> develop af7c1d79b 2021-12-18 01:13:37 +0100
Doom core	v3.0.0-alpha     HEAD -> develop af7c1d79b 2021-12-18 01:13:37 +0100
```
