### ISSUE TITLE
New Emacs version seems to have broken Doom

### ISSUE THREAD

**Issue by GuiHeurich** [hlissner/doom-emacs#6259]
### What did you expect to happen?

Open Emacs without issues.

### What actually happened?

````
Debugger entered--Lisp error: (void-function doom-partial)
  (doom-partial #'add-to-list 'comp-deferred-compilation-deny-list)
  (mapc (doom-partial #'add-to-list 'comp-deferred-compilation-deny-list) (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir)))) (list (concat local-dir-re ".*/evil-collection-vterm\\.el\\'") (concat local-dir-re ".*/jupyter-channel\\.el\\'") (concat local-dir-re ".*/with-editor\\.el\\'") (concat "\\`" (regexp-quote doom-autoloads-file) "\\'"))))
  (closure (t) nil (mapc (doom-partial #'add-to-list 'comp-deferred-compilation-deny-list) (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir)))) (list (concat local-dir-re ".*/evil-collection-vterm\\.el\\'") (concat local-dir-re ".*/jupyter-channel\\.el\\'") (concat local-dir-re ".*/with-editor\\.el\\'") (concat "\\`" (regexp-quote doom-autoloads-file) "\\'")))) (defadvice! doom--comp-use-all-cores-a nil :override #'comp-effective-async-max-jobs (if (= 0 comp-async-jobs-number) (setq comp-num-cpus (doom-num-cpus)) comp-async-jobs-number)))()
  eval-after-load(comp (closure (t) nil (mapc (doom-partial #'add-to-list 'comp-deferred-compilation-deny-list) (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir)))) (list (concat local-dir-re ".*/evil-collection-vterm\\.el\\'") (concat local-dir-re ".*/jupyter-channel\\.el\\'") (concat local-dir-re ".*/with-editor\\.el\\'") (concat "\\`" (regexp-quote doom-autoloads-file) "\\'")))) (defadvice! doom--comp-use-all-cores-a nil :override #'comp-effective-async-max-jobs (if (= 0 comp-async-jobs-number) (setq comp-num-cpus (doom-num-cpus)) comp-async-jobs-number))))
  load-with-code-conversion("/home/guilhermeorlandiniheurich/.emacs.d/core/core.el" "/home/guilhermeorlandiniheurich/.emacs.d/core/core.el" nil t)
  load("/home/guilhermeorlandiniheurich/.emacs.d/core/core.el" nil t)
  load-with-code-conversion("/home/guilhermeorlandiniheurich/.emacs.d/bin/doom" "/home/guilhermeorlandiniheurich/.emacs.d/bin/doom" nil t)
  command-line-1(("-scriptload" "/home/guilhermeorlandiniheurich/.emacs.d/bin/doom" "--" "doctor"))
  command-line()
  normal-top-level()
```

### Describe your attempts to resolve the issue

I have tried running `doom doctor` and `doctor build` but they display the same error. I didn't try deleting and cloning emacs again because I'm afraid of losing data. 

### Steps to reproduce

1. Try opening emacs.

### System Information

NOT AVAILABLE

**Comment by loopier** [comment]
Same here. I did try reinstalling Doom and Emacs.I also tried downgrading to Emacs 27.2 and 27.1 and the problem persists

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by GuiHeurich** [comment]
Thank you for that. But, unfortunately, it's not fixed for me. Still can't run any doom commands. This is the (part of the) error now:

`void-variable comp-deferred-compilation-deny-list)

(cl-some #'(lambda (re) (string-match-p re file)) comp-deferred-compilation-deny-list)

(not (cl-some #'(lambda (re) (string-match-p re file)) comp-deferred-compilation-deny-list))

(straight--native-compile-file-p "/home/guilhermeorlandiniheurich/.emacs.d/.local/straight/build-28.1/el-get/el-get.el")`

**Comment by loopier** [comment]
It solved it for me.

**Comment by shonfeder** [comment]
I had to rollback to emacs 27.1 and do a fresh install of doom to get the `doom` command to run without crashing.

**Comment by shonfeder** [comment]
This is the traceback I was getting on 28.1:

https://gist.github.com/shonfeder/6fc38bcc1306926cb4a29d0100e849bf

**Comment by GuiHeurich** [comment]
> I had to rollback to emacs 27.1 and do a fresh install of doom to get the `doom` command to run without crashing.

Me too. It works fine now - a bit better, actually,. :)

**Comment by shonfeder** [comment]
On discord, [hlissner](https://github.com/hlissner) suggested this might be a problem with the snap packaging, and i was indeed using snap before downgrading to 27.1. So perhaps that additional bit of info can helps someone else in the future! :)

**Comment by hlissner** [comment]
@GuiHeurich @shonfeder Your issues are not relevant to this one. Please create another if you're still experiencing it.

I've renamed this thread to better reflect what it was reporting, and locked it because the original problem was definitively resolved.
