### ISSUE TITLE
Develop is sort of totally broken.

### ISSUE THREAD

**Issue by HaoZeke** [hlissner/doom-emacs#701]
All commits from 03022d09f9e47e6786003a728b020fd59dd30395 onwards break everything.
The last working commit is 648f4bb5859536dfe167542b07aff7bc4d4c447e

The break is basically due to 

```bash
Unable to find theme file for ‘doom-one’
```

**Comment by hlissner** [comment]
Would you kindly expand on "sort of totally broken"? Error messages and backtraces would be much appreciated. Perhaps a link to your own config, if it's up somewhere. There have been many changes recently.

If you run emacs in debug mode with `emacs --debug-init`, it will produce more helpful error messages.

**Comment by hlissner** [comment]
Ah, didn't see your edit. Please run `bin/doom refresh` (or `make`) and see if that fixes your issue.

**Comment by HaoZeke** [comment]
@hlissner on the latest commit (ae6c3cacf2cc04b1fdaddfd941a142a94550b8bb) I am still getting the same error:

```bash
./bin/doom refresh                            
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Initializing modules
Doom core autoloads is up-to-date
Looking for orphaned packages...
Looking for packages to install...
No packages to install!
Doom package autoloads is up-to-date
Recompiled 0/1 file(s) (203 ignored)
```

This still gives me:

```emacs-lisp
Error in a Doom startup hook: doom|init-ui, (doom-hook-error doom|init-theme (error "Unable to find theme file for ‘doom-one’"))
```

My current configuration is [here](https://github.com/HaoZeke/Dotfiles/tree/master/dotfiles/emacs/.doom.d) but it works from the commit before the refactoring, as mentioned.

**Comment by hlissner** [comment]
Nothing in your config seems amiss, so could you try `bin/doom autoloads` instead? This will force regeneration of the autoloads files, which is usually to blame when Emacs can't find an installed package.

**Comment by HaoZeke** [comment]
That gives an error I noticed from the [this](51f2ea29323e6b5bcfc6421303732ab363b9609f) commit onwards:

```bash
./bin/doom autoloads                 
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Initializing modules
Deleted old autoloads.el
Generating new autoloads.el
✓ Scanned core/autoload/ui.el
✓ Scanned core/autoload/scratch.el
✓ Scanned core/autoload/projects.el
✓ Scanned core/autoload/packages.el
✓ Scanned core/autoload/message.el
✓ Scanned core/autoload/menu.el
✓ Scanned core/autoload/memoize.el
✓ Scanned core/autoload/help.el
✓ Scanned core/autoload/files.el
✓ Scanned core/autoload/editor.el
✓ Scanned core/autoload/debug.el
✓ Scanned core/autoload/cache.el
✓ Scanned core/autoload/buffers.el
✓ Scanned modules/completion/company/autoload.el
⚠ Ignoring modules/completion/ivy/autoload/posframe.el
✓ Scanned modules/completion/ivy/autoload/ivy.el
✓ Scanned modules/completion/ivy/autoload/evil.el
✓ Scanned modules/config/default/autoload/evil.el
✓ Scanned modules/config/default/autoload/default.el
✓ Scanned modules/config/literate/autoload.el
✓ Scanned modules/emacs/electric/autoload.el
✓ Scanned modules/emacs/term/autoload.el
✓ Scanned modules/feature/eval/autoload/settings.el
✓ Scanned modules/feature/eval/autoload/repl.el
✓ Scanned modules/feature/eval/autoload/evil.el
✓ Scanned modules/feature/eval/autoload/eval.el
✓ Scanned modules/feature/evil/autoload/folds.el
✓ Scanned modules/feature/evil/autoload/files.el
✓ Scanned modules/feature/evil/autoload/evil.el
✓ Scanned modules/feature/evil/autoload/evil-mc.el
✓ Scanned modules/feature/file-templates/autoload.el
✓ Scanned modules/feature/lookup/autoload/lookup.el
✓ Scanned modules/feature/lookup/autoload/evil.el
✓ Scanned modules/feature/lookup/autoload/docsets.el
✓ Scanned modules/feature/lookup/autoload/devdocs.el
✓ Scanned modules/feature/snippets/autoload/snippets.el
✓ Scanned modules/feature/snippets/autoload/settings.el
✓ Scanned modules/feature/snippets/autoload/evil.el
✓ Scanned modules/feature/syntax-checker/autoload.el
✓ Scanned modules/feature/version-control/autoload.el
✓ Scanned modules/feature/workspaces/autoload/workspaces.el
✓ Scanned modules/feature/workspaces/autoload/evil.el
✓ Scanned modules/lang/cc/autoload.el
✓ Scanned modules/lang/emacs-lisp/autoload.el
✓ Scanned modules/lang/latex/autoload.el
✓ Scanned modules/lang/markdown/autoload.el
✓ Scanned modules/lang/org/autoload/tables.el
✓ Scanned modules/lang/org/autoload/org.el
✓ Scanned modules/lang/org/autoload/org-present.el
✓ Scanned modules/lang/org/autoload/org-link.el
✓ Scanned modules/lang/org/autoload/org-capture.el
✓ Scanned modules/lang/org/autoload/org-attach.el
⚠ Ignoring modules/lang/org/autoload/ipython.el
✓ Scanned modules/lang/python/autoload.el
⚠ Ignoring modules/lang/python/autoload/conda.el
✓ Scanned modules/lang/sh/autoload.el
✓ Scanned modules/lang/web/autoload/html.el
✓ Scanned modules/lang/web/autoload/evil.el
✓ Scanned modules/lang/web/autoload/css.el
✓ Scanned modules/tools/magit/autoload.el
✓ Scanned modules/tools/rotate-text/autoload.el
✓ Scanned modules/ui/doom-dashboard/autoload.el
✓ Scanned modules/ui/doom-modeline/autoload.el
✓ Scanned modules/ui/fci/autoload.el
✓ Scanned modules/ui/hl-todo/autoload.el
✓ Scanned modules/ui/nav-flash/autoload.el
✓ Scanned modules/ui/neotree/autoload.el
✓ Scanned modules/ui/popup/autoload/settings.el
✓ Scanned modules/ui/popup/autoload/popup.el
✓ Scanned modules/ui/unicode/autoload.el
✓ Scanned modules/ui/vi-tilde-fringe/autoload.el
✓ Expanded module autoload paths
✓ Generated autodefs
✓ Clean up autoloads

Deleted old autoloads.pkg.el
Symbol’s value as variable is void: import
```

The error is then:

```emacs-lisp
Warning (initialization): An error occurred while loading ‘/home/haozeke/.emacs.d/init.el’:

: Your package autoloads are missing! Run ‘bin/doom refresh’ to regenerate them

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by hlissner** [comment]
Try `bin/doom --debug autoloads` and see if it produces a more helpful error message.

**Comment by hlissner** [comment]
Very strange. Could you show me the output of `bin/doom info`.

**Comment by HaoZeke** [comment]
Yup:

```bash
bin/doom info                
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Generating Doom info...
Initializing modules
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop ae6c3cacf2cc04b1fdaddfd941a142a94550b8bb)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux myarchbox 4.16.16-1-ck-haswell #1 SMP PREEMPT Sat Jun 16 08:24:52 EDT 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline evil-goggles fci hl-todo nav-flash neotree (popup +all +defaults) unicode vi-tilde-fringe window-select :emacs ediff electric imenu term :tools magit pdf rotate-text :lang data emacs-lisp latex markdown (org +attach +babel +capture +export +present) python ruby sh web :config (default +bindings +snippets +evil-commands))
  packages:  n/a
  exec-path: (~/.zplug/bin ~/Git/Github/Dotfiles/Scripts ~/.node_modules/bin ~/.yarn/bin ~/.local/bin ~/bin /bin /usr/local/bin /usr/bin /usr/local/sbin /opt/cxoffice/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.rvm/bin ~/.local/bin/gitHelpers ~/.local/bin/droidHelpers ~/.local/bin/dockerHelpers ~/.local/bin/shellHelpers ~/.local/bin/fileHelpers ~/.local/bin/webHelpers ~/.local/bin/installHelpers ~/.cargo/bin ~/.go/bin ~/Git/Github/Linux/xmr-stak-cpu/bin /var/lib/snapd/snap/bin //home/haozeke/.gem/ruby/2.4.0/bin ~/LabWork/IITB/Icover /root/.gem/ruby/2.2.0/bin ~/Matlab/MATLAB_Production_Server/R2015a/bin ~/.gem/ruby/2.2.0/bin ~/.gem/ruby/2.3.0/bin /opt/schrodinger2016-2 ~/Git/Github/mylammps/src ~/Git/Github/espresso/build ~/Git/Github/Scripts/Build ~/Git/Github/Scripts/System ~/.local/g16 /usr/local/MATLAB/R2017a/bin /usr/local/MATLAB/R2017a/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```

**Comment by hlissner** [comment]
Does `~/.emacs.d/.local/autoloads.el` exist for you? If it doesn't, please update to the latest Doom (just pushed it a minute ago) and invoke the error again and Doom will save the errant autoloads file into `~/.emacs.d/.local/autoloads.el.bak`.

Please send that file to me.

**Comment by HaoZeke** [comment]
I do have `~/.emacs.d/.local/autoloads.el` with the latest Doom... However I am unable to produce the `autoloads.el.bak` file...

```bash
$ ./bin/doom autoloads     
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Wrong type argument: stringp, nil
$ cd .local/ 
$ ls
:  autoloads.el  autoloads.elc  autoloads.pkg.el  autoloads.pkg.elc  cache  emacs-version.el  etc  packages
```

**Comment by hlissner** [comment]
Sorry, there was a regression. I just pushed a fix for the `stringp` error. Please update and try once more.

**Comment by HaoZeke** [comment]
Still the same errors [with the latest commit](https://github.com/hlissner/doom-emacs/commit/279ee3cc8c9c22f9429d7405d22782c2d1f297b2)..

```bash
$ make  
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Initializing modules
Doom core autoloads is up-to-date
Looking for orphaned packages...
Looking for packages to install...
No packages to install!
Doom package autoloads is up-to-date
Error in a Doom startup hook: doom|init-ui, (doom-hook-error doom|init-theme (error "Unable to find theme file for ‘doom-one’"))
make: *** [Makefile:5: all] Error 255

```bash
$ ./bin/doom -d install 
Debug mode on
Loading /home/haozeke/.emacs.d/early-init.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/packages.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/cache.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/debug.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/message.el (source)...
Initializing modules
Loading /home/haozeke/.emacs.d/modules/config/literate/init.el (source)...
Doom core autoloads is up-to-date
Looking for packages to install...
Wrong type argument: symbolp, (closure ((p install :desc "Installs requested plugins that aren't installed." :body #0) t) (args) (doom--do (quote doom-packages-install)))
```

```bash
./bin/doom -d autoloads       
Debug mode on
✓ Expanded module autoload paths
✓ Generated autodefs
✓ Clean up autoloads

Compiling /home/haozeke/.emacs.d/.local/autoloads.el...
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (doom-project-expand)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (doom/describe-setting)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (doom/help)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (doom-buffer-list)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (other-popup)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (set-email-account!)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (set-eshell-alias!)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el... (set-pretty-symbols!)
Compiling /home/haozeke/.emacs.d/.local/autoloads.el...done
Deleted old autoloads.pkg.el
Wrong type argument: symbolp, (closure ((p autoloads :desc "Regenerates Doom's autoloads file.

This file tells Emacs where to find your module's autoloaded functions and
plugins." :body #0) t) (args) (doom-reload-autoloads nil (quote force)))
```

Emacs gives:

```emacs-lisp
Warning (initialization): An error occurred while loading ‘/home/haozeke/.emacs.d/init.el’:

: Your package autoloads are missing! Run ‘bin/doom refresh’ to regenerate them

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Finally, `bin/doom -d refresh` gives:

```bash
Error in a Doom startup hook: doom|init-ui, (doom-hook-error doom|init-theme (error "Unable to find theme file for ‘doom-one’"))
```

Also, @hlissner, don't apologize! I'm glad you're taking the time to help me get this working again.

**Comment by hlissner** [comment]
```
Wrong type argument: symbolp, (closure ((p autoloads :desc "Regenerates Doom's autoloads file.

This file tells Emacs where to find your module's autoloaded functions and
plugins." :body #0) t) (args) (doom-reload-autoloads nil (quote force)))
```

That is a very strange error. I can't reproduce it, but I am confident it is the root cause of all this. Could you pastebin your `autoloads.pkg.el` (or `autoloads.pkg.el.bak`) file?

This file is responsible for setting your `load-path` and `custom-theme-load-path` (among other things), so if it is failing to generate/run, it's natural Emacs won't be able to find the theme.

**Comment by HaoZeke** [comment]
Sure, it's been [uploaded here](https://pastebin.com/BX9aChe3).

**Comment by hlissner** [comment]
Could you try this change, in [core/core-dispatcher.el (line 82)](https://github.com/hlissner/doom-emacs/blob/develop/core/core-dispatcher.el#L82):

```diff
         `((dolist (alias ',aliases)
             (map-put doom--dispatch-alias-alist alias ',cmd))))
       `((map-put doom--dispatch-command-alist ',cmd
                  (list :desc ,docstring
-                       :body (lambda (args) ,form))))))))
+                       :body '(lambda (args) ,form))))))))
 
 
 ;;
 ;; Dispatch commands
 ;;
```

Then try `bin/doom autoloads` again to see if it fixes your issue?

**Comment by HaoZeke** [comment]
Yup, tried it, but there is no change. Still getting

```bash
Symbol’s value as variable is void: import
```

**Comment by hlissner** [comment]
Are you able to produce that `Symbol’s value as variable is void: import` error specifically when you run `doom --debug autoloads`. 

If not, check if `autoloads.pkg.el` exists. If it does not, check if `autoloads.pkg.el.bak` does. If so, hastebin that file to me.

**Comment by hlissner** [comment]
Also, if you aren't aware, [we have a Discord server](https://discord.gg/bcZ6P3y). Perhaps its best we carry on this process in real time.

**Comment by HaoZeke** [comment]
With `doom --debug autoloads` I get:

```bash
Compiling /home/haozeke/.emacs.d/.local/autoloads.el...done
Deleted old autoloads.pkg.el
Wrong type argument: symbolp, (closure ((p autoloads :desc "Regenerates Doom's autoloads file.

This file tells Emacs where to find your module's autoloaded functions and
plugins." :body #0) t) (args) (doom-reload-autoloads nil (quote force)))
```
Also I no longer get any `autoloads.pkg.el` at all, or the `.bak` file.

```bash
autoloads.el   cache             etc
autoloads.elc  emacs-version.el  packages
```

I can get an `autoloads.pkg.el` by running `make`.

That file is [here](https://hastebin.com/avusodahex).

**Comment by hlissner** [comment]
After much hunting, I've finally zeroed in on the cause of the symbolp closure error in 84756b3. Please update, then run `bin/doom refresh` and let me know if it resolves your issue!

**Comment by HaoZeke** [comment]
New errors..

When emacs starts:

```emacs-lisp
Warning (initialization): An error occurred while loading ‘/home/haozeke/.emacs.d/init.el’:

: Your package autoloads are missing! Run ‘bin/doom refresh’ to regenerate them

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

From `doom refresh`

```bash
Initializing modules
Doom core autoloads is up-to-date
Looking for orphaned packages...
Looking for packages to install...
No packages to install!
Doom package autoloads is up-to-date

--------------------------------------------------

There was an unexpected error:
  Error in a Doom module (doom-module-error)
  modules/config/default/+bindings.el
  (void-function evil-define-key*)

Run the command again with the -d (or --debug) option to enable debug
mode and, hopefully, generate a stack trace. If you decide to file a bug
report, please include it!

Emacs outputs to standard error, so you’ll need to redirect stderr to
stdout to pipe this to a file or clipboard!

  e.g. doom -d install 2>&1 | clipboard-program
```

From the suggested command:

```bash
 ./bin/doom -d install 2>&1                            
Debug mode on
Loading /home/haozeke/.emacs.d/core/autoload/packages.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/cache.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/debug.el (source)...
Loading /home/haozeke/.emacs.d/core/autoload/message.el (source)...
Initializing modules
Loading /home/haozeke/.emacs.d/modules/config/literate/init.el (source)...
Doom core autoloads is up-to-date
Looking for packages to install...

...
  load("/home/haozeke/.doom.d/packages.el" t t t)
  (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e))))
  (closure ((temp-buffer . #<buffer  *temp*>) (force-p) t) (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))("/home/haozeke/.doom.d/packages.el" t)
  funcall((closure ((temp-buffer . #<buffer  *temp*>) (force-p) t) (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e))))) "/home/haozeke/.doom.d/packages.el" t)
  (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))
  (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t)))
  (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))
  (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t)))))
  (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))))
  (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t)))))))
  (let ((load-prefer-newer t)) (if (eq force-p 'internal) nil (if (or force-p (not (and (boundp 'package-alist) package-alist))) (progn (setq load-path (cons doom-core-dir doom-site-load-path)) (doom-ensure-packages-initialized 'force))) (if (or force-p (not (and (boundp 'quelpa-cache) quelpa-cache))) (progn (if (featurep 'quelpa) nil (load (locate-library "quelpa.el") nil t t)) (setq quelpa-initialized-p nil) (or (quelpa-setup-p) (error "Could not initialize quelpa"))))) (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))))))
  (progn (let ((load-prefer-newer t)) (if (eq force-p 'internal) nil (if (or force-p (not (and (boundp 'package-alist) package-alist))) (progn (setq load-path (cons doom-core-dir doom-site-load-path)) (doom-ensure-packages-initialized 'force))) (if (or force-p (not (and (boundp 'quelpa-cache) quelpa-cache))) (progn (if (featurep 'quelpa) nil (load (locate-library "quelpa.el") nil t t)) (setq quelpa-initialized-p nil) (or (quelpa-setup-p) (error "Could not initialize quelpa"))))) (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t)))))))))
  (unwind-protect (progn (let ((load-prefer-newer t)) (if (eq force-p 'internal) nil (if (or force-p (not (and (boundp 'package-alist) package-alist))) (progn (setq load-path (cons doom-core-dir doom-site-load-path)) (doom-ensure-packages-initialized 'force))) (if (or force-p (not (and (boundp 'quelpa-cache) quelpa-cache))) (progn (if (featurep 'quelpa) nil (load (locate-library "quelpa.el") nil t t)) (setq quelpa-initialized-p nil) (or (quelpa-setup-p) (error "Could not initialize quelpa"))))) (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let ((load-prefer-newer t)) (if (eq force-p 'internal) nil (if (or force-p (not (and (boundp 'package-alist) package-alist))) (progn (setq load-path (cons doom-core-dir doom-site-load-path)) (doom-ensure-packages-initialized 'force))) (if (or force-p (not (and (boundp 'quelpa-cache) quelpa-cache))) (progn (if (featurep 'quelpa) nil (load (locate-library "quelpa.el") nil t t)) (setq quelpa-initialized-p nil) (or (quelpa-setup-p) (error "Could not initialize quelpa"))))) (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let ((load-prefer-newer t)) (if (eq force-p 'internal) nil (if (or force-p (not (and (boundp 'package-alist) package-alist))) (progn (setq load-path (cons doom-core-dir doom-site-load-path)) (doom-ensure-packages-initialized 'force))) (if (or force-p (not (and (boundp 'quelpa-cache) quelpa-cache))) (progn (if (featurep 'quelpa) nil (load (locate-library "quelpa.el") nil t t)) (setq quelpa-initialized-p nil) (or (quelpa-setup-p) (error "Could not initialize quelpa"))))) (if (or force-p (not doom-packages)) (progn (let* ((--cl-_load-- (function (lambda (file &optional noerror) (condition-case e (load file noerror t t) ((debug error) (signal 'doom-package-error (list (or (doom-module-from-path file) '(:private . packages)) e)))))))) (progn (let ((doom-modules (doom-modules)) (doom--stage 'packages) (noninteractive t)) (setq doom-packages nil) (funcall --cl-_load-- (expand-file-name "packages.el" doom-core-dir)) (let ((private-packages (expand-file-name "packages.el" doom-private-dir))) (funcall --cl-_load-- private-packages t) (let* ((path nil)) (maphash (function (lambda (key --cl-var--) (setq path (doom-module-path (car key) (cdr key) "packages.el")) (let ((doom--current-module key)) (funcall --cl-_load-- path t)))) doom-modules) nil) (funcall --cl-_load-- private-packages t))))))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  doom-initialize-packages()
  doom-get-missing-packages()
  (reverse (doom-get-missing-packages))
  (let ((packages (reverse (doom-get-missing-packages)))) (cond ((not packages) (print! (green "No packages to install!")) nil) ((not (or auto-accept-p (y-or-n-p (format "%s packages will be installed:\n\n%s\n\nProceed?" (length packages) (mapconcat (function (lambda (pkg) (format "+ %s (%s)" (car pkg) (cond ((doom-package-different-recipe-p (car pkg)) "new recipe") ((doom-package-different-backend-p (car pkg)) (if (plist-get (cdr pkg) :recipe) "ELPA->QUELPA" "QUELPA->ELPA")) ((plist-get (cdr pkg) :recipe) "QUELPA") ("ELPA"))))) (cl-sort (cl-copy-list packages) (function string-lessp) :key (function car)) "\n"))))) (error "Aborted!")) ((let (success) (doom-refresh-packages-maybe doom-debug-mode) (let ((--dolist-tail-- packages)) (while --dolist-tail-- (let ((pkg (car --dolist-tail--))) (print! "Installing %s" (car pkg)) (condition-case ex (progn (let ((result (or (and (package-installed-p (car pkg)) (not (doom-package-different-backend-p (car pkg))) (not (doom-package-different-recipe-p (car pkg))) 'already-installed) (and (doom-install-package (car pkg) (cdr pkg)) (setq success t) 'success) 'failure)) (pin-label (and (plist-member (cdr pkg) :pin) (format " [pinned: %s]" (plist-get (cdr pkg) :pin))))) (print! "%s%s" (cond ((eq result 'already-installed) (dark (white "⚠ ALREADY INSTALLED"))) ((eq result 'success) (green "✓ DONE")) ((eq result 'failure) (red "✕ FAILED")) (t nil)) (or pin-label "")))) ((debug quote user-error) (print! (bold (red "  NOTICE: %s" ex)))) ((debug quote file-error) (print! (bold (red "  FILE ERROR: %s" (error-message-string ex)))) (print! "  Trying again...") (if doom-debug-mode (progn (doom-refresh-packages-maybe t)) (let ((old-fn (symbol-function 'write-region))) (let ((standard-output (function (lambda (&rest _))))) (let* ((vnew (function (lambda (file) (load file nil t)))) (old (symbol-function 'load-file))) (unwind-protect (progn (fset 'load-file vnew) (let* ((vnew (function (lambda (&rest _)))) (old (symbol-function 'message))) (unwind-protect (progn (fset 'message vnew) (let* ((vnew (function (lambda (start end filename &optional append visit lockname mustbenew) (if visit nil (setq visit 'no-message)) (funcall old-fn start end filename append visit lockname mustbenew)))) (old (symbol-function 'write-region))) (unwind-protect (progn (fset 'write-region vnew) (let ((inhibit-message t)) (let ((save-silently t)) (doom-refresh-packages-maybe t)))) (fset 'write-region old)))) (fset 'message old)))) (fset 'load-file old)))))) (let ((result (or (and (package-installed-p (car pkg)) (not (doom-package-different-backend-p (car pkg))) (not (doom-package-different-recipe-p (car pkg))) 'already-installed) (and (doom-install-package (car pkg) (cdr pkg)) (setq success t) 'success) 'failure)) (pin-label (and (plist-member (cdr pkg) :pin) (format " [pinned: %s]" (plist-get (cdr pkg) :pin))))) (print! "%s%s" (cond ((eq result 'already-installed) (dark (white "⚠ ALREADY INSTALLED"))) ((eq result 'success) (green "✓ DONE")) ((eq result 'failure) (red "✕ FAILED")) (t nil)) (or pin-label ""))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (print! (bold (green "Finished!"))) (if success (progn (set-file-times doom-packages-dir) (doom-delete-autoloads-file doom-package-autoload-file))) success))))
  doom-packages-install(nil)
  funcall(doom-packages-install nil)
  (if (funcall fn doom-auto-accept) (progn (doom-reload-package-autoloads)))
  doom--do(doom-packages-install)
  (closure ((p install :desc "Installs requested plugins that aren't installed." :body #0) t) (args) (doom--do 'doom-packages-install))(nil)
  funcall((closure ((p install :desc "Installs requested plugins that aren't installed." :body #1) t) (args) (doom--do 'doom-packages-install)) nil)
  (if help (apply (function doom--dispatch-help) command desc (cdr args)) (funcall body (cdr args)))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:desc :body :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:desc :body)" (car --cl-keys--)))))) (if help (apply (function doom--dispatch-help) command desc (cdr args)) (funcall body (cdr args))))
  (let* ((--cl-rest-- (let ((sym (intern (car args)))) (or (assq sym doom--dispatch-command-alist) (assq (cdr (assq sym doom--dispatch-alias-alist)) doom--dispatch-command-alist) (error "Invalid command: %s" (car args))))) (command (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (signal 'wrong-number-of-arguments (list nil (length --cl-rest--))))) (desc (car (cdr (plist-member --cl-rest-- ':desc)))) (body (car (cdr (plist-member --cl-rest-- ':body))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:desc :body :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:desc :body)" (car --cl-keys--)))))) (if help (apply (function doom--dispatch-help) command desc (cdr args)) (funcall body (cdr args)))))
  (let ((help (equal (car args) "help"))) (if help (car-safe (prog1 args (setq args (cdr args))))) (let* ((--cl-rest-- (let ((sym (intern (car args)))) (or (assq sym doom--dispatch-command-alist) (assq (cdr (assq sym doom--dispatch-alias-alist)) doom--dispatch-command-alist) (error "Invalid command: %s" (car args))))) (command (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (signal 'wrong-number-of-arguments (list nil (length --cl-rest--))))) (desc (car (cdr (plist-member --cl-rest-- ':desc)))) (body (car (cdr (plist-member --cl-rest-- ':body))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:desc :body :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:desc :body)" (car --cl-keys--)))))) (if help (apply (function doom--dispatch-help) command desc (cdr args)) (funcall body (cdr args))))))
  doom-dispatch(("install"))
  (condition-case e (doom-dispatch args) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) 'error-message) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")))))
  (let ((default-directory emacs-dir)) (setq argv nil noninteractive 'doom) (condition-case e (doom-dispatch args) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) 'error-message) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program"))))))
  (cond ((not noninteractive) (doom|run-all-startup-hooks)) ((and (not (cdr args)) (member (car args) '("help" "h"))) (usage)) ((not args) (usage) (message "") (error "No command detected, aborting!")) ((let ((default-directory emacs-dir)) (setq argv nil noninteractive 'doom) (condition-case e (doom-dispatch args) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) 'error-message) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program"))))))))
  (let ((args (cdr (cdr (cdr command-line-args)))) (emacs-dir (or (getenv "EMACSDIR") (expand-file-name "../" (file-name-directory load-file-name))))) (while (condition-case nil (progn (string-prefix-p "-" (car args))) (error nil)) (let* ((val (car-safe (prog1 args (setq args (cdr args)))))) (cond ((member val '("--help" "-h")) (error "Did you mean 'doom help'?")) ((member val '("--debug" "-d")) (setq doom-debug-mode t) (setenv "DEBUG" "1") (message "Debug mode on")) ((member val '("--insecure" "-i")) (setenv "INSECURE" "1") (message "Insecure mode on")) ((member val '("--private" "-p")) (setq doom-private-dir (expand-file-name (concat (car-safe (prog1 args (setq args (cdr args)))) "/"))) (or (file-directory-p doom-private-dir) (error "%s does not exist" doom-private-dir)) (setenv "DOOMDIR" doom-private-dir) (message "DOOMDIR changed to %s" doom-private-dir)) ((member val '("--emacsd" "-e")) (setq emacs-dir (expand-file-name (concat (car-safe (prog1 args (setq args (cdr args)))) "/"))) (message "Emacs directory changed to %s" emacs-dir)) ((member val '("--yes" "-y")) (setq doom-auto-accept t) (setenv "YES" "1") (message "Auto-yes mode on")) (t nil)))) (or (file-directory-p emacs-dir) (error "%s does not exist" emacs-dir)) (load (expand-file-name "init" emacs-dir) nil 'nomessage) (cond ((not noninteractive) (doom|run-all-startup-hooks)) ((and (not (cdr args)) (member (car args) '("help" "h"))) (usage)) ((not args) (usage) (message "") (error "No command detected, aborting!")) ((let ((default-directory emacs-dir)) (setq argv nil noninteractive 'doom) (condition-case e (doom-dispatch args) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) 'error-message) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")))))))))
  eval-buffer(#<buffer  *load*> nil "/home/haozeke/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 4693
  load-with-code-conversion("/home/haozeke/.emacs.d/bin/doom" "/home/haozeke/.emacs.d/bin/doom" nil t)
  load("/home/haozeke/.emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "./bin/doom" "--" "-d" "install"))
  command-line()
  normal-top-level()
```

```bash
$ ./bin/doom autoloads                          
Initializing modules
Deleted old autoloads.el
Generating new autoloads.el
✓ Scanned core/autoload/ui.el
✓ Scanned core/autoload/scratch.el
✓ Scanned core/autoload/projects.el
✓ Scanned core/autoload/packages.el
✓ Scanned core/autoload/message.el
✓ Scanned core/autoload/menu.el
✓ Scanned core/autoload/memoize.el
✓ Scanned core/autoload/help.el
✓ Scanned core/autoload/files.el
✓ Scanned core/autoload/editor.el
✓ Scanned core/autoload/debug.el
✓ Scanned core/autoload/cache.el
✓ Scanned core/autoload/buffers.el
✓ Scanned modules/completion/company/autoload.el
⚠ Ignoring modules/completion/ivy/autoload/posframe.el
✓ Scanned modules/completion/ivy/autoload/ivy.el
✓ Scanned modules/completion/ivy/autoload/evil.el
✓ Scanned modules/config/default/autoload/evil.el
✓ Scanned modules/config/default/autoload/default.el
✓ Scanned modules/config/literate/autoload.el
✓ Scanned modules/emacs/electric/autoload.el
✓ Scanned modules/emacs/term/autoload.el
✓ Scanned modules/feature/eval/autoload/settings.el
✓ Scanned modules/feature/eval/autoload/repl.el
✓ Scanned modules/feature/eval/autoload/evil.el
✓ Scanned modules/feature/eval/autoload/eval.el
✓ Scanned modules/feature/evil/autoload/folds.el
✓ Scanned modules/feature/evil/autoload/files.el
✓ Scanned modules/feature/evil/autoload/evil.el
✓ Scanned modules/feature/evil/autoload/evil-mc.el
✓ Scanned modules/feature/file-templates/autoload.el
✓ Scanned modules/feature/lookup/autoload/lookup.el
✓ Scanned modules/feature/lookup/autoload/evil.el
✓ Scanned modules/feature/lookup/autoload/docsets.el
✓ Scanned modules/feature/lookup/autoload/devdocs.el
✓ Scanned modules/feature/snippets/autoload/snippets.el
✓ Scanned modules/feature/snippets/autoload/settings.el
✓ Scanned modules/feature/snippets/autoload/evil.el
✓ Scanned modules/feature/syntax-checker/autoload.el
✓ Scanned modules/feature/version-control/autoload.el
✓ Scanned modules/feature/workspaces/autoload/workspaces.el
✓ Scanned modules/feature/workspaces/autoload/evil.el
✓ Scanned modules/lang/cc/autoload.el
✓ Scanned modules/lang/emacs-lisp/autoload.el
✓ Scanned modules/lang/latex/autoload.el
✓ Scanned modules/lang/markdown/autoload.el
✓ Scanned modules/lang/org/autoload/tables.el
✓ Scanned modules/lang/org/autoload/org.el
✓ Scanned modules/lang/org/autoload/org-present.el
✓ Scanned modules/lang/org/autoload/org-link.el
✓ Scanned modules/lang/org/autoload/org-capture.el
✓ Scanned modules/lang/org/autoload/org-attach.el
⚠ Ignoring modules/lang/org/autoload/ipython.el
✓ Scanned modules/lang/python/autoload.el
⚠ Ignoring modules/lang/python/autoload/conda.el
✓ Scanned modules/lang/sh/autoload.el
✓ Scanned modules/lang/web/autoload/html.el
✓ Scanned modules/lang/web/autoload/evil.el
✓ Scanned modules/lang/web/autoload/css.el
✓ Scanned modules/tools/magit/autoload.el
✓ Scanned modules/tools/rotate-text/autoload.el
✓ Scanned modules/ui/doom-dashboard/autoload.el
✓ Scanned modules/ui/doom-modeline/autoload.el
✓ Scanned modules/ui/fci/autoload.el
✓ Scanned modules/ui/hl-todo/autoload.el
✓ Scanned modules/ui/nav-flash/autoload.el
✓ Scanned modules/ui/neotree/autoload.el
✓ Scanned modules/ui/popup/autoload/settings.el
✓ Scanned modules/ui/popup/autoload/popup.el
✓ Scanned modules/ui/unicode/autoload.el
✓ Scanned modules/ui/vi-tilde-fringe/autoload.el
✓ Expanded module autoload paths
✓ Generated autodefs
✓ Clean up autoloads

Deleted old autoloads.pkg.el
--------------------------------------------------

There was an unexpected error:
  Error with packages (doom-package-error)
  (:private . packages)
  (void-variable import)

Run the command again with the -d (or --debug) option to enable debug
mode and, hopefully, generate a stack trace. If you decide to file a bug
report, please include it!

Emacs outputs to standard error, so you’ll need to redirect stderr to
stdout to pipe this to a file or clipboard!

  e.g. doom -d install 2>&1 | clipboard-program
```

Finally, from `make` I get this `autoloads.pkg.el` [hasted here](https://hastebin.com/ubamahiqix).

I shall move to the discord server to continue this.

**Comment by ar1a** [comment]
Maybe try deleting .emacs.d and reinstalling doom?

**Comment by HaoZeke** [comment]
@ar1a  done before every new bug report.. :)

**Comment by HaoZeke** [comment]
Thanks for the hard work!

**Comment by ar1a** [comment]
What was the solution?

**Comment by hlissner** [comment]
@ar1a There were three separate problems:

```
Wrong type argument: symbolp, (closure ((p autoloads :desc "Regenerates Doom's autoloads file.

This file tells Emacs where to find your module's autoloaded functions and
plugins." :body #0) t) (args) (doom-reload-autoloads nil (quote force)))
```

Which was fixed in 84756b3, caused by an advise function that lacked type checks.

```
There was an unexpected error:
  Error with packages (doom-package-error)
  (:private . packages)
  (void-variable import)
```

Caused by some python import statements that had snuck into his `~/.doom.d/packages.el`.

```
Unable to find theme file for ‘doom-one’
```

Caused by his autoloads files not being fully generated when running `bin/doom autoloads`. Fixing the other two issues fixed this one.

**Comment by ar1a** [comment]
> Caused by some python import statements that had snuck into his ~/.doom.d/packages.el.

too real, haha. we've all been there.
